### ISSUE TITLE
Windows can't build miso

### ISSUE THREAD

**Issue by Gurkenglas** [dmjio/miso#144]
Because ghcjs [can't](http://sprunge.us/HMeA) build [ansi-terminal](https://hackage.haskell.org/package/ansi-terminal) on Windows, [because ansi-terminal uses C primitives for its Windows compatibility](https://hackage.haskell.org/package/ansi-terminal-0.6.3.1/src/System/Console/ANSI/Windows/Foreign.hs) which are not available in javascript.

**Comment by dmjio** [comment]
Ah, hmm, this might be something to file on the GHCJS issue tracker, we might need to add shims for this. Would be interesting to see if others have ran into this.

**Comment by dmjio** [comment]
@Gurkenglas any updates on this?

**Comment by Gurkenglas** [comment]
Nope, see the ghcjs issue.

**Comment by dmjio** [comment]
@Gurkenglas https://ci.appveyor.com gives free CI for windows. Going to try and repro there.

**Comment by dmjio** [comment]
https://github.com/dmjio/miso/issues/186

**Comment by dmjio** [comment]
@Gurkenglas, the appveyor build successfully bootstraps `GHCJS` on windows and builds `miso` using the following commads:

```
cp stack/ghcjs7103/stack.yaml .
stack setup
stack build
```

It's also using this version of stack: http://www.stackage.org/stack/windows-i386

Can you elaborate on what your setup is?

**Comment by dmjio** [comment]
Per separate conversation and appveyor windows build, @Gurkenglas and I were able to get ghcjs7103 bootstrapping and building on Windows.

**Comment by dmjio** [comment]
Re-open if this problem persists.
