### ISSUE TITLE
Add to Stackage?

### ISSUE THREAD

**Issue by amar47shah** [dmjio/miso#149]
Can this project be added to [Stackage](https://github.com/fpco/stackage/#add-your-package)?

If it is desirable but not yet possible to include the project in Stackage, what contributions would be welcome as preparation?

**Comment by dmjio** [comment]
Yes, we can do that for sure. Let me look into what that would take.

**Comment by dmjio** [comment]
https://github.com/fpco/stackage/pull/2630

**Comment by dmjio** [comment]
@amar47shah, merged into stackage, closing.

**Comment by amar47shah** [comment]
thanks!
