### ISSUE TITLE
Website

### ISSUE THREAD

**Issue by dmjio** [dmjio/miso#153]
haskell-miso.org or needs to happen. This could be a good example of how to use the isomorphic functionality as well, so putting it in the main repo might not be a bad idea.

**Comment by stilesb** [comment]
Do you have a preferred HTML template? Or entirely written in Miso? What about content?

**Comment by dmjio** [comment]
@stilesb, right now it's just written entirely with `miso`, but @stepcut has used `hsx` with miso before (more inline with actual `HTML`). To make it easier to generate miso's templating language, I've thrown together a quick script `miso-from-html` (in spirit with `blaze-from-html`), that will convert `HTML` to miso's templating language (in the gist here: #198). Am using that on https://haskell-miso.org

**Comment by stilesb** [comment]
Fantastic - eating your own dog food! Will look into this. Does most discussion happen here on GH or Slack? Or Gitter? What's best for you?

**Comment by dmjio** [comment]
@stilesb we have a [slack](https://haskell-miso-slack.herokuapp.com/), and an IRC (#haskell-miso). It seems like more people are on the slack. I am not at all opposed to using a gitter though, since it seems like slack drops public messages after 10k. Just don't want to add so many outlets as to confuse new users.

**Comment by stepcut** [comment]
If you are not familiar with HSX, `miso+HSX` looks something like this:

```
view' :: Model -> View Action
view' model = [hsx|
  <div [ on (Proxy :: Proxy BoxInfo) (\bi -> ClickEditor bi) ]>
   <p>view</p>
  </div>
  |]
```

It just uses a QuasiQuoter to transform XML into the low-level miso HTML primitives. There is a lot of information on HSX in The Happstack Book,

http://www.happstack.com/docs/crashcourse/index.html#using-hsxhsp

Some of that information is, of course, Happstack specific and irrelevant to miso. But it is still probably a good source of info on the HSX side of things.

**Comment by dmjio** [comment]
closing, since https://haskell-miso.org is live.
