### ISSUE TITLE
Add sse example

### ISSUE THREAD

**Issue by dmjio** [dmjio/miso#196]
Using as source URL http://sapid.sourceforge.net/ssetest/webkit.events.php

**Comment by cocreature** [comment]
I just took a look at this but sadly it look like we can’t use that URL since it doesn’t set CORS headers. Not sure if there is another url we could use (so far I couldn’t find one) or if we’ll a) have to host this ourselves or include a small backend with this example.

**Comment by dmjio** [comment]
I think hosting our own might be a good plan. Much in the same way we are hosting `https://haskell-miso.org`.

Have some code for an `SSE` backend w/ servant here: 
https://gist.github.com/dmjio/181edca6a7be6926fa17238d3d786b66

And some code that uses SSE (among other things), on the front end.
https://gist.github.com/dmjio/1ebfe05bdaf82d7e74437d0ad533ee46
