### ISSUE TITLE
miso-from-html

### ISSUE THREAD

**Issue by dmjio** [dmjio/miso#198]
This is a good start: 
  https://gist.github.com/dmjio/08698459424c3f73f316317214399224

**Comment by dmjio** [comment]
to test:
```
runghc Main.hs index.html
```

**Comment by FintanH** [comment]
Hi @dmjio I went AWOL there. I would love to start tackling this issue, but I'm not quite sure what you want out of it. I'm also new to the miso library so I'd say there'd be some work in understanding the library. I won't let that stop me though!

Could I have some more information as to what the goal is here?

**Comment by dmjio** [comment]
Hi @FintanH :)

> I'm also new to the miso library so I'd say there'd be some work in understanding the library. I won't let that stop me though!

We're all new to the `miso` library, so you're in good company :)

The basic idea of `miso` is centered around the [Elm architecture](https://guide.elm-lang.org/architecture/). The model, update, view paradigm. 

`miso-from-html` is what will help us construct the "view" part.

A view in miso is a function that takes any type and returns a `View` (`View` is like a DSL for constructing a virtual dom), a simple example looks like: 

```haskell
someView model = div_ [] [ text "hello world" ]
```

Under the hood this `view` will turn into a virtual dom and will eventually be drawn to the real `DOM` as a `DOM` node (`div`), with a child `TextNode` (`"hello world"`), via a diffing process.

The basic problem with this is that writing view logic can at times be onerous / tedious.  Often times the end user knows what HTML they want to express, but doesn't want to go through and write it in Haskell (think of like large twitter bootstrap HTML fragments). So, `miso-from-html` is meant to perform this tedium on behalf of the user. `miso-from-html` will take as input an `HTML` file , and return a `View` type as a `String` (or `Text`) that can be printed to stdout. This way a user can just redirect the `String` output to a file .

So a basic example would look like:

```bash
$ cat index.html
<div id="foo">bar</div>

$ ./miso-from-html index.html
div_ [ id_ "foo" ] [ text "bar" ]

$ ./miso-from-html index.html > View.hs
```

The initial implementation I have is here: https://gist.github.com/dmjio/08698459424c3f73f316317214399224

It's a little naive, but that's fine.

It parses `HTML` with [`tagsoup`](https://hackage.haskell.org/package/tagsoup) and then traverses through this structure, constructing a `String` representation of a `View`, and then prints it to the console. The goal is to have this output be recognized by `GHC` (if redirected into a Haskell file).

There is another project that is similar, [`blaze-from-html`](https://hackage.haskell.org/package/blaze-from-html). Which might serve as a good frame of reference, but their implementation seems to be a little more involved (which may or may not be necessary, hard to tell at this point). 

I hope this description has helped.

cc @cocreature

**Comment by cocreature** [comment]
Some kind of pretty-printing of the generated output (nothing too fancy, just a bit of indentation and linebreaks) would also be nice.

**Comment by FintanH** [comment]
Ya that's super helpful! I think I can start looking into it this weekend 👍

**Comment by FintanH** [comment]
Hey @dmjio, @cocreature! I have a good start here: https://github.com/FintanH/miso-from-html

Lemme know whatya think 👍

**Comment by dmjio** [comment]
@FintanH, nice work, going to make comments inline at https://github.com/FintanH/miso-from-html

**Comment by dmjio** [comment]
@FintanH you should join our slack too, if you're into that sort of thing. https://haskell-miso-slack.herokuapp.com/

**Comment by FintanH** [comment]
@dmjio I certainly am! Already in the functional programming slack at https://fpchat-invite.herokuapp.com/. I'll join now :)

**Comment by dmjio** [comment]
@FintanH, great work. I'd say this issue can be closed for now (agree?). The baseline functionality is implemented. All future dev on `miso-from-html` can occur at https://github.com/fintanH/miso-from-html. I've used it btw, works well.  🍺

**Comment by FintanH** [comment]
@dmjio: Ya, sorry I went off the radar! I have big notions of it being more but that all depends on my willpower 😛
