### ISSUE TITLE
IndexedDB Support

### ISSUE THREAD

**Issue by ahri** [dmjio/miso#200]
It would be really nice to have Web SQL support in addition to Local Storage, given that it has more space allocated by default and provides a relational model.

**Comment by dmjio** [comment]
@ahri, hmmm this is interesting, it doesn't seem to be too well-supported in IE/Firefox.
http://caniuse.com/#search=websql

Maybe we have a relational algebra engine on top of local storage, or something similar.

**Comment by LeviSchuck** [comment]
"The Web SQL Database specification is no longer being maintained and support may be dropped in future versions." (caniuse)

Integrated support may not be worth the time. Although what may be useful is something like ecto which can have many adapters.

**Comment by dmjio** [comment]
> "The Web SQL Database specification is no longer being maintained and support may be dropped in future versions." (caniuse)

@LeviSchuck, @ahri, ah well there's that too :) 

Hm, might be interesting to research different approaches.

**Comment by ahri** [comment]
Interesting. The problem with Local Storage is that it gets loaded synchronously into memory before page load, so it actually blocks loading. Chrome limits it to 5mb because of this. 

WebSQL was one was l way to get around this, but if it's effectively deprecated... 🤔

**Comment by ahri** [comment]
You know, I was confused 😕- I was thinking of [IndexedDB](http://caniuse.com/#search=Indexeddb), not WebSQL, my apologies.

**Comment by ahri** [comment]
https://developer.mozilla.org/en/docs/Web/API/IndexedDB_API lists ("See Also") a couple of libraries that wrap IndexedDB which may be helpful as reference material.

Additionally https://github.com/dfahlander/Dexie.js/issues/22 is an contains some interesting discussion of localForage's fallback to WebSQL and Local Storage.

**Comment by dmjio** [comment]
I'd say this should be implemented as a separate library, and not into `miso` proper, due to its inconsistent support across all major browsers.
