### ISSUE TITLE
Using Miso HTML DSL for email templates? 

### ISSUE THREAD

**Issue by saurabhnanda** [dmjio/miso#221]
Just wondering if it's possible to use Miso"s DSL, instead of Blaze/Lucid for html email templates? This would allow our project to have a single library for generating HTML.

**Comment by dmjio** [comment]
When using `miso` on the server, w/ GHC, there exists a `ToHtml` instance for `View` that can compile `miso` templates to lucid HTML. This might satisfy that requirement.

**Comment by saurabhnanda** [comment]
Ah okay, seem to have missed that. Thanks!
