### ISSUE TITLE
How to "mount" a Miso app to a specific pre-existing DOM element?

### ISSUE THREAD

**Issue by saurabhnanda** [dmjio/miso#223]

**Comment by cocreature** [comment]
Currently this is not possible. You can only mount it directly in the `body`. I’ve talked a bit to @dmjio about allowing other mount points but my impression was that he’d like to avoid that to keep things simple.

**Comment by LeviSchuck** [comment]
At face value that makes it difficult to do a transition of an existing app.
Can it at least work with making a web component?

**Comment by dmjio** [comment]
In practice it wouldn't be hard to add a mount point, where one could initialize a miso application from (e.g. `data App = App { mountPoint :: Maybe MisoString ... }`),  where if no mount point was specified we could simply mount to `<body>`, and all diffing could take place from this node.

@saurabhnanda, @LeviSchuck, I guess I'd like to know more about the use case here.

If someone is going to try to embed a `ghcjs` application into an existing application (by specifying a mount point  for it) they'd be pulling in a lot of javascript (i.e. `rts.js`). But if Elm supports this, I'll definitely add it.

**Comment by 3noch** [comment]
A use case I've considered is trying to use Miso in a WordPress plugin or some other third-party plugin system. In those cases you can't take control of the whole `body`. Without a mount point your only option is to use an iframe which is far heavier than necessary.

**Comment by dmjio** [comment]
I think elm allows this, so we should add it.

**Comment by dwaldhalm** [comment]
I have this working with the new property `data App = App { mountPoint :: Maybe misoString }` as you suggested.  `Miso.hs : common` calls `Miso.FFI` to determine whether the configured element exists--returning either that or body.  I had to tinker with event propagation passing that element all the way down to `delegate.js : buildTargetToBody`.  If that sits well with you, I'll work on a pull request.

**Comment by dmjio** [comment]
@dwaldhalm please do, and thanks, great work! 👍 

I'll have to think about how this affects isomorphic, but regardless, PR would be fantastic.

**Comment by dwaldhalm** [comment]
pull request: https://github.com/dmjio/miso/pull/318

**Comment by dmjio** [comment]
🍻 @dwaldhalm
