### ISSUE TITLE
Update 'getting started' guide to use miso 0.7 instead of 0.4.0.0

### ISSUE THREAD

**Issue by Qqwy** [dmjio/miso#252]
I think it is appropriate to update the version of Miso that is used in the getting started guide.

The current version number is both very low (as of today we have version 0.7), and overly specific (which would not be required, assuming that Miso follows [Semantic Versioning](http://semver.org/))

**Comment by dmjio** [comment]
Miso should follow [PVP](https://pvp.haskell.org/?rdfrom=https%3A%2F%2Fwiki.haskell.org%2Findex.php%3Ftitle%3DPackage_versioning_policy%26redirect%3Dno).

In order to not get lost in "update hell" on each release (and to remove needless commits). It might be best to document how to use `nix-prefetch-git`, or `fetchFromGitHub`

```
λ nixos  nix-prefetch-git https://github.com/dmjio/miso
Initialized empty Git repository in /tmp/git-checkout-tmp-NHyEtQBf/miso/.git/
remote: Counting objects: 151, done.
remote: Compressing objects: 100% (122/122), done.
remote: Total 151 (delta 22), reused 88 (delta 11), pack-reused 0
Receiving objects: 100% (151/151), 122.97 KiB | 0 bytes/s, done.
Resolving deltas: 100% (22/22), done.
From https://github.com/dmjio/miso
 * branch            HEAD       -> FETCH_HEAD
Switched to a new branch 'fetchgit'
removing `.git'...

git revision is c4e22369551ad6fc6dc567b984cb0c5f68e469a3
path is /nix/store/89a4dm9jbhjpzf4lqv7lbs9cf07ldvc1-miso
git human-readable version is -- none --
Commit date is 2017-08-11 15:50:53 +0000
hash is 0ylsml2v5fq7z51cvq88yq1h3f4px87n3jfgil8d6xjn11r21sfr
{
  "url": "https://github.com/dmjio/miso",
  "rev": "c4e22369551ad6fc6dc567b984cb0c5f68e469a3",
  "date": "2017-08-11T15:50:53+00:00",
  "sha256": "0ylsml2v5fq7z51cvq88yq1h3f4px87n3jfgil8d6xjn11r21sfr",
  "fetchSubmodules": true
}
```

**Comment by Qqwy** [comment]
Thank you for pointing me to PVP :-).


What exactly would `nix-prefetch-git`/`fetchFromGitHub` do for us?

**Comment by cocreature** [comment]
Maybe it’s better to explain `cabal2nix` in the readme. Then this would boil down to `cabal2nix cabal://miso-0.7.0.0` which is easy to update both for us and for users if we ever forget to do so.

**Comment by srid** [comment]
The Nix section in README already mentions `cabal2nix` however it needs to describe how to use a specific (i.e., latest) version of Miso. As I understand it, you can run the above `nix-prefetch-git` command to use the `master` branch and substitute the resulting `rev` and `sha256` values to use the latest Miso. But perhaps someone else other than me might be able to document a simpler workflow.

**Comment by cocreature** [comment]
My point is that it shouldn’t describe how to get the master branch but how to get the latest released version.

**Comment by dmjio** [comment]
> Miso should follow PVP.

@Qqwy sorry if that sounded aggressive 😆

**Comment by dmjio** [comment]
This is done afaik.
