### ISSUE TITLE
The Miso Manifesto

### ISSUE THREAD

**Issue by srid** [dmjio/miso#254]
I’m interested to hear what Miso’s answers to Elm’s philosophy would be? For example, elm does not have type classes and for another example dictates a rather verbose coding style (elm-format). How does Miso position itself relative to that rather restrictive philosophy? See http://www.elmbark.com/2016/03/16/mainstream-elm-user-focused-design

I imagine Miso too is “User focused” but obviously it is on a different route (eg: saying yes to type classes) to that of Elm when it comes to specifics ...

It would be great to have a manifesto about this.

**Comment by cocreature** [comment]
For me personally, one of the big selling points of `miso` is that it’s not a whole new language that requires me to buy into some philosophy but it’s just a library and I can keep using whatever Haskell coding style I prefer.

**Comment by srid** [comment]
@cocreature That right there (what you said) could be The Miso Manifesto distinguishing it from that of Elm all the while retaining the core philosophy ("user focused" tasty haskell front-end framework). :-)

**Comment by srid** [comment]
> A long time ago Elm decided it’d be a language aimed at beginners and JavaScript programmers—not for ML or functional programming experts.  https://elixirforum.com/t/elm-hacker-news-article-elm-is-wrong/2317/7

Miso on the other hand is for Haskell and FP programmers. That's 180 degrees opposite.

**Comment by RobertFischer** [comment]
For the record, Evan intends to add typeclasses to Elm. Eventually. 
The Elm community seems to be defining itself in opposition to type classes, in classic I-don't-have-it-so-I-must-not-want-it developer style.

**Comment by dmjio** [comment]
https://github.com/dmjio/miso/issues/254#issuecomment-321987762
