### ISSUE TITLE
Flappy Birds 

### ISSUE THREAD

**Issue by dmjio** [dmjio/miso#265]
In the spirit of [2048](http://2048.haskell-miso.org) and [flatris](https://flatris.haskell-miso.org), it would be nice to have a flappy birds example. Code can be ported from here:

https://www.odedwelgreen.com/elm-plane/
https://github.com/odedw/elm-plane

cc @ptigwe ;)

**Comment by therewillbecode** [comment]
Is this still up for grabs?

**Comment by sectore** [comment]
@therewillbecode It's _wip_ -> https://github.com/sectore/miso/commits/flappy-bird :bird:

**Comment by therewillbecode** [comment]
@sectore Awesome ... looking forward to the result!

**Comment by dmjio** [comment]
@therewillbecode if interested, #340 is still available :)

**Comment by dmjio** [comment]
@sectore any updates on this ?

**Comment by sectore** [comment]
No updates. Anyone - who might be interested - is welcome to continue on this.

**Comment by therewillbecode** [comment]
@dmjio Thanks for the offer! Would love to but don't really have the bandwidth right now.

**Comment by Lermex** [comment]
@dmjio I can do this

**Comment by dmjio** [comment]
@Lermex nice ! I've assigned to you, and reached out on slack.

**Comment by Lermex** [comment]
Here it is! https://github.com/Lermex/miso-plane
Comments/reviews are very welcome.

**Comment by dmjio** [comment]
Fantastic ! @Lermex
