### ISSUE TITLE
Problem following nix guide; ghcjs version marked as broken

### ISSUE THREAD

**Issue by ahri** [dmjio/miso#268]
$ nix-build
    error: Package ‘ghcjs-0.2.0’ in ‘/nix/store/1d321579v509s5kw3jp2sg901cm1xyzh-nixpkgs-17.09pre102350.fa03b82/nixpkgs/pkgs/development/compilers/ghcjs/base.nix:102’ is marked as broken, refusing to evaluate.

    a) For `nixos-rebuild` you can set
      { nixpkgs.config.allowBroken = true; }
    in configuration.nix to override this.

After following that advice, I tried to build again but received this error instead:

    $ nix-builderror: Package ‘app-0.1.0.0’ in ‘/tmp/app/app.nix:3’ has an unfree license (‘unfree’), refusing to evaluate.

    a) For `nixos-rebuild` you can set
      { nixpkgs.config.allowUnfree = true; }
    in configuration.nix to override this.

    b) For `nix-env`, `nix-build`, `nix-shell` or any other Nix command you can add
      { allowUnfree = true; }
    to ~/.config/nixpkgs/config.nix.

        b) For `nix-env`, `nix-build`, `nix-shell` or any other Nix command you can add
          { allowBroken = true; }
        to ~/.config/nixpkgs/config.nix.

        (use ‘--show-trace’ to show detailed location information)

Only then did `nix-build` work. I guess this should be part of the guide if it's expected. On the other hand if it's been marked "broken" since you wrote the guide, perhaps a different version should be used?

**Comment by cocreature** [comment]
If I’m interpreting that error message correctly, the version of `nixpkgs` you’re using is a few months old https://github.com/NixOS/nixpkgs/commit/fa03b8279fa9b544c29c97eaa5263163b6716046. Sadly the newest unstable channel doesn’t have versions of `ghcjs` atm that work but it’s fixed in `master` for at least `ghcjsHEAD` and `ghcjs` is easy to fix.

**Comment by dmjio** [comment]
@ahri Ah, this is more nix specific information, so the line is blurring between what we should provide and what we expect the user to know. But I agree we need to provide a version of nixpkgs to the user that we curate, and that they can trust to reliably build. The first step towards that was forking our own nixpkgs, which we've done, next is to rebase our commits on a channel with a stable ghcjs, and then instruct users to build off that.

**Comment by dmjio** [comment]
Fixed now that nixpkgs is pinned.
