### ISSUE TITLE
Decoding multiple fields

### ISSUE THREAD

**Issue by ptigwe** [dmjio/miso#273]
Certain events, especially [Touch events](https://developer.mozilla.org/en-US/docs/Web/API/Touch_events) have a bit of a nested nature. At the moment, with the use of `decodeAt :: [JSString]` we are only capable of looking at a single one of such nested objects. One possibility involves changing the type of `decodeAt` to `[[JSString]]`.
Related to #121.

**Comment by ptigwe** [comment]
Resolved #275.

**Comment by dmjio** [comment]
Thanks again @ptigwe, great work
