### ISSUE TITLE
Support adding unescaped text into DOM

### ISSUE THREAD

**Issue by 3noch** [dmjio/miso#31]
`text_ "&copy;"` rightly gets escaped. But we need a back door for cases like this.

**Comment by dmjio** [comment]
I think for now it's best if we just document that unicode symbols should be used in text nodes only.

```haskell
view :: Int -> View Action                                                                                                                                        
view _ = div_ [] [ text "\x27f6" ] 
```
Result: ⟶

**Comment by dmjio** [comment]
closing for now

**Comment by mikelpr** [comment]
I got bit by this. my use case: a contenteditable div's content (html tags < > get converted to ````&lt;```` ````&gt;````)
