### ISSUE TITLE
nix-build fails for Miso

### ISSUE THREAD

**Issue by rihardsk** [dmjio/miso#310]
When I do `nix-build` with the latest master (2340394) the build fails with an error related to Qt:
```
[28 of 29] Compiling Miso             ( ghcjs-src/Miso.hs, dist/build/tests/tests-tmp/Miso.js_dyn_o )
[29 of 29] Compiling Main             ( tests/Main.hs, dist/build/tests/tests-tmp/Main.js_dyn_o )
Linking dist/build/tests/tests.jsexe (Main,Miso,Miso.Concurrent,Miso.Delegate,Miso.Diff,Miso.Effect,Miso.Effect.DOM,Miso.Effect.Storage,Miso.Effect.XHR,Miso.Event,Miso.Event.Decoder,Miso.Event.Types,Miso.FFI,Miso.Html,Miso.Html.Element,Miso.Html.Event,Miso.Html.Internal,Miso.Html.Property,Miso.Lens,Miso.Router,Miso.String,Miso.Subscription,Miso.Subscription.History,Miso.Subscription.Keyboard,Miso.Subscription.Mouse,Miso.Subscription.SSE,Miso.Subscription.WebSocket,Miso.Subscription.Window,Miso.Types)
running tests
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/nix-build-miso-0.9.0.0.drv-0/runtime-rihards'
qt.qpa.screen: QXcbConnection: Could not connect to display 
Could not connect to any X display.
builder for ‘/nix/store/49rqja787ncznxfd4j42ddlsna4vdz9a-miso-0.9.0.0.drv’ failed with exit code 1
cannot build derivation ‘/nix/store/w94qgvigd28lylgwrkd2x9pj12w31bsm-miso.drv’: 1 dependencies couldn't be built
error: build of ‘/nix/store/w94qgvigd28lylgwrkd2x9pj12w31bsm-miso.drv’ failed
```

The _"Could not connect to any X display"_ part might be related to the fact that I'm running a Wayland session. 

Though I am able to build the Miso 0.9.0.0 version from Hackage using the miso-ghcjs.nix found here on GitHub (with some modifications).

**Comment by dmjio** [comment]
@rihardsk Ah, it's attempting to run the tests. I'd try `nix-build --arg tests false`, this should disable the `checkPhase` that gets run. https://github.com/dmjio/miso/blob/master/default.nix#L10

Let me know, otherwise we can further edit `default.nix`

**Comment by dmjio** [comment]
or when you import, `miso = haskell.packages.ghcjs.callPackage ./default.nix { tests = false; }`

**Comment by rihardsk** [comment]
Disabling tests helped, thanks. It still failed at the end with a different error though:
```
installing
post-installation fixup
building path(s) ‘/nix/store/d0y1zvwygw6i366s41hfdf0pbw8bf5zc-s3.sh’
building path(s) ‘/nix/store/bhg9lqppkg2f2p796ybsf4v0ldsfjylq-miso’
cp: missing destination file operand after '/nix/store/bhg9lqppkg2f2p796ybsf4v0ldsfjylq-miso/doc/'
Try 'cp --help' for more information.
builder for ‘/nix/store/lxrwskps3agixa9afb0zhg05nffxg57f-miso.drv’ failed with exit code 1
error: build of ‘/nix/store/lxrwskps3agixa9afb0zhg05nffxg57f-miso.drv’ failed
```
I got around this by removing [these two lines related to docs](https://github.com/dmjio/miso/blob/2340394d90420b20a11bd87ce4db7b8537e9384d/default.nix#L69-L70) from `default.nix`.

Regarding the original issue - do the failing tests belong to Miso or are they from some dependency? It's weird that running them requires X.

**Comment by dmjio** [comment]
> Regarding the original issue - do the failing tests belong to Miso or are they from some dependency? It's weird that running them requires X.

Think it's related to the `phantomjs` derivation and its dependencies. 

I use a different version of `nixpkgs`, so my derivation might differ. I'd try pinning at this version.
```nix
let nixpkgs = import (pkgs.fetchFromGitHub {
      owner  = "NixOS";
      repo   = "nixpkgs";
      sha256 = "05k9vmy25d48af9qghz589qrph2cy5zqsb4i5nq0x2q4y4344yja";
      rev    = "ab4f4f8baa91e406d18263b7b97eae45e8738276";
 }) {};
```

**Comment by rihardsk** [comment]
No luck with pinning `nixpkgs`. I still get the same error. I also tried to run the build under an Xorg session but that didn't help either. The only solution is to disable the tests.

**Comment by dmjio** [comment]
@rihardsk should be fixed in HEAD now. Tests disabled by default, and derivation updated to support @cleverca22's fixed ouput derivation changes to haskellPackages.

**Comment by dmjio** [comment]
reopen if issues persist.
