### ISSUE TITLE
threejs example is broken out of the box on firefox and safari

### ISSUE THREAD

**Issue by narrative** [dmjio/miso#326]
Hi, I was just testing out the examples and noticed that the [threejs example](http://threejs.haskell-miso.org/) crashes with the following messages displayed in the console.

```
uncaught exception: Thread aborted, exit code: 0
uncaught exception in Haskell main thread: ReferenceError: Stats is not defined
all.js:8856:9
h$mainZCMainzimain30_e@http://threejs.haskell-miso.org/all.js:44188:7
h$runThreadSlice@http://threejs.haskell-miso.org/all.js:9868:11
h$runThreadSliceCatch@http://threejs.haskell-miso.org/all.js:9823:12
h$mainLoop@http://threejs.haskell-miso.org/all.js:9818:9
partiallyApplied/<@http://threejs.haskell-miso.org/all.js:3675:17
runIfPresent@http://threejs.haskell-miso.org/all.js:3693:21
onGlobalMessage@http://threejs.haskell-miso.org/all.js:3734:17
all.js:8856:9
The character encoding of the HTML document was not declared. The document will render with garbled text in some browser configurations if the document contains characters from outside the US-ASCII range. The character encoding of the page must be declared in the document or in the transfer protocol.
```

**Comment by dmjio** [comment]
@narrartive, yea I noticed this on safari but it *should* work on chrome. I haven't had much time to look closely. If you can identify the cross platform issue of why it's not working on Safari, that would be extremely helpful. Which browser are you using?

**Comment by narrative** [comment]
Ah yes, I can confirm that it works for me on Chrome. I was using Firefox 57.0.1 when this error occurred.

**Comment by narrative** [comment]
Strangely enough, I just noticed that it does work intermittently. If I refresh the page several times, it ends up working after a while. Unfortunately, I don't know enough about browsers to debug this further, though this does not seem to be an issue with Miso or the threejs example code itself.
