### ISSUE TITLE
Where do `startApp` and `App` come from?

### ISSUE THREAD

**Issue by ocramz** [dmjio/miso#329]
Neither is exported by the library, yet every program uses them. What sorcery is this?

**Comment by dmjio** [comment]
@ocramz hey :) witchcraft indeed ! So, when using `GHCJS`, both `startApp` and `App` should be available when from the `Miso` module (`import Miso`). The only reason they wouldn't is if you were using `GHC`. Are you using stack or nix? 

`startApp` is exported here
https://haddocks.haskell-miso.org/Miso.html

and `App` here:
https://haddocks.haskell-miso.org/Miso-Types.html#t:App

**Comment by ocramz** [comment]
I'm using `stack` compiling with GHCJS 8.0.2 , and I'd just like to do type inspection with `flycheck-mode` in Emacs. What's the recommended way of working interactively with miso? Thanks!

**Comment by dmjio** [comment]
For interactive use, I'd recommend `GHCJSi`, which only works with the `GHCJS 7.10.3` version currently. Trying to use `GHCJS 8.x` will say interactive mode is currently not supported. I believe @luite is working on this, along with `GHCJS 8.(2/4)` support.

**Comment by dmjio** [comment]
I'd say the original question has been answered. Reopen if necessary.

**Comment by ocramz** [comment]
Yes indeed, thanks @dmjio !
