### ISSUE TITLE
stack setup fails in miso/sample-app

### ISSUE THREAD

**Issue by pamu** [dmjio/miso#331]
```
exit status: 1                                
stderr: solver must be one of: modular        
CallStack (from HasCallStack):                
  error, called at libraries/Cabal/Cabal/Distribution/ReadE.hs:46:24 in Cabal-2.0.1.0:Distribution.ReadE
```

**Comment by pamu** [comment]
Even `stack build`, `stack clean` and `stack setup` give the same error. Worked after deleting `cabal-install` and running `stack build`.

**Comment by Tehnix** [comment]
Perhaps this should be added to the README? I just ran into this as well, having a global cabal-install/cabal lying around.

**Comment by dmjio** [comment]
https://github.com/dmjio/miso/commit/adea51505f30853caae76f38faa5e9f192ae8827

**Comment by Tehnix** [comment]
Quick and effective, thanks! I should probably have submitted a PR instead of just having mentioned it, but was planning on playing around with it a bit more first :)

**Comment by checkraiser** [comment]
@pamu How to delete `cabal-install` ? Which command do you use ?

**Comment by charlescrain** [comment]
Hey @pamu @dmjio,

I'm also running into this issue. I had previously installed `cabal-install` via homebrew.

 I've uninstalled it but now I don't have `cabal` as a command and get the error:

```Executable named cabal not found on path``` 

when I run `stack setup` or `stack build`. 

By remove `cabal-install` do you mean we shouldn't have a global `cabal` executable?

Hoping I'm just overlooking something but would appreciate some guidance.

Cheers,
Charles

**Comment by peterbecich** [comment]
@revskill10 Deleting `~/.local/bin/cabal`fixed it for me.

**Comment by tonicebrian** [comment]
I'm facing same problem as @charlescrain, if I have global cabal I get error:

```
exit status: 1
stderr: solver must be one of: modular
CallStack (from HasCallStack):
  error, called at libraries/Cabal/Cabal/Distribution/ReadE.hs:49:24 in Cabal-2.2.0.1:Distribution.ReadE
```

and if I `rm ~/.local/bin/cabal` the I get 

```
$ stack setup
Executable named cabal not found on path:  ....
```
any ideas?
