### ISSUE TITLE
Differences in server side rendered Miso, and client side rendered Miso

### ISSUE THREAD

**Issue by tolgap** [dmjio/miso#333]
Hi @dmjio, we've chatted extensively about this in Slack :)

But I've already applied your `to-html-fixes` branch to my current code, and there are still a few differences between serverside HTML, and clientside HTML. I'm changing the TodoMVC example to perform API calls, and render the Todo entries serverside.

When I call `viewEntries` serverside, they are rendered like this:

```html
<li class="">
    <div class="view">
        <input type="checkbox" class="toggle">
        <label>testing</label>
        <button class="destroy"></button>
    </div>
    <input value="testing" name="title" id="todo-0" class="edit">
</li>
```

and this is when rendering them clientside:

```html
<li class="">
    <div class="view">
        <input class="toggle" type="checkbox">
        <label>testing</label>
        <button class="destroy"></button>
    </div>
    <input class="edit" name="title" id="todo-0">
</li>
```

here's the diff:

```diff
<li class="">
    <div class="view">
-        <input type="checkbox" class="toggle">
+        <input class="toggle" type="checkbox">
        <label>testing</label>
        <button class="destroy"></button>
    </div>
-    <input value="testing" name="title" id="todo-0" class="edit">
+    <input class="edit" name="title" id="todo-0">
</li>
```

**Comment by tolgap** [comment]
Also, the `Key` instances seem to behave differently in GHC and GHCJS. I've done a bit of hacking and have the same HTML server side and client side, but I still have duplicate list items (entries) from rerendering on client side.

**Comment by dmjio** [comment]
Thanks for making this issue.

So, having attributes in different order (from DOM to virtual DOM) should be fine. But missing attributes like `value="testing"` is obviously problematic.

Can you confirm that the entries being sent to the client have the `value="testing"`.

**Comment by tolgap** [comment]
![screen shot 2018-01-05 at 11 07 33](https://user-images.githubusercontent.com/1763486/34604592-b6c3c00e-f208-11e7-956c-fbb4a7e9d845.png)

So I put a breakpoint there, and I see the prop "value" inside the diffing logic, but it does not seem to get applied into the DOM, as when I step through that breakpoint, `value` is not set tot `testd`, it remains empty.

**Comment by dmjio** [comment]
I'll take a look at your project this weekend.

**Comment by dmjio** [comment]
Should be fixed now, re-open if necessary.
