### ISSUE TITLE
Update nix instructions

### ISSUE THREAD

**Issue by dmjio** [dmjio/miso#334]
This should be the recommended way to use `miso` w/ `nix`. With a pinned, working version of nixpkgs.
```nix
{ pkgs ? import <nixpkgs> {} }:
let
  goodNixpkgs = import (pkgs.fetchFromGitHub {
    owner = "NixOS";
    repo = "nixpkgs";
    rev = "a0aeb23";
    sha256 = "04dgg0f2839c1kvlhc45hcksmjzr8a22q1bgfnrx71935ilxl33d";
  }){};
  miso = goodNixpkgs.haskell.packages.ghcjs.callCabal2nix "miso" (pkgs.fetchFromGitHub {
    owner = "dmjio";
    repo = "miso";
    sha256 = "f0e4c2f76c58916ec258f246851bea091d14d4247a2fc3e18694461b1816eb99";
    rev = "e2bd6765b520ffc03830053c52eb0ffca4edabcd";
  }){};
in
  goodNixpkgs.haskell.packages.ghcjs.callPackage ./miso-example-nix.nix { inherit miso; }
```

**Comment by dmjio** [comment]
done in HEAD

**Comment by mikelpr** [comment]
can you update them again? it's confusing, I'm trying to get a new version of miso (used the one on the README.md and it's like 0.14.0.0 or something like that) but I got stuck with the never-ending tasty-quickcheck bug. I tried adapting https://github.com/dmjio/miso/pull/462 and https://github.com/FPtje/miso-isomorphic-example/blob/93470ca431d759168facfac5234bbc5e4619e72c/default.nix to my default.nix to no avail

**Comment by dmjio** [comment]
@mikelpr I'm working on a nix overhaul of miso's nixpkgs infra as we speak, will include documentation as well.

**Comment by dmjio** [comment]
@mikeplr should be good now
