### ISSUE TITLE
Miso submission to HNPWA

### ISSUE THREAD

**Issue by dmjio** [dmjio/miso#340]
A HN clone would be a good show of how GHCJS apps can be PWAs.

https://hnpwa.com/

**Comment by wisn** [comment]
Assign me @dmjio. I'd like to help.

**Comment by wisn** [comment]
Lighthouse report: [72/100](https://www.webpagetest.org/result/180330_A6_02b43f3a0c94f5b66b4a2e8b624b450e/)

WebPagetest: [< 2s](https://www.webpagetest.org/result/180330_R6_703e3ed195f76b0a39c815f1d04640da/)

**Comment by dmjio** [comment]
@wisn Yes! Go for it. Will gladly merge. And anything you can do to improve https://haskell-miso.org on those lighthouse metrics would be extremely helpful. Awesome it's 100 for SEO.

**Comment by dmjio** [comment]
So @sectore is taking flappy-birds #265 , @wisn will take HNPWA.

**Comment by wisn** [comment]
I think we should improve those Lighthouse metrics first. Gonna learn Miso codebase and try to contribute

**Comment by dmjio** [comment]
@wisn awesome :) please join our slack as well! https://haskell-miso-slack.herokuapp.com/

**Comment by wisn** [comment]
@dmjio joined :)

**Comment by dmjio** [comment]
@wisn lighthouse metrics are looking good, any thoughts on moving this forward? https://files.slack.com/files-pri/T2GM0PT2P-FLFMP8Y7R/image.png
