### ISSUE TITLE
Failing stack install 

### ISSUE THREAD

**Issue by gurgl** [dmjio/miso#348]
When using the stack install instructions from README.md (today)

   git clone https://github.com/dmjio/miso && cd miso/sample-app && stack setup && stack build

i get : 

... lots of stuff above (no entry containing error though), only showing last part of log...

/home/karlw/.stack/snapshots/x86_64-linux/lts-6.20/7.10.3/bin/happy --version
/home/karlw/.stack/programs/x86_64-linux/ghc-7.10.3/bin/hpc version
looking for tool hsc2hs near compiler in      
/home/karlw/.stack/programs/x86_64-linux/ghcjs-0.2.0.9006020_ghc-7.10.3/src/.stack-work/install/x86_64-linux/lts-6.20/7.10.3/bin
found hsc2hs in                               
/home/karlw/.stack/programs/x86_64-linux/ghcjs-0.2.0.9006020_ghc-7.10.3/src/.stack-work/install/x86_64-linux/lts-6.20/7.10.3/bin/hsc2hs-ghcjs
/home/karlw/.stack/programs/x86_64-linux/ghcjs-0.2.0.9006020_ghc-7.10.3/src/.stack-work/install/x86_64-linux/lts-6.20/7.10.3/bin/hsc2hs-ghcjs --version
/home/karlw/.cabal/bin/HsColour -version      
/usr/bin/pkg-config --version                 
/bin/tar --help                               
Warning: No remote package servers have been specified. Usually you would have
one specified in the config file.             
/usr/bin/pkg-config --list-all                
/usr/bin/pkg-config --modversion zlib libusb-1.0 QtHelp gobject-introspection-no-export-1.0 gio-unix-2.0 xshmfence cairo-xcb QtOpenGL dbus-glib-1 gio-2.0 QtTest QtNetwork libpng12 cairo-gobject xinerama harfbuzz-icu ibus-table dbus-1 menu cairo-ps gmodule-2.0 randrproto QtDeclarative glib-2.0 xdmcp docky.items xkeyboard-config xau docky.widgets QtScriptTools gnome-icon-theme-symbolic docky.services pango nautilus-sendto libdrm gl libnotify dbus-python fontutil libbsd-ctor gdk-x11-3.0 libpcrecpp pangoft2 ice QtCore libpci xorg-wacom libffi gdk-pixbuf-2.0 gtksourceview-3.0 libdrm_nouveau gdk-pixbuf-xlib-2.0 wayland-server libproxy-1.0 libgdiplus luajit xrender 'gtk+-3.0' xext QtDesigner xcb QtSql pthread-stubs lua5.2 gobject-introspection-1.0 libbsd-overlay 'gtk+-unix-print-2.0' ginn python-2.7 javascriptcoregtk-3.0 QtUiTools xcb-randr compizconfig-python renderproto xcb-present gdk-2.0 webkitgtk-3.0 libcares libssl atk-bridge-2.0 glproto libsoup-2.4 xproto openssl xcursor xi xrandr xcb-sync cairo-pdf wayland-client ncurses python xcomposite libxml-2.0 expat xkbcomp xcb-shm x11-xcb gmodule-no-export-2.0 hexchat-plugin xcb-shape QtXml pangocairo fixesproto gmodule-export-2.0 damageproto iso-codes dri x11 xdamage cairo-xlib QtScript libcanberra tinfo QtDesignerComponents kbproto xcb-dri2 xcb-dri3 'gtk+-x11-2.0' cairo-xcb-shm compositeproto Qt3Support libquvi-scripts libdrm_amdgpu dri2proto pygtksourceview-2.0 QtDBus xxf86vm inputproto libbsd xextproto libdrm_radeon python-3.4 gobject-2.0 'gtk+-unix-print-3.0' mobile-broadband-provider-info libpng gthread-2.0 cairo-fc fontconfig pixman-1 'ncurses++' libcrypto python2 form gdk-3.0 notify-python libpcreposix wayland-cursor yelp-xsl python3 tic docky.cairohelper pangoxft cairo-xlib-xrender cairo-ft cairo cairo-png xft QtGui wayland-scanner 'gtk+-wayland-3.0' python-3.4m atk sm udisks gnome-icon-theme glu xf86vidmodeproto bash-completion cairo-svg xineramaproto QtWebKit shared-mime-info libdrm_intel QtXmlPatterns harfbuzz xcb-render usbutils xkbcommon gdk-x11-2.0 libpcre panel cairo-script xbitmaps pm-utils gdk-wayland-3.0 shared-desktop-ontologies cairo-tee freetype2 'gtk+-x11-3.0' xfixes m17n-db xcb-xfixes QtSvg libsexy QtCLucene 'gtk+-2.0' harfbuzz-gobject udev xcb-glx xtrans xorg-sgml-doctools
Resolving dependencies...                     
Warning: Topdown solver is deprecated         
In order, the following would be installed:   
ghc-prim-0.4.0.0 (new package)                
/home/karlw/.ghcjs/x86_64-linux-0.2.0.9006020-7.10.3/ghcjs/ghcjs-boot$ [cabal]: /home/karlw/.cabal/bin/cabal "--config-file" "/home/karlw/.ghcjs/x86_64-linux-0.2.0.9006020-7.10.3/ghcjs/cabalBootConfig" "--ignore-sandbox" "install" "./boot/ghc-prim" "--solver=topdown" "--global" "--ghcjs" "--one-shot" "--avoid-reinstalls" "--builddir" "dist" "--with-compiler" "/home/karlw/.stack/programs/x86_64-linux/ghcjs-0.2.0.9006020_ghc-7.10.3/src/.stack-work/install/x86_64-linux/lts-6.20/7.10.3/bin/ghcjs" "--with-hc-pkg" "/home/karlw/.stack/programs/x86_64-linux/ghcjs-0.2.0.9006020_ghc-7.10.3/src/.stack-work/install/x86_64-linux/lts-6.20/7.10.3/bin/ghcjs-pkg" "--prefix" "/home/karlw/.ghcjs/x86_64-linux-0.2.0.9006020-7.10.3/ghcjs" "--enable-documentation" "--haddock-html" "--haddock-hyperlink-source" "--enable-shared" "--enable-library-profiling" "--root-cmd" "/home/karlw/.ghcjs/x86_64-linux-0.2.0.9006020-7.10.3/ghcjs/run.sh"
/home/karlw/.cabal/bin/cabal --config-file /home/karlw/.ghcjs/x86_64-linux-0.2.0.9006020-7.10.3/ghcjs/cabalBootConfig --ignore-sandbox install ./boot/ghc-prim --solver=topdown --global --ghcjs --one-shot --avoid-reinstalls --builddir dist --with-compiler /home/karlw/.stack/programs/x86_64-linux/ghcjs-0.2.0.9006020_ghc-7.10.3/src/.stack-work/install/x86_64-linux/lts-6.20/7.10.3/bin/ghcjs --with-hc-pkg /home/karlw/.stack/programs/x86_64-linux/ghcjs-0.2.0.9006020_ghc-7.10.3/src/.stack-work/install/x86_64-linux/lts-6.20/7.10.3/bin/ghcjs-pkg --prefix /home/karlw/.ghcjs/x86_64-linux-0.2.0.9006020-7.10.3/ghcjs --enable-documentation --haddock-html --haddock-hyperlink-source --enable-shared --enable-library-profiling --root-cmd /home/karlw/.ghcjs/x86_64-linux-0.2.0.9006020-7.10.3/ghcjs/run.sh
Warning: No remote package servers have been specified. Usually you would have
Resolving dependencies...                     
one specified in the config file.             
cabal: Entering directory './boot/ghc-prim'   
Warning: Topdown solver is deprecated         
<command line>: cannot satisfy -package-id Cabal-1.24.1.0-LJFFR8WFcs7DZtL1vbJqmP: 
    Cabal-1.24.1.0-LJFFR8WFcs7DZtL1vbJqmP is unusable due to missing or recursive dependencies:
      binary-0.7.5.0-5784fd031a720c3b84e73006e444c7ca bytestring-0.10.6.0-c60f4c543b22c7f7293a06ae48820437 containers-0.5.6.2-e59c9b78d840fa743d4169d4bea15592 directory-1.2.2.0-f8e14a9d121b76a00a0f669ee724a732 process-1.2.3.0-78f206acb2330ea8066c6c19c87356f0 time-1.5.0.1-edbd1a50e7922b396ada189ab8e8523b unix-2.7.1.0-343d4f566f30113da92e819f4a148640
    (use -v for more information)             
cabal: Leaving directory './boot/ghc-prim'    
Failed to install ghc-prim-0.4.0.0            
cabal: Error: some packages failed to install:
ghc-prim-0.4.0.0 failed during the configure step. The exception was:
ExitFailure 1                                 
ghcjs-boot: error running: /home/karlw/.cabal/bin/cabal --config-file /home/karlw/.ghcjs/x86_64-linux-0.2.0.9006020-7.10.3/ghcjs/cabalBootConfig --ignore-sandbox install ./boot/ghc-prim --solver=topdown --global --ghcjs --one-shot --avoid-reinstalls --builddir dist --with-compiler /home/karlw/.stack/programs/x86_64-linux/ghcjs-0.2.0.9006020_ghc-7.10.3/src/.stack-work/install/x86_64-linux/lts-6.20/7.10.3/bin/ghcjs --with-hc-pkg /home/karlw/.stack/programs/x86_64-linux/ghcjs-0.2.0.9006020_ghc-7.10.3/src/.stack-work/install/x86_64-linux/lts-6.20/7.10.3/bin/ghcjs-pkg --prefix /home/karlw/.ghcjs/x86_64-linux-0.2.0.9006020-7.10.3/ghcjs --enable-documentation --haddock-html --haddock-hyperlink-source --enable-shared --enable-library-profiling --root-cmd /home/karlw/.ghcjs/x86_64-linux-0.2.0.9006020-7.10.3/ghcjs/run.sh
exit status: 1                                
stderr: Warning: No remote package servers have been specified. Usually you would have
one specified in the config file.             
Warning: Topdown solver is deprecated         
<command line>: cannot satisfy -package-id Cabal-1.24.1.0-LJFFR8WFcs7DZtL1vbJqmP: 
    Cabal-1.24.1.0-LJFFR8WFcs7DZtL1vbJqmP is unusable due to missing or recursive dependencies:
      binary-0.7.5.0-5784fd031a720c3b84e73006e444c7ca bytestring-0.10.6.0-c60f4c543b22c7f7293a06ae48820437 containers-0.5.6.2-e59c9b78d840fa743d4169d4bea15592 directory-1.2.2.0-f8e14a9d121b76a00a0f669ee724a732 process-1.2.3.0-78f206acb2330ea8066c6c19c87356f0 time-1.5.0.1-edbd1a50e7922b396ada189ab8e8523b unix-2.7.1.0-343d4f566f30113da92e819f4a148640
    (use -v for more information)             
cabal: Error: some packages failed to install:
ghc-prim-0.4.0.0 failed during the configure step. The exception was:
ExitFailure 1                                 
                                              
Booting GHCJS (this will take a long time) ...Process exited with ExitFailure 1: /home/karlw/.stack/programs/x86_64-linux/ghcjs-0.2.0.9006020_ghc-7.10.3/src/.stack-work/install/x86_64-linux/lts-6.20/7.10.3/bin/ghcjs-boot --clean
karlw@kalles:~/Documents/src/labs/misoplay/miso/sample-app$

**Comment by gurgl** [comment]
got the same error when removing ~/.stack

https://github.com/tolysz/ghcjs-stack mentions theres some exception to ghc-prim - so that might be it?

btw:

karlw@kalles:~/.ghcjs/x86_64-linux-0.2.0.9006020-7.10.3/ghcjs/ghcjs-boot$ cabal -V
cabal-install version 1.24.0.1
compiled using version 1.24.1.0 of the Cabal library 

...if thats an issue?

**Comment by gurgl** [comment]
in the end i could get the sample-app to work using an old ghcjs setup using the following changes to the stack.yaml: 

`resolver: lts-6.13
compiler: ghcjs-0.2.0.20160414_ghc-7.10.3
compiler-check: match-exact

packages:
 - '.'
extra-deps:
 - miso-0.12.0.0

setup-info:
  ghcjs:
    source:
      ghcjs-0.2.0.20160414_ghc-7.10.3:
        url: https://s3.amazonaws.com/ghcjs/ghcjs-0.2.0.20160414_ghc-7.10.3.tar.gz
        sha1: 6d6f307503be9e94e0c96ef1308c7cf224d06be3`

**Comment by dmjio** [comment]
Strange, closing for now, but will reopen if others report.
