### ISSUE TITLE
More documentation and examples for how to configure a miso project

### ISSUE THREAD

**Issue by tysonzero** [dmjio/miso#350]
In particular the setup in the README gives you base-4.8, and if you change from packages.ghcjs to package.ghcjsHEAD then building fails with an error about the miso dependency not being filled. It would be nice to see an example that works with base-4.9 or even 4.10. To make it more obvious what version of base you are getting, having it be specified in the cabal file would also be nice.

Secondly some more information about how to build projects with shared front and backend code would be nice. I'm not entirely sure how to imitate the haskell-miso.org setup for my own project, except perhaps by using git-submodules to pull miso into the local directory structure, since its current setup depends on it being within the miso repository. So adding a section on the README.md explaining exactly what to do for a full-stack project with shared code would be great.

One of the main things I look at examples for is how to set things up initially. One other suggestion I have is thus to have the examples be complete setups that are independently buildable, with their own cabal and nix configurations, and not dependent on being inside the miso repository. Perhaps a few front-end only examples and a few full-stack examples with shared code, maybe some with different compiler/base versions too.

I'm happy to try and help out with this, once I get a better understanding of nix and manage to successfully build miso (#349), but I think this is very important for usability. The main problems I have these days with Haskell web projects pretty much always comes down to initial setup and dependency management.

**Comment by dmjio** [comment]
> In particular the setup in the README gives you base-4.8, and if you change from packages.ghcjs to package.ghcjsHEAD then building fails with an error about the miso dependency not being filled

I can't reproduce this. When I build `default.nix` with `ghcjsHEAD` it works fine (tested on Darwin).

> Secondly some more information about how to build projects with shared front and backend code would be nice

Per @FPtje 
https://github.com/FPtje/miso-isomorphic-example

> since its current setup depends on it being within the miso repository

You can copy the sample-app, or haskell-miso.org out of those directories.

> One other suggestion I have is thus to have the examples be complete setups that are independently buildable, with their own cabal and nix configurations, and not dependent on being inside the miso repository

Yea, others have mentioned this as well. https://github.com/dmjio/miso/pull/339

> The main problems I have these days with Haskell web projects pretty much always comes down to initial setup and dependency management.

You're right, there is a dearth of documentation for this project. I do plan on fixing this, in the meantime, the links I've provided, the README, and examples are good starting points.

**Comment by tysonzero** [comment]
Thank you!

> I can't reproduce this. When I build default.nix with ghcjsHEAD it works fine (tested on Darwin).

Hmm... that's weird. I'm currently upgrading my OS to high sierra. I'll give more detailed error information if I still have the issue after upgrading.

> Per @FPtje https://github.com/FPtje/miso-isomorphic-example

Thanks! Is that in the README at all? Because it seems worthwhile to have it in there.

> You can copy the sample-app, or haskell-miso.org out of those directories.

But how? `miso-ghc = ghc802.callPackage ./../../miso-ghc.nix { };` seems like something that is only going to work in the current location within `miso`.

**Comment by dmjio** [comment]
> Thanks! Is that in the README at all? Because it seems worthwhile to have it in there.

Agreed, will add.

> But how? miso-ghc = ghc802.callPackage ./../../miso-ghc.nix { }; seems like something that is only going to work in the current location within miso.

Yes, instead of fetching from a relative path (two parent directories above), fetch the source directly from GitHub. Replace `default.nix` in `examples/haskell-miso.org` w/ the below script.

```nix
{ pkgs ? import <nixpkgs> {} }:                                                                                                                                        
let                                                                                                                                                                    
  inherit (pkgs) runCommand closurecompiler;                                                                                                                           
  inherit (pkgs.haskell.packages) ghcjsHEAD ghc802;                                                                                                                    
  miso-src = pkgs.fetchFromGitHub {                                                                                                                                    
    owner = "dmjio";                                                                                                                                                   
    repo = "miso";                                                                                                                                                     
    sha256 = "0xcbyphv2wxj6r8n66003w13x3kfw0sk3qdrf331mrz768p564v5";                                                                                                   
    rev = "8d115ab0c04c3f5a41497a6a460b8cc1656a975d";                                                                                                                  
  };                                                                                                                                                                   
  miso-ghc = ghc802.callCabal2nix "miso" miso-src {};                                                                                                                  
  miso-ghcjs = ghcjsHEAD.callCabal2nix "miso" miso-src {};                                                                                                             
  client = ghcjsHEAD.callPackage ./client { miso = miso-ghcjs; };                                                                                                      
  server = ghc802.callPackage ./server { miso = miso-ghc; };                                                                                                           
in                                                                                                                                                                     
  runCommand "haskell-miso.org" { inherit client server; } ''                                                                                                          
    mkdir -p $out/{bin,static}                                                                                                                                         
    ${closurecompiler}/bin/closure-compiler ${client}/bin/client.jsexe/all.js > $out/static/all.js                                                                     
    cp ${server}/bin/* $out/bin                                                                                                                                        
  ''      
```

**Comment by dmjio** [comment]
> The main problems I have these days with Haskell web projects pretty much always comes down to initial setup and dependency management.

Same, and a pinned version of `nixpkgs` goes a long way to solving this.

**Comment by dmjio** [comment]
cc @tysonzero https://github.com/dmjio/miso#isomorphic

**Comment by tysonzero** [comment]
Thanks for all the information! The one remaining issue I am having is that miso-isomorphic-example fails to build, I pinned nixpkgs to the same version as the one you gave me in #349.

I am happy to create an issue on the miso-isomorphic-example repo, but I figured I'd talk to you first.

```
Building miso-0.7.3.0...
Preprocessing library miso-0.7.3.0...
[2 of 2] Compiling Data.Distributive.Generic ( src/Data/Distributive/Generic.hs, dist/build/Data/Distributive/Generic.js_o )
haddockPhase
[ 1 of 33] Compiling Miso.String      ( ghcjs-src/Miso/String.hs, dist/build/Miso/String.js_o )
haddockPhase
[ 2 of 33] Compiling Miso.Lens        ( src/Miso/Lens.hs, dist/build/Miso/Lens.js_o )
[ 3 of 33] Compiling Miso.FFI         ( ghcjs-src/Miso/FFI.hs, dist/build/Miso/FFI.js_o )
Running Haddock for parallel-3.2.1.0...
Warning: The program 'hscolour' version >=1.8 is required but the version of
/nix/store/jaa7d6nbgwhh6987yfvclg9wpw0xaxmw-hscolour-1.24.2/bin/HsColour could
not be determined.
Running Haddock for distributive-0.5.3...
Warning: The program 'hscolour' version >=1.8 is required but the version of
/nix/store/jaa7d6nbgwhh6987yfvclg9wpw0xaxmw-hscolour-[ 4 of 33] Compiling Miso.Event.Types ( src/Miso/Event/Types.hs, dist/build/Miso/Event/Types.js_o )
1.24.2/bin/HsColour could
not be determined.

src/Miso/Event/Types.hs:39:19: error:
    Ambiguous occurrence ‘Options’
    It could refer to either ‘Data.Aeson.Options’,
                             imported from ‘Data.Aeson’ at src/Miso/Event/Types.hs:18:1-27
                             (and originally defined in ‘aeson-1.2.2.0:Data.Aeson.Types.Internal’)
                          or ‘Miso.Event.Types.Options’,
                             defined at src/Miso/Event/Types.hs:31:1
builder for ‘/nix/store/627yi6jbqb3vcg5n1wkg76b77kgnq73a-miso-0.7.3.0.drv’ failed with exit code 1
cannot build derivation ‘/nix/store/hrfl2ch707digcm7jza4mkr8bq9lladj-miso-isomorphic-example-0.1.0.0.drv’: 1 dependencies couldn't be built
cannot build derivation ‘/nix/store/azy8f4dw6lf6qm70p8iia1bd7zanvgkz-miso-ismorphic-example.drv’: 1 dependencies couldn't be built
error: build of ‘/nix/store/azy8f4dw6lf6qm70p8iia1bd7zanvgkz-miso-ismorphic-example.drv’ failed
```

**Comment by dmjio** [comment]
yea, either make an issue on that repo, or use a pinned version of nixpkgs here as well.

**Comment by tysonzero** [comment]
Pinning miso to a newer version seemed to fix things! One other thing that would be nice is an example where overriding a haskell package is necessary, such as to get a different version or to jailbreak it, as I'm currently having some issues doing that (specifically I'm not sure how to get miso working with datetime).

**Comment by dmjio** [comment]
@tysonzero this is a good section on that: https://github.com/Gabriel439/haskell-nix/blob/master/project3/README.md#tweaking-haskell-projects

**Comment by dmjio** [comment]
@tysonzero join our slack or IRC channel if you have more questions about nix.
