### ISSUE TITLE
Is there any way to avoid having to do routing twice?

### ISSUE THREAD

**Issue by tysonzero** [dmjio/miso#353]
Currently it seems like you need to do routing in two separate places. Once in `shared` for the client side routing that allows you to navigate without refreshing the page, and again in `server` so that the server knows what initial model state to give you.

It seems to me as though this shouldn't be necessary. Once you have the routing written out in `shared`, then it seems as though the server should just be able to forward on the URI it has been given directly into the model (perhaps via the `HasURI` instance), and let the `shared` routing handle which view the server should pre-render.

It would be nice to be able to write out half as much routing code, and it would also be nice to eliminate the risk of having the shared and server side routing desync and lead to bad behavior (only some types of desyncing would be caught by the type system).

**Comment by tysonzero** [comment]
https://github.com/FPtje/miso-isomorphic-example/issues/3#issuecomment-364989003

A function like the one I mentioned `serveFromURIFunction :: <Routes that all serve <a>> -> (URI -> a -> Server <Routes>` would be really nice. It would allow the server in isomorphic apps to not have to change even as new URL's are added, and it would get rid of some fairly substantial code duplication that is currently fairly necessary.

**Comment by dmjio** [comment]
@tysonzero can this be closed now?

**Comment by tysonzero** [comment]
Yep!
