### ISSUE TITLE
Make childless html tags not take in a `[View action]` argument

### ISSUE THREAD

**Issue by tysonzero** [dmjio/miso#358]
Currently `input_` has type `[Attribute action] -> [View action] -> View action`, but anything you put inside `[View action]` seems to just spill out to the side of the `<input>` tag. It seems like a simple solution to this is for `input_` (and all other childless elements) to have type `[Attribute action] -> View action`.

**Comment by dmjio** [comment]
That is a good observation. Adding children to `<input>` isn't valid HTML, even though the DOM allows it. I think a PR along these lines (that restricts specifying children on `<input>`) would be beneficial.

**Comment by dmjio** [comment]
@tysonzero care to make a PR? Otherwise, I can make one soon.

**Comment by tysonzero** [comment]
@dmjio As long as there is no rush, I am happy to make a PR at some point.

**Comment by dmjio** [comment]
We did it 🎉 @tysonzero
