### ISSUE TITLE
Miso routing fails to work with url fragments.

### ISSUE THREAD

**Issue by pamu** [dmjio/miso#359]
### Thanks for the Cool frontend framework! Miso is new hope in Haskell frontend world.

In the example https://github.com/dmjio/miso/blob/master/examples/router/Main.hs

```haskell
-- | Type-level routes
type API   = About :<|> Home
type Home  = View Action
type About = "#about" :> View Action  -- introduced # in front of about
```

I want router to work with fragments also because, this way I can use urls without invoking the backend actions in case of same domain name for frontend and backend.

Using `#` client-side routing is much more effective and flexible. As server ignores fragments. When client-side url (url with `#`) is changed browser does not request the server.

For example:
Let's say current URL is `http://foobar.com/#locations/all` now let's change the URL to `http://foobar.com/#locations/1234` by hand. Now Browser page is not refreshed. The client app can read the fragment information to load necessary data without page reloading.

**Comment by pamu** [comment]
Found the solution:  https://github.com/dmjio/miso/pull/360

**Comment by dmjio** [comment]
cc @Archaeron is running into a similar issue, this patch seems like the fix. Great work @pamu !

**Comment by pamu** [comment]
@dmjio Shall I go ahead and update the examples/demos apps as well.

**Comment by pamu** [comment]
@dmjio I am currently using Miso with this fix for my frontend app. Waiting for the fix to be merged.

**Comment by dmjio** [comment]
https://github.com/dmjio/miso/pull/360#issuecomment-377201301

**Comment by pamu** [comment]
@archaeron are you still interested in this ?

**Comment by archaeron** [comment]
I still believe this is useful, but I don't use miso right now

**Comment by dmjio** [comment]
Re-open if necessary please.

**Comment by pamu** [comment]
Properly fixing this would require changes in servant repo
