### ISSUE TITLE
Consider getting rid of `HasUri` constraint on `miso`

### ISSUE THREAD

**Issue by tysonzero** [dmjio/miso#376]
In order for `model` to have a `HasUri` instance it must contain a `URI`, so in order to create that model to pass into `miso` in the first place you must give it some sort of `URI`, which is just going to get immediately overridden.

It seems like it would make more sense for the `model` argument to `App` to have type `URI -> model`, instead of `model`, then we can drop the `HasURI` constraint. We could also give it type `model` with no constraint and just let users decide if they want to call `getCurrentURI` or not.

Funnily enough with the current setup I have actually been indirectly calling `getCurrentURI` twice, once to build the `model`, and once in `miso`, which I only just noticed after doing some source diving to figure out the purpose of `HasURI`.

**Comment by tysonzero** [comment]
After further thought I would suggest simply giving it type `model` and allowing users to call `getCurrentURI`, as that would also allow you to do other things based on the URI such as change the other parameters to miso or get some of the model state from `IO`.

**Comment by dmjio** [comment]
`HasURI` might be too heavyweight, I'd tend to agree. Also introduces lens where it might not be that necessary. It might be safe to assume that all applications will hold the `URI` somewhere on the top level of the model.

**Comment by tysonzero** [comment]
I was also considering not even storing the URI in the state for my app, as all I really need is a function from `URI -> State` that gets dispatched whenever a link is pressed or the page is loaded. I don't really need to be able to convert from `State` back to a `URI`, since the `URI` is already going to be in the URL bar from the last time I clicked a link or loaded the page.

I just have to make sure that large state changes are done via setting the `URI`, and not via directly manipulating the state to one that doesn't fit well with the `URI`, which is something you have to worry about even if you do store the `URI` directly.

Would you like me to make a PR?

**Comment by dmjio** [comment]
> In order for model to have a HasUri instance it must contain a URI, so in order to create that model to pass into miso in the first place you must give it some sort of URI, which is just going to get immediately overridden.

With the `miso` function yes, this assumes you'd like to share routes with the server, so we grab the `currentURI` for the user and route the correct place. Overriding isn't a problem here IMO. If using `startApp` no overriding occurs, but it also assumes you're not sharing with the server.

> It seems like it would make more sense for the model argument to App to have type URI -> model, instead of model, then we can drop the HasURI constraint. We could also give it type model with no constraint and just let users decide if they want to call getCurrentURI or not.

Not all applications will use routing, so unsure if it makes sense to impose it upon users.

> Funnily enough with the current setup I have actually been indirectly calling getCurrentURI twice, once to build the model, and once in miso, which I only just noticed after doing some source diving to figure out the purpose of HasURI.

Yea apologies for that, it can be rather non-intuitive, and the documentation isn't the best, but the source for haskell-miso.org is a good example of how to use it effectively. 

But yes, `HasURI` is used to help the user when routing in an isomorphic context.

**Comment by dmjio** [comment]
https://github.com/dmjio/miso/commit/f2dc6f49a4855c424c6d57068bd4b4be6d1558d5
