### ISSUE TITLE
Improve the Miso Official Website Lighthouse Metrics

### ISSUE THREAD

**Issue by wisn** [dmjio/miso#393]
The current [Lighthouse Report](https://www.webpagetest.org/result/180330_A6_02b43f3a0c94f5b66b4a2e8b624b450e/#accessibility) in Miso official website is quite bad. The accessibility is 36 out of 100. How to fix: Follow the report's audit.

**Comment by dmjio** [comment]
Improve PWA, Performance, Best Practices and Accessibility.

- [ ] Create a manifest
- [ ] Add `alt` to `img`
- [ ] Add `lang` attribute to `html`
... etc. (more todo's depicted below)

<img width="819" alt="screen shot 2018-03-30 at 12 09 12 am" src="https://user-images.githubusercontent.com/875324/38128314-ee092c10-33ae-11e8-9381-331889e672ef.png">

<img width="789" alt="screen shot 2018-03-30 at 12 09 44 am" src="https://user-images.githubusercontent.com/875324/38128321-f2f50230-33ae-11e8-9b77-fc237198eb2d.png">


<img width="781" alt="screen shot 2018-03-30 at 12 09 38 am" src="https://user-images.githubusercontent.com/875324/38128327-f7cc69ec-33ae-11e8-91d7-e271287c893a.png">

<img width="783" alt="screen shot 2018-03-30 at 12 09 32 am" src="https://user-images.githubusercontent.com/875324/38128330-fc435fc6-33ae-11e8-9783-d8cc0496ae46.png">

**Comment by wisn** [comment]
On my way~

**Comment by dmjio** [comment]
@wisn I went ahead an added a few things... but we still need to fix CSS blocking (concatenation would help) and service workers + icons (and reference them in the manifest) in the PWA.

<img width="806" alt="screen shot 2018-03-31 at 1 09 01 am" src="https://user-images.githubusercontent.com/875324/38161262-a7ca64c6-3480-11e8-9686-17db24850d2c.png">

**Comment by wisn** [comment]
I got a different result [here](https://www.webpagetest.org/result/180331_AQ_ddaf13edfb71595287348b0efd6bb3ce/).

**Comment by dmjio** [comment]
It takes you 3 times as long to download from the CDN for some reason.

**Comment by wisn** [comment]
I don't know whether [this](https://developers.google.com/web/fundamentals/performance/critical-rendering-path/render-blocking-css) could help or not.

**Comment by dmjio** [comment]
Concatenating the CSS into one file would help, embedding the CSS in the HTML might be even faster.

**Comment by dmjio** [comment]
@wisn let's say this is good enough for now, I say let's move to #340 ?
