### ISSUE TITLE
Miso `sample-app` is Outdated

### ISSUE THREAD

**Issue by wisn** [dmjio/miso#394]
The current stable release is `0.17.0.0`. However, the `sample-app` using `0.14.0.0`.

**Comment by sectore** [comment]
Just a side note:[`sample-app/default.nix`](https://github.com/dmjio/miso/blob/master/sample-app/default.nix) is already pointed to latest `v.0.17.0.` https://github.com/dmjio/miso/commit/99b5145426bf0b2cc3df5f1a014b3a86fc4ebeed . 

However, you are right that [`sample-app/stack.yaml`](https://github.com/dmjio/miso/blob/master/sample-app/stack.yaml#L8) has to be updated as well. @wisn Could you update `stack.yaml` and run it? _Because I haven't `ghcjs` installed by `Stack`, just by `Nix`..._

**Comment by sectore** [comment]
> Just a side note:sample-app/default.nix is already pointed to latest v.0.17.0. 99b5145 .

Oops, I'm wrong with that ^ _I will update it in a sec. ..._

**Comment by wisn** [comment]
I have some problem with GHCJS by Stack. Trying to fixing it. I'm trying to use the latest GHC (LTS-11.2) but no luck. Gonna try till fixed!

**Comment by sectore** [comment]
@wisn I guess you can't use `lts-11.2`, check https://docs.haskellstack.org/en/stable/ghcjs/

**Comment by wisn** [comment]
@sectore need to build it from source
