### ISSUE TITLE
action/actbon/actuon/actqon

### ISSUE THREAD

**Issue by JamieBallingall** [dmjio/miso#397]
To the untrained eye, the use of action/actbon/actuon/actqon in the below looks like a find/replace error. If it is intentional, maybe a quick comment to explain what is going on is called for.

https://github.com/dmjio/miso/blob/5fcb57ad9fd423bd2d1b38f9e1a7121a0acf3e17/src/Miso/Html/Element.hs#L476-L486

**Comment by dmjio** [comment]
Never in a million years would I have caught this.

**Comment by dmjio** [comment]
https://github.com/dmjio/miso/pull/398

**Comment by dmjio** [comment]
🍺

**Comment by JamieBallingall** [comment]
Thanks! Hopefully in the future I can contribute a little more than just an untrained eye.
