### ISSUE TITLE
Add ability to batch multiple action into an Effect

### ISSUE THREAD

**Issue by tolgap** [dmjio/miso#401]
Right now we have functions to create Effects with one action: `<#`, `#>`, `effectSub`.

When working with list related applications, you sometimes need a single `Effect` to change multiple items in a `List` (something like "check all" or "delete all"). You most likely already have an `action` handling the same logic for a single `List` record, so you'd like to reuse this.

Elm has `Cmd.batch`, so I was looking for something like this for Miso. I know you can use the `Effect` datatype directly. But seeing as that recently changed to also include Sinks, I think it would be nice to have an API stable function for batching multiple Actions.

**Comment by tysonzero** [comment]
For that you can simply use the `Effect` constructor directly.

**Comment by tolgap** [comment]
@tysonzero That's my point though:

*I know you can use the Effect datatype directly. But seeing as that recently changed to also include Sinks, I think it would be nice to have an **API stable** function for batching multiple Actions.*

It's a way to reduce breaking changes by hiding the implementation detail of the constructor with an exposed function.

**Comment by tolgap** [comment]
@tysonzero This is what I have in my own project now:

```haskell
batchEff :: model -> [IO action] -> Effect action model
batchEff m actions = Effect m (map (\a -> \sink -> a >>= sink) actions)
```

I don't really have a use-case for the other types.

**Comment by tysonzero** [comment]
If you wanted to add it to [ghcjs-src/Miso/Effect.hs](https://github.com/dmjio/miso/blob/master/ghcjs-src/Miso/Effect.hs), I don't think it would be much trouble to accept such a PR.

@dmjio Thoughts?

**Comment by dmjio** [comment]
@tolgap @tysonzero yes sounds great! Will accept PR for `batchEff` add documentation too if possible. Thanks!

**Comment by dmjio** [comment]
```haskell
batchEff :: model -> [IO action] -> Effect action model
batchEff m actions = Effect m $ (>>=) <$> actions
```
