### ISSUE TITLE
Implement Websocket Type as Instance of Show Typeclass 

### ISSUE THREAD

**Issue by therewillbecode** [dmjio/miso#402]
While playing with the Websocket example in the repo I noticed that it is a bit laborious to derive  the Action type as an instance of the Show typeclass.
data Action

 ```
Data Action = HandleWebSocket (WebSocket Message)
  | SendMessage Message
  | UpdateMessage MisoString
  | Id

```
When trying to automatically derive the Show typeclass for the Action type in the example I get the following error from GHC.

```
data Action
  = HandleWebSocket (WebSocket Message)
  | SendMessage Message
  | UpdateMessage MisoString
  | Id deriving (Show)
```

```

No instance for (Show (WebSocket Message))
      arising from the first field of ‘HandleWebSocket’
        (type ‘WebSocket Message’)
    Possible fix:
      use a standalone 'deriving instance' declaration,
        so you can specify the instance context yourself
    When deriving the instance for (Show Action)
```

I propose that we include an instance of Show for Websocket within the library.

I am happy to work on a PR for this issue if needed.

**Comment by dmjio** [comment]
Sure, please add. Think I just forgot the `deriving (Show, Eq)`

```haskell
data WebSocket action                                                                                          
  = WebSocketMessage action                                                                                    
  | WebSocketClose                                                                                             
  | WebSocketOpen                                                                                              
  | WebSocketError                                                                                             
+++  deriving (Show, Eq)
```

**Comment by therewillbecode** [comment]
@dmjio Would it be a good idea to implement the instance of Monoid for MisoString?

**Comment by dmjio** [comment]
@therewillbecode think we get that for free since `MisoString` is a type alias for `JSString`. Great work on this PR https://github.com/dmjio/miso/commit/8906ed31d31cc62a73ae95103734ebb1ab8be6e9
