### ISSUE TITLE
Default Instances of ToJSON and FromJSON for Websocket Action type?

### ISSUE THREAD

**Issue by therewillbecode** [dmjio/miso#411]
It would seem useful to be able to encode and decode JSON for all the actions in an app for the purposes of sharing actions between the front and back end in a full stack Haskell setup.

However an inconvenience is presented to the user if they try and derive their ToJSON and FromJSON classes automatically for their action types  when using Aeson and there is no implementation of the classes for the imported Websocket type from the library. 

Do we want users to manually implement them or should we export the type with default instances for these classes?

[Websocket Type Declaration here](https://github.com/dmjio/miso/blob/ffc7558907c7a14de97986c45c738a8940a1cd42/ghcjs-src/Miso/Subscription/WebSocket.hs)

**Comment by dmjio** [comment]
Closing since only serialization on `Message` needs to be provided, not entire `action`.
