### ISSUE TITLE
create-miso-app

### ISSUE THREAD

**Issue by renanpvaz** [dmjio/miso#419]
I think having something, if possible, like [create-elm-app](https://github.com/halfzebra/create-elm-app) and [create-react-app](https://github.com/facebook/create-react-app) would be nice.

**Comment by RobertFischer** [comment]
This is what Stack templates would be useful for.

**Comment by jbrgfx** [comment]
Does the Pi template model have any advantages?
https://github.com/vmchale/pi-templates

**Comment by dmjio** [comment]
stack templates would be great.
