### ISSUE TITLE
Warning in console on Firefox

### ISSUE THREAD

**Issue by JamieBallingall** [dmjio/miso#421]
When loaded in Firefox, the Simple app (and other examples) cause the warning:

> The character encoding of the HTML document was not declared. The document will render with garbled text in some browser configurations if the document contains characters from outside the US-ASCII range. The character encoding of the page must be declared in the document or in the transfer protocol.

to be printed to the console.

Hardly a show stopper but it would be nice if the character encoding were declared to keep Firefox happy.

**Comment by dmjio** [comment]
This is an issue with GHCJS itself, and the HTML it generates.

**Comment by JamieBallingall** [comment]
Ah. Ok. I'll see if I can get GHCJS to insert that. Will report back. In the meantime, closing this.
