### ISSUE TITLE
Sample application = Simple example?

### ISSUE THREAD

**Issue by JamieBallingall** [dmjio/miso#422]
The Sample application in [README.md](https://github.com/dmjio/miso/blob/master/README.md) is very similar (and functionally identical?) to the [Simple example](https://github.com/dmjio/miso/blob/master/exe/Main.hs). But a diff shows many differences in the code.

I'd like to create a pull request to conform them. Any opinions on which one is better?

**Comment by dmjio** [comment]
Sure, I would copy the example out of `README.md` into the sample app.
