### ISSUE TITLE
Register miso at todomvc.com

### ISSUE THREAD

**Issue by roman-mkh** [dmjio/miso#425]
Miso TodoMVC example has a link that claims it is a part of "**todomvc.com**", but it is not. It would be nice to register miso framework at "**todomvc.com**"

**Comment by dmjio** [comment]
@roman-mkh great idea! Would you mind making a PR on todo mvc on miso's behalf? Otherwise, I'll try to get around to it soon.

**Comment by roman-mkh** [comment]
@dmjio: I read their contribution guidelines. Unfortunately it requires more work to compliance with guidelines, than I have free time now. :disappointed:

**Comment by dmjio** [comment]
@roman-mkh, ok, well, just let me know when you're free I guess.

**Comment by dmjio** [comment]
https://github.com/tastejs/todomvc/issues/1987
