### ISSUE TITLE
Stray start tag in examples/haskell-miso.org

### ISSUE THREAD

**Issue by jbrgfx** [dmjio/miso#429]
**Describe the bug**
The example/haskell-miso.org/server.hs produces an HTML validation error.
```
instance L.ToHtml a => L.ToHtml (Wrapper a) where
  toHtmlRaw = L.toHtml
  toHtml (Wrapper x) =
    L.doctypehtml_ $ do
      L.html_ [ L.lang_ "en" ] $ do
        L.head_ $ do
```
Causes an Error: 
Start tag in generated HTML5 missing lang attribute, then it is added but wrapped in a duplicate html tag.

Extra html tag opened and closed after ending head and before body
```
<!DOCTYPE HTML><html><html lang="en"><head><title>  </head></html><body>
```

Your "wrapper implementation" fails to implement lucid output as prescribed in the lucid documentation.

**To Reproduce**
1.  https://validator.w3.org/#validate_by_uri
2.  haskell-miso.org

Alternative method to reproduce:
1. Run example
2. View source
3. Inspect DOCTYPE
4. submit generated HTML to https://validator.w3.org/ 

**Expected behavior**
Output should be:
```
<!DOCTYPE HTML><html lang="en"><head><title> </title><meta charset="utf-8"><script defer async src="/static/all.js"></script></head><body>
```

**Additional context**
Using lucid directly produces the proper output.
```   
page :: Html () 
   page =
      html_ [lang_ "en"]
         (do head_  
             body_
```
 produces:
```
   <html lang="en"><head>  </head><body>
```

**Comment by dmjio** [comment]
Nice catch 🍺 https://github.com/dmjio/miso/commit/93783297bd79685b7a471bc565bcdc801c270b02
