### ISSUE TITLE
can't build sample app with stack

### ISSUE THREAD

**Issue by lippirk** [dmjio/miso#433]
**Describe the bug**
when trying to build the 'quick start example', stack moans about lack of cabal

**To Reproduce**

step one - remove stack / cabal
$ cd ~ && mv .stack .stack.backup
$ which cabal // cabal not found
$ sudo pacman -Rsn stack // remove stack

at this point i have removed stack and made sure cabal is not on my PATH

step two - reinstall stack & do the 'quick start' command
$ sudo pacman -S stack
$ cd ~/github
$ git clone https://github.com/dmjio/miso && cd miso/sample-app && stack setup && stack build

**actual behaviour**

stuff^^

Copied executables to /home/mycomp/.stack/programs/x86_64-linux/ghcjs-0.2.0.9006020_ghc-7.10.3/bin:
- ghcjs
- ghcjs-boot
- ghcjs-pkg
- ghcjs-run
- haddock-ghcjs
- hsc2hs-ghcjs

Warning: Installation path /home/mycomp/.stack/programs/x86_64-linux/ghcjs-0.2.0.9006020_ghc-7.10.3/bin
         not found on the PATH environment variable.
Installed GHCJS.
Executable named cabal not found on path: ["/home/mycomp/.stack/programs/x86_64-linux/ghcjs-0.2.0.9006020_ghc-7.10.3/src/.stack-work/install/x86_64-linux-tinfo6/lts-6.20/7.10.3/bin","/home/mycomp/.stack/snapshots/x86_64-linux-tinfo6/lts-6.20/7.10.3/bin","/home/mycomp/.stack/compiler-tools/x86_64-linux-tinfo6/ghc-7.10.3/bin","/home/mycomp/.stack/programs/x86_64-linux/ghc-tinfo6-7.10.3/bin","/usr/local/bin","/usr/bin","/bin","/usr/local/sbin","/home/mycomp/.local/bin/","/usr/lib/jvm/default/bin","/usr/bin/site_perl","/usr/bin/vendor_perl","/usr/bin/core_perl"]

**Expected behavior**
build with no errors

**Desktop (please complete the following information):**
 - OS: manjaro + xfce-4.12

**Additional context**
- It looks like `stack setup` doesn't install cabal...? 
- i have not installed GHCJS (i am under the impression stack will do this for me ?)
- i have checked and cabal is indeed not in any of those directories
- if this is a stack issue i'm sorry, i am a haskell noob
- i don't understand the warning about /home/mycomp/.stack..... etc not being on the PATH variable -i don't want it on my PATH variable

many thanks for the help!

**Comment by madnight** [comment]
I guess you should try it with nix-build. The stack support for ghcjs is not very good lately.

> The GHCJS codepaths are not currently being actively maintained in Stack

> Most of the GHCJS community recommends Nix for setting up the toolchain

> None of the regular Stack contributors are using the GHCJS support

https://github.com/commercialhaskell/stack/issues/4086

**Comment by matchwood** [comment]
Have you tried installing cabal globally and then running the command? The ghcjs boot process will look for cabal in your path. Ideally stack would install cabal first, and then provide a modified path for ghcjs, but I don't think it does this at the moment.

**Comment by Lermex** [comment]
Installing cabal globally doesn't help because GHCJS expects an older version of cabal (1.2) and doesn't build successfully on 2.0+.

What helped me as a workaround was to temporarily remove the compiler setting in stack.yaml, stack install cabal, and put the compiler setting back in. [MacOS 10.14]

**Comment by dmjio** [comment]
Stack support has been [officially deprecated](https://github.com/commercialhaskell/stack/commit/c94b0405baa2e8e5c3a2552896fbbb9f2184ab9d), we recommend using `nix` with [miso's binary cache](https://haskell-miso.cachix.org).
