### ISSUE TITLE
Binary cache hydra.dmj.io down

### ISSUE THREAD

**Issue by madnight** [dmjio/miso#434]
**Describe the bug**
Binary cache server hydra.dmj.io seems to be down.   
I tried it several times on different days.

**To Reproduce**
0. Go to https://github.com/dmjio/miso#binary-cache
  I. See suggestion `nix-build --option extra-binary-caches https://hydra.dmj.io `
2. Try suggestion
3. See error:

```
nix-build --option extra-binary-caches https://hydra.dmj.io                                                                            
warning: unable to download 'https://hydra.dmj.io/nix-cache-info': Couldn't connect to server (7); retrying in 352 ms
```

**Expected behavior**
Server should respond with 200 OK and deliver nix binary cache.

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - KERNEL: Linux 4.16.4-1-ARCH
 - SHELL: zsh

**Comment by dmjio** [comment]
@madnight use this for now https://hydra.dmj.io/nix-cache-info
