### ISSUE TITLE
https://sse.haskell-miso.org/ is unreachable

### ISSUE THREAD

**Issue by JamieBallingall** [dmjio/miso#437]
**Describe the bug**
The link in the README under SSE is broken.

**To Reproduce**
Try to go to https://sse.haskell-miso.org/ or go to https://github.com/dmjio/miso#sse and click "Link".

**Comment by dmjio** [comment]
@JamieBallingall, thanks. This is also related to https://github.com/dmjio/miso/issues/434

**Comment by dmjio** [comment]
https://sse.haskell-miso.org/
