### ISSUE TITLE
Nix build outdated

### ISSUE THREAD

**Issue by madnight** [dmjio/miso#446]
```nix
let
  result = import (pkgs.fetchFromGitHub {
	owner = "dmjio";
	repo = "miso";
	sha256 = "1l1gwzzqlvvcmg70jjrwc5ijv1vb6y5ljqkh7rxxq7hkyxpjyx9q";
	rev = "95f6bc9b1ae6230b110358a82b6a573806f272c2";
  }) {};
```

The nix instructions in the README.md suggest an old version of miso `95f6bc9b1ae6230b110358a82b6a573806f272c2`

Suggested upgrade:
`sha256 = "0q0m105c7jj913vh4mc9qsnc9ddvldff1np364z6acw6fyslnn5r";`
`rev = "5c3d01780bce2f803bf10d531c876250be5eebc6";`

**Comment by dmjio** [comment]
I have code for this, just need to update. I'm using 8.4.

**Comment by LucianU** [comment]
Just want to add that I'm hitting an issue with this as well, as I'm on Mojave.

**Comment by dmjio** [comment]
Upgrade occurring in #493
