### ISSUE TITLE
Checkbox onChange / onChecked do not work in safari

### ISSUE THREAD

**Issue by tysonzero** [dmjio/miso#453]
Basically just the title, can't seem to get checkboxes properly working on safari at all.

See: https://github.com/tysonzero/miso-example/tree/checkbox-bug

It is possible that this bug pertains to GHCJS itself, but I figured I would start here.

**Comment by dmjio** [comment]
@tysonzero can you paste the error you're receiving as well.

**Comment by dmjio** [comment]
@tysonzero It appears to be a bug in safari. The stack trace ghcjs raises shows the error occurs here:


Offending code:
<img width="376" alt="screen shot 2018-08-24 at 8 20 38 am" src="https://user-images.githubusercontent.com/875324/44584728-e6cde480-a777-11e8-9d9c-6d2d35215f84.png">

```javascript
if (typeof obj[i] == "string" || typeof obj[i] == "number" || typeof obj[i] == "boolean")
      newObj[i] = obj[i];
    }
```

The code above accumulates an event object that the checked decoder gets executed on. Right now, whenever the fields "selectionStart", "selectionEnd" or "selectionDirection" are referenced, safari webkit throws a TypeError.

Here is an example in safari:
<img width="294" alt="screen shot 2018-08-24 at 8 18 54 am" src="https://user-images.githubusercontent.com/875324/44584738-ec2b2f00-a777-11e8-9cc2-f5281bc09373.png">


Here is an example in chrome:
<img width="357" alt="screen shot 2018-08-24 at 8 19 00 am" src="https://user-images.githubusercontent.com/875324/44584752-f6e5c400-a777-11e8-946e-77d8d6bff4ba.png">

Trying to track down the source of this bug, and a good solution. Stay tuned.

**Comment by dmjio** [comment]
I believe this is a bug in Safari according to the spec. 

> If this element is an input element, and selectionStart does not apply to this element, return null.

https://html.spec.whatwg.org/multipage/form-control-infrastructure.html#dom-textarea/input-selectionstart

**Comment by dmjio** [comment]
https://github.com/dmjio/miso/pull/454
