### ISSUE TITLE
Miso for GHC 8.0 with Nix?

### ISSUE THREAD

**Issue by cah6** [dmjio/miso#457]
Hey there,

Is there a good pinned nixpkgs / miso version for developing on GHC 8.0+ with Nix? I see that 8.2+ might be broken from https://github.com/dmjio/miso/issues/414, but I'd still like to try it out with 8.0 as that version released a lot of ghci commands that could make https://github.com/dramforever/vscode-ghc-simple feasible as a simple editor for miso projects. 

Note that I did try a few combinations of nixpkgs / miso version in the initial setup's `default.nix`, the most recent of which was simply updating miso to the latest commit. This seemed to prompt it to use GHC 8.0.2 but having to re-compile pretty much everything.

**Comment by dmjio** [comment]
@cah6 please checkout the `8.4` branch and call `nix-build`. This should build the latest `ghcjs` with a working `nixpkgs`.

https://github.com/dmjio/miso/blob/8.4/default.nix#L1
