### ISSUE TITLE
Pre-render no-end tags correctly

### ISSUE THREAD

**Issue by dmjio** [dmjio/miso#466]
**Describe the bug**
When attempting to pre-render a page, certain elements like `br` are rendered incorrectly in `lucid`, causing `walk` to error out in `isomorphic.js`. The solution is to use the `noEnd` suite of functions from `lucid` to render `<br>` tags (among others) correctly. 

cc @tysonzero

**Comment by tysonzero** [comment]
https://github.com/dmjio/miso/blob/master/ghc-src/Miso/Html/Internal.hs#L86

This is the line in question that sometimes needs to be `L.makeElementNoEnd` instead.

I personally think a decent solution is to change the type of `vChildren` from `V.Vector (VTree action)` to `Maybe (V.Vector (VTree action))`. Where `Nothing` means `<foo>`, `Just []` means `<foo></foo>` and `Just xs` means `<foo>...xs...</foo>`.

Then in `Miso.Html.Element` you can define:

```
nodeHtml :: MisoString -> [Attribute action] -> [View action] -> View action
nodeHtml name attrs children = node HTML name Nothing attrs (Just children)

nodeHtmlVoid :: MisoString -> [Attribute action] -> View action
nodeHtmlVoid name attrs = node HTML name Nothing attrs Nothing
```

And now all the existing code that uses `nodeHtml` is unaffected, and the problematic void elements that shouldn't have closing tags can be switched from `flip (nodeHtml "foo") []` to `nodeHtmlVoid "foo"` with a simple find and replace.

This has the upside of allowing users to define new void elements that Miso isn't aware of (say new things get added to the Html5 spec before they get added to Miso / the user is on an older version of Miso), it also means that the bookkeeping of void vs non-void elements is in one place.

The downside is that if someone did decide to create `nodeHtml[NotVoid] "br" ...` it would be incorrect, but I think that's a fairly minor issue, we can't truly guarantee correct Html5 without putting those element names in the type system directly.

**Comment by dmjio** [comment]
https://github.com/dmjio/miso/commit/70bf9aa9aec0467ca551c366a3e4c19f99db6a02
