### ISSUE TITLE
bidirectional web apps using Miso

### ISSUE THREAD

**Issue by juliendehos** [dmjio/miso#467]
Hi,
Thanks for developing Miso. I've looked into FPtje's [miso-isomorphic-example](https://github.com/FPtje/miso-isomorphic-example) and I really like having both client code and server code in Haskell.

Now, I'm considering a "bidirectional" app, where the server can push notifications to its clients, so I wrote this collaborative counter app : https://gitlab.com/juliendehos/isocounter. This was quite simple to do but I had to handle some low-level stuff (e.g. websockets, client connections, message formatting...) that are handled more nicely in my other implementations (Javascript/socket.io or C++/Wt).

Is there a better implementation of push notifications using Miso ? It may be interesting to add an example (such as a classic chat application) in the Miso repo.

**Comment by dmjio** [comment]
Very nice! Love to see examples like this. In the specific case of push notifications, I do recommend the `wai` server sent events (SSE) implementation. `miso` plays nicely with this API. There is also some example code here https://github.com/dmjio/miso/blob/master/examples/sse/server/Main.hs#L44

**Comment by juliendehos** [comment]
Thanks for mentioning SSE. I've rewritten the app and it plays nice with Miso, indeed. I'll try to implement a servant API when I have more time.

**Comment by juliendehos** [comment]
I finally rewrote the app using Servant : https://gitlab.com/juliendehos/isocounter/tree/master/miso_servant_sse. I really like how Miso handles the "isomorphic" technique.
Thanks for the help, I think this issue can be closed.

**Comment by dmjio** [comment]
@juliendehos it looks great, well done :beers: !
