### ISSUE TITLE
prevent errors from halting the entire js app

### ISSUE THREAD

**Issue by silky** [dmjio/miso#468]
**Is your feature request related to a problem? Please describe.**
If you an `error` occurs when returning a model, the entire JS app halts.

**Describe the solution you'd like**
I'd like it not to halt the entire app. It should just leave the previous state rendered, and continue accepting new events.

**Additional context**
Example:

Accept any input and parse it into your model. If the input isn't valid, observe that no more events are processed.

**Comment by dmjio** [comment]
It should be possible to catch exceptions that would otherwise cause the app to crash. In the case of parsing, is it not possible to return an `IO (Either ParseError a)` ?

@silky If you can shed some more light on your specific scenario I can be of more help.

**Comment by silky** [comment]
thanks for the quick response @dmjio  !

yeah; i had actually assumed I'd be able to catch exceptions as well, but i couldn't manage it, probably i was just doing the wrong thing.

i tried something like this:

```
updateModel (TryChangeBackgroundColour s) m = 
  m <# do
    let f :: SomeException -> IO (Colour Double)
        f _ = return red

    newColour <- catch (return $ sRGB24read (fromMisoString s)) (f)
    pure $ DefinitelyChangeBackgroundColour newColour
```

but the error isn't caught.

oh, but i just noticed if i do this, it works:

```
    newColour <- catch (evaluate $ sRGB24read (fromMisoString s)) (f)
```

(i.e. for the error to be hit in the effect part of the update)

my main point is that i have to do this in the effect part though; i..e i have to have this "try/definitely" pattern, which is clearly ugly.

i'm sure i'm missing some better idea?

**Comment by dmjio** [comment]
Can you call `Text.Read.readMaybe` instead, so you don't have to perform exception handling in IO ?

**Comment by dmjio** [comment]
I’d view this moreso as user error then a problem with miso itself. If exceptions aren’t working as expected (as on ghc), is recommend reopening this issue there.

**Comment by silky** [comment]
maybe i'm not being clear; but the problem isn't about how _i_ catch the error in the effect part; it's the fact that if the particular path of the model update that returns the next model ends in an error, that kills the entire app.

as an example, consider this tiny modification of the complete sample app (only change is that subtract errors immediately):

```
08:16 AM noon ∈ sample-app (master*) ♫ cat Main.hs 
-- | Haskell language pragma
{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE RecordWildCards #-}

-- | Haskell module declaration
module Main where

-- | Miso framework import
import Miso
import Miso.String

-- | Type synonym for an application model
type Model = Int

-- | Sum type for application events
data Action
  = AddOne
  | SubtractOne
  | NoOp
  | SayHelloWorld
  deriving (Show, Eq)

-- | Entry point for a miso application
main :: IO ()
main = startApp App {..}
  where
    initialAction = SayHelloWorld -- initial action to be executed on application load
    model  = 0                    -- initial model
    update = updateModel          -- update function
    view   = viewModel            -- view function
    events = defaultEvents        -- default delegated events
    subs   = []                   -- empty subscription list
    mountPoint = Nothing          -- mount point for application (Nothing defaults to 'body')

-- | Updates model, optionally introduces side effects
updateModel :: Action -> Model -> Effect Action Model
updateModel AddOne m = noEff (m + 1)
updateModel SubtractOne m = error "Some error"
updateModel NoOp m = noEff m
updateModel SayHelloWorld m = m <# do
  putStrLn "Hello World" >> pure NoOp

-- | Constructs a virtual DOM from a model
viewModel :: Model -> View Action
viewModel x = div_ [] [
   button_ [ onClick AddOne ] [ text "+" ]
 , text (ms x)
 , button_ [ onClick SubtractOne ] [ text "-" ]
 ]
```

if you click subtract, not only do you get the error display in the console, but the entire app stops working. it seemed more intuitive to me that it's just that _function_ that would fail; and all the other functions would continue to work.

the fix could be to catch any and all updates in the `updateModel` function itself, and have a `maybeUpdateModel` which tries to update the model, and upon failure, just returns the old state. but i'm asking, why not make this the default?

**Comment by dmjio** [comment]
So this is a pure update to a record happening in the main thread of execution (not a green thread), javascript is single threaded, if your functions aren't total, then it will crash in a bad way. Miso is not going to make assumptions about exception handling for users in either IO or pure record updates. It will also not make assumptions about the semantics of your update logic. If you choose the partial path you'll pay the penalty. Exception handling in Haskell is something everybody does differently. It also has a performance penalty attached to it. Like Elm, there are large miso apps in production that have 0 runtime crashes.

**Comment by silky** [comment]
i mean, i don't know what to tell you; obviously if life was amazing and the world was great there would be no partial functions and i wouldn't be reporting this bug.

*shrug*

i get that you don't want to implement this, though.

**Comment by dmjio** [comment]
Haskell isn't a total language, Elm is better in this regard. But you can definitely write Haskell in such a way to mitigate the presence of all partial functions, and that is definitely not asking too much. If you're using `head`, `fromJust`, `read` all over the place, you're asking for it. Write good Haskell code is the answer, use `listToMaybe`, `maybe`, `readMaybe` instead.

**Comment by silky** [comment]
no doubt; but my point is that it's not entirely up to me, it's also up to the libraries i depend on.

the point is, presently, if i want to be fully cerain i need to follow this pattern of "try/definitely" actions; which is terribly ugly, or implement this "maybeUpdateModel" function (which i'm doing now). 

i understand that, from a haskell app point of view, it makes total sense for the entire thing to error; it's just that the default implementation wasn't intuitive to me from a web-app point of view. maybe it's the way elm works; (i don't know, and i'm not interested in checking just at the moment).

**Comment by dmjio** [comment]
If you're parsing something, you don't need `try`, it should return an `Either String a` or you need to find a new parsing library. I'll admit, I have no idea what you're trying to do, but it sounds like parsing, and that should always be pure.

**Comment by silky** [comment]
parsing colours was the first example; which is handled easily as you say either by readMaybe or the way i'd done it above by munging to IO

what hit me next was an invalid combination of parameters to drawing a diagam with diagrams-miso that resulted in that library throwing a divide-by-zero error.

so yeah, i could re-implement that logic to check for the bad case; or i could just handle the error. but i had to handle it with the try/definitely pattern. hence the issue.

**Comment by dmjio** [comment]
divide-by-zero is another classic case of things that should be handled purely and can be mitigated completely by the type system. This is an error I'd bring up on the diagrams library you're using.

**Comment by dmjio** [comment]
This is why we can't have nice things @silky :)
