### ISSUE TITLE
Subscribing to a Sub which uses threadDelay prevents the app from being rendered

### ISSUE THREAD

**Issue by peterstuart** [dmjio/miso#470]
Thanks for the great library! I'm really enjoying using Miso.

**Describe the bug**
Subscribing to a `Sub` which uses `threadDelay` seems to prevent the app from ever being rendered. I wrote a `Sub` which should fire every second, based on your comment in https://github.com/dmjio/miso/issues/284. I can see in the console that the `Sub` is indeed running ("test" is printed every second), but the app is never rendered.

**To Reproduce**
```haskell
{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE RecordWildCards #-}

module Main where

import           Miso
import           Miso.String

import qualified Control.Concurrent            as Concurrent
import qualified Control.Monad                 as Monad

data Action = Add | Subtract deriving (Eq, Show)

main :: IO ()
main = startApp App {..}
 where
  initialAction = Add
  model         = 0
  events        = defaultEvents
  subs          = [timer]
  mountPoint    = Nothing

  update Add      m = noEff (m + 1)
  update Subtract m = noEff (m - 1)

  view :: Int -> View Action
  view x = div_
    []
    [ button_ [onClick Add] [text "+"]
    , text . ms . show $ x
    , button_ [onClick Subtract] [text "-"]
    ]

  timer :: Sub Action
  timer sink = Monad.forever $ do
    Concurrent.threadDelay 1000000
    putStrLn "test"
    sink =<< Add <$ now
```

Running this code results in this DOM, which never changes:

<img width="398" alt="screen shot 2019-01-20 at 8 57 03 am" src="https://user-images.githubusercontent.com/98044/51440118-5eedf700-1c91-11e9-8865-c91b21bee0cf.png">

**Expected behavior**
The app should render normally, and the value should increase by 1 every second.

**Desktop (please complete the following information):**
 - OS: macOS 10.14.2
 - Browser: Chrome
 - Version: 71

**Comment by dmjio** [comment]
@peterstuart Awesome! Glad you’re putting it to good use. For this I’d try putting a call to `forkIO` before the call to `forever`. Without `forkIO` the sub will use the main thread of execution, so it will block page rendering. Let me know how it goes!

**Comment by peterstuart** [comment]
Perfect, thank you! Sorry for cluttering up your issues with my mistakes 😄
