### ISSUE TITLE
THRunner crash during compilation on 0.21.2.0

### ISSUE THREAD

**Issue by patrickmn** [dmjio/miso#472]
**Describe the bug**
I'm experiencing a crash involving GHCJS' THRunner during compilation that's hard to debug:

```
[26 of 63] Compiling Web.Dom ( src/Web/Dom.hs, .stack-work/dist/x86_64-linux/Cabal-1.24.2.0_ghcjs/build/Web/Dom.js_o )
Linking Template Haskell (Web.Manager,Web.Component,Prelude,...,ThRunner23)
uncaught exception in Haskell main thread: ReferenceError: window is not defined
ReferenceError: window is not defined
    at eval (eval at h$loadCodeStr (/home/patrick/.ghcjs/x86_64-linux-0.2.1.9007019-8.0.1/ghcjs/thrunner.js:141:10), <anonymous>:3329:1)
    at eval (<anonymous>)   
    at Object.h$loadCodeStr [as loadCodeStr] (/home/patrick/.ghcjs/x86_64-linux-0.2.1.9007019-8.0.1/ghcjs/thrunner.js:141:10)
    at Object.h$loadCode [as loadCode] (/home/patrick/.ghcjs/x86_64-linux-0.2.1.9007019-8.0.1/ghcjs/thrunner.js:149:10)
    at h$$ghcjszmthzm0zi1zi0zi0zmBEGv9AyA1xR6tq2yjrbQODZCGHCJSziPrimziTHziEval_e7 (eval at h$loadCodeStr (/home/patrick/.ghcjs/x86_64-linux-0.2.1.9007019-8.0.1/ghcjs/thrunner.js:141:10), <anonymous>:129322:16)
    at h$runThreadSlice (eval at h$loadCodeStr (/home/patrick/.ghcjs/x86_64-linux-0.2.1.9007019-8.0.1/ghcjs/thrunner.js:141:10), <anonymous>:8271:11)
    at h$runThreadSliceCatch (eval at h$loadCodeStr (/home/patrick/.ghcjs/x86_64-linux-0.2.1.9007019-8.0.1/ghcjs/thrunner.js:141:10), <anonymous>:8221:12)
    at h$mainLoop (eval at h$loadCodeStr (/home/patrick/.ghcjs/x86_64-linux-0.2.1.9007019-8.0.1/ghcjs/thrunner.js:141:10), <anonymous>:8216:9)
    at eval (eval at h$loadCodeStr (/home/patrick/.ghcjs/x86_64-linux-0.2.1.9007019-8.0.1/ghcjs/thrunner.js:141:10), <anonymous>:8782:13)
    at /home/patrick/.ghcjs/x86_64-linux-0.2.1.9007019-8.0.1/ghcjs/thrunner.js:97:9
Data.Binary.Get.runGet at position 0: not enough bytes
CallStack (from HasCallStack):
  error, called at libraries/binary/src/Data/Binary/Get.hs:342:5 in binary-0.8.3.0:Data.Binary.Get
Completed 2 action(s).      

--  While building package foo-0.1.0.0 using:
      /home/patrick/.stack/setup-exe-cache/x86_64-linux/Cabal-simple_mPHDZzAJ_1.24.2.0_ghcjs-0.2.1.9007019_ghc-8.0.1 --builddir=.stack-work/dist/x86_64-linux/Cabal-1.24.2.0_ghcjs build lib:foo exe:foo-web --ghcjs-options " -ddump-hi -ddump-to-file"
    Process exited with code: ExitFailure 1
```

It does NOT happen on miso-0.21.1.0, and, oddly, there are no Miso modules listed in the "linking Template Haskell" module list.

The most likely culprits I could find are the jsbits that changed "func foo{}" to "window.foo" [between miso-0.21.1.0 and miso-0.21.2.0](https://github.com/dmjio/miso/compare/0.21.1.0...0.21.2.0#diff-8731ee2352d5cd5f69b17c9a04e081b3) (see Changed files)

I'm guessing 'window' isn't available in THRunner?

I will try to change these jsbits shortly and report back.

**To Reproduce**
1. Use ghcjs-0.2.1.9007019_ghc-8.0.1 and miso-0.21.2.0
2. Use TemplateHaskell (e.g. to derive lenses in Types.hs)
3. Build

**Expected behavior**
No crash

**Desktop (please complete the following information):**
 - OS: Linux

**Comment by dmjio** [comment]
> I'm guessing 'window' isn't available in THRunner?

That is correct, changes were made to incorporate `jsaddle` that caused a regression in `ghcjsi-7.10.3` TH linking. The fix for this would require removing `window` as a prefix to those functions (i.e. `diff`), which I would be fine with. Although, this might break `jsaddle` support. At this point I'd be fine deprecating `jsaddle` since I'm not sure many people use it. But ideally we could keep `jsaddle`, and not use the `window` prefix.

**Comment by patrickmn** [comment]
I wonder if you could just have a `window = window || {};` at the top, since it seems you're only adding functions?

**Comment by patrickmn** [comment]
Scratch that. There I go hoping it can be simple :)

https://github.com/dmjio/miso/compare/master...patrickmn:master results in

```
uncaught exception in Haskell thread: TypeError: Cannot read property 't' of undefined
all.js:7228 TypeError: Cannot read property 't' of undefined
    at h$e (all.js:18958)
    at all.js:147896
    at h$runThreadSlice (all.js:8265)
    at h$runThreadSliceCatch (all.js:8221)
    at h$mainLoop (all.js:8216)
    at all.js:2521
    at runIfPresent (all.js:2539)
    at onGlobalMessage (all.js:2580)
```

**Comment by sheyll** [comment]
Please keep the jsaddle support a little longer, if at all possible. At least until we have progressed with our current project to a point where we can make a judgement about it's usefulness. Please, please, please?

**Comment by dmjio** [comment]
@sheyll sure, I didn't know people were using it. I'll probably never take it out then.

**Comment by dmjio** [comment]
This seems to be moreso related to `GHCJS` than `miso` itself. Also, I'd recommend upgrading to GHCJS 8.6 (`miso` master gives this), and see if this issue still persists. If so, I'd repost on https://github.com/ghcjs/ghcjs/

**Comment by patrickmn** [comment]
I'm still seeing this in the form of a crash when trying to execute the jsexe with `node`. Previously, the miso jsbits didn't reference `window`; now they do, so the program doesn't run. (Tbf I could just move the `miso` dep to a browser-only executable, but still..) It also breaks the test-suite.

I am using GHCJS 8.4.0.1 atm -- unfortunately I can't upgrade.

**Comment by dmjio** [comment]
Seems to make sense, the DOM does not exist in `node`, unless you use a tool like `jsdom` to provide one. The test-suite only works with a mock DOM (`jsdom`.) What is the use case for using `node` I guess.

**Comment by patrickmn** [comment]
To be clear, I'm referring to my own test-suite. I'm including `miso` as a library-level dependency in a cabal file that has a test-suite and a ghc, node, and browser-only executable so that I get ghcid for the Views among other things. Because the jsbits are injected into jsexe output no matter what, this means my node exe and ghcjs test-suite break due to `window` not existing.

I can rearrange things to get around it, but just making you aware that this worked previously.

**Comment by dmjio** [comment]
@patrickmn yea it does seem like a regression, can you try this PR out: https://github.com/dmjio/miso/pull/512

**Comment by patrickmn** [comment]
Yep, works again given that change. Thanks!
