### ISSUE TITLE
Readme for stack update

### ISSUE THREAD

**Issue by ynishi** [dmjio/miso#475]
**There are invalid part in readme for stack**
* stack.yaml - invalid indent was included, I copied and built but failed.
* open - linux(Ubuntu 18.04.2 LTS) not worked, xdg-open was worked.

**When follow readme in stack**
https://github.com/dmjio/miso#stack

**Expected**
* no error when build
* add description for linux

**Desktop:**
 - OS: Ubuntu
 - Browser -
 - Version 18.04.2 LTS

I think it is little bit fix, but good for newbie, can I pr it?

**Comment by dmjio** [comment]
@ynishi sure, go ahead and PR. Thanks for spotting this.

**Comment by ynishi** [comment]
@dmjio Thanks for reply! I sent it.
