### ISSUE TITLE
onInput doesn't work for contenteditables

### ISSUE THREAD

**Issue by mikelpr** [dmjio/miso#484]
onInput doesn't work for contenteditables, miso tries to read the value of the element but there's no value in this case (only the InputEvent emitted with the new character)

e.g. I have this:
````
div_ [
    boolProp "contenteditable" True
  , onInput (\i -> pa $ Edit (path, Just edi{description=jstx2h i}))
  ]
````

and it outputs this on the console
````
Parse error on input: Error in $: key "value" not present
CallStack (from HasCallStack):
  error, called at frontend-src/Miso/Html/Internal.hs:252:20 in miso-0.21.2.0-4ZWiGe453GhAgW9yh7lwjm:Miso.Html.Internal
````

**Comment by mikelpr** [comment]
got around with this decoder:
````
contenteditableDecoder :: Decoder MisoString
contenteditableDecoder = Decoder {..}
  where
    decodeAt = DecodeTarget ["target"]
    decoder = withObject "target" $ \o -> o .: "innerHTML"
````

**Comment by dmjio** [comment]
Closing as fixed, reopen if something else arises.

**Comment by mikelpr** [comment]
I'm not sure if it is a reason for reopening this (or opening another)

but there's a bug using them contenteditables: miso does not see a value change (they change/add node children) so it doesn't update the view when it changes in your model
