### ISSUE TITLE
How to bring back control flow from asynchronous JavaScript to Miso?

### ISSUE THREAD

**Issue by y-taka-23** [dmjio/miso#486]
In my understanding, Miso cannot handle promises rise in JavaScript.

Assume that we have a JS function `mylib.get()`, which tries to fetch something from a remote server and return a promise. In Miso side, we want to invoke the `get()` by an action `Get`, and when the promise results in `catch` clause, purely update the Model by an action `HandleError`.

For example, using Jsaddle for the sake of simplicity, I'm talking about:

```haskell
updateModel Get m = m <# do
    jsg "mylib" ^. js0 "get" ^. js1 "catch" (fun $ \_ _ [v] -> do
        return ())  -- (*) How can we fire the `HandleError` action here?
updateModel HandleError m =
    noEff m { errCount = 1 + errCount m  }
```

In Elm, it's addressed because JavaScript should be placed out of Elm code and talk with the port in/out and port-in is a subscription at Elm's point of view.

In Miso, I know we can register a subscription like `mySub :: action -> Sub action`, but as far as I know, we have no way to fire it without writing JavaScript code.

What is the best practice to handle such control flow in Miso? Is writing JavaScript glue unavoidable?

**Comment by dmjio** [comment]
Hey @y-taka-23, 

In this case there is a special function that @FPtje added called `effectSub`, that allows you to access the `sink` inside of an update handler. But it's true, all IO in `miso` is asynchronous.

```haskell
updateModel Get m = effectSub m $ \sink -> do
    jsg "mylib" ^. js0 "get" ^. js1 "catch" (fun $ \_ _ [v] -> do
        sink HandlerError
        return ())
updateModel HandleError m =
    noEff m { errCount = 1 + errCount m  }
```

https://haddocks.haskell-miso.org/src/Miso.Effect.html#effectSub

Let me know how this goes.

**Comment by y-taka-23** [comment]
Thanks for the comment. Yes, it awesomely helps me!
