### ISSUE TITLE
Haddocks don't link correctly to GHCJS

### ISSUE THREAD

**Issue by turion** [dmjio/miso#487]
Have a look at https://haddocks.haskell-miso.org/Miso-Html.html#t:VTree and inspect the link on `Object`. It points to a nix store (probably a local build product), not a URL in the internet.

**Comment by dmjio** [comment]
This is most likely due to the fact I uploaded the docs directly from a call to `nix-build` and not `Cabal`.

**Comment by dmjio** [comment]
They link well enough now on hackage. https://hackage.haskell.org/package/miso-1.8.0.0/docs/Miso-Html-Types.html#t:VTree
