### ISSUE TITLE
Stack does not support building ghcjs anymore - Suggest that it should be removed from the readme

### ISSUE THREAD

**Issue by JordyMoos** [dmjio/miso#489]
Stack no longer builds ghcjs as of this commit:
https://github.com/commercialhaskell/stack/commit/c94b0405baa2e8e5c3a2552896fbbb9f2184ab9d

I suggest that the installation instructions for stack will be removed or adjusted in a way that it does work. Because following the stack instructions on the readme with the newest stack version does not work and is confusion.

**Comment by dmjio** [comment]
Stack support has been officially deprecated.
