### ISSUE TITLE
Split ToMisoString class?

### ISSUE THREAD

**Issue by noinia** [dmjio/miso#492]
The ToMisoString class currently has two functions: 
`toMisoString :: str -> MisoString`
and 
`fromMisoString :: MisoString -> str `

and there are instances for non-string types such as Int, Double, and Float. This seems wrong to me, as there are clearly MisoStrings that cannot be converted properly into Ints, Doubles, or Floats. It is clearly nice to be able to easily serialize such types into MisoStrings when building a view [1]. So I think it would be much cleaner to have separate 'ToMisoString' and 'FromMisoString' typeclasses for the toMisoString and fromMisoString functions, respectively.

[1] this is actually how I ran into this issue; serializing things such as RGB value from the Colour package into a misoString.

**Comment by dmjio** [comment]
`fromMisoString` was meant to be the analog of `read :: Read a => String -> a` for `String`.

> there are instances for non-string types such as Int, Double, and Float. This seems wrong to me, as there are clearly MisoStrings that cannot be converted properly into Ints, Doubles, or Floats.

the same logic would apply to `String` as well, `Read` class simple throws an exception. We could do `fromMisoString :: MisoString -> Either String str` (similar to `Text.Read`) and be verbose about why the conversion does not exist. I think the former was chosen out of expediency.

> So I think it would be much cleaner to have separate 'ToMisoString' and 'FromMisoString' typeclasses for the toMisoString and fromMisoString functions, respectively.

Doing this would definitely remove the need to prove the law that 
`\x -> id x === fromMisoString (toMisoString x)`, `aeson` takes a similar approach with separating out typeclasses for these things. It's definitely worth considering. I'll consider it. If you make a PR I'll be much more apt to accept.

**Comment by dmjio** [comment]
solved in https://github.com/dmjio/miso/commit/7881ce9364beb00b017996b6f9e777284e6adcd5
