### ISSUE TITLE
Add tests

### ISSUE THREAD

**Issue by dmjio** [dmjio/miso#51]
Things to test:
- Correct recognition and application of different patching operations
  - Remove patch
  - Insert patch
  - Keys patch
- Virtual event propagation can be stopped
- Go from VTree <-> DOM (isomorphic js) - caveat: must be done in I/O
  - Check the references are correct
- Lucid HTML instance
- Property diffing
- Node rendering

**Comment by bkc39** [comment]
Whats the status on this? API seems to have changed a bit since the last time I checked in.

Are things stable enough that we can start putting the tests in?

**Comment by dmjio** [comment]
Yea, I'd say our testing infra is in place. All new PRs get built and tests run (on our [hydra](https://hydra.dmj.io)). There only exist a few tests atm [here](https://github.com/dmjio/miso/blob/master/tests/Main.hs#L23-L34). Adding new tests`diff.js` is a high priority.

**Comment by dmjio** [comment]
#370
