### ISSUE TITLE
nix-build doesn't work with package.yaml

### ISSUE THREAD

**Issue by voidus** [dmjio/miso#533]
**Describe the bug**
When using an hpack `package.yaml` instead of a plain cabal file, nix-build fails. As far as I can tell it tries to install an outdated version of hpack, in turn trying to compile an old version of network, which fails. The complete output is at https://github.com/voidus/miso-hpack-error/blob/master/error.

I guess this probably isn't miso's fault, but I'm totally overwhelmed by cabal, nix, and the lack of documentation of `callCabal2nix`. I searched for it, but I can't even find the code that defines it. 😐
If this is fixable, let's fix it. If not, it should probably be documented somewhere?

**To Reproduce**
* Run `hpack-convert` in the sample app and remove the cabal file and nix-build
* This repo creates the files and illustrating scripts: https://github.com/voidus/miso-hpack-error

**Expected behavior**
Compile just as the original sample app does

**Additional context**
I created a repo with scripts and the error output here: https://github.com/voidus/miso-hpack-error

**Comment by dmjio** [comment]
The issue I believe is that it's attempting to compile `hpack` with `ghcjs`, I had to work around something like this. I can look at it more tonight.

**Comment by dmjio** [comment]
@voidus,

Try this:

```nix
with (import (builtins.fetchTarball {                                                                                                                                  
  url = "https://github.com/dmjio/miso/archive/4e15d92cc4f37605fc398229695de4d903ef8a47.tar.gz";                                                                       
  sha256 = "0kg9lg18qdsnb6gw3jmnl49widzf5cy151bls7k09d5dxlm0myd8";                                                                                                     
}) {});                                                                                                                                                                
with pkgs.haskell.packages;                                                                                                                                            
let                                                                                                                                                                    
  app = ghcjs.callCabal2nix "app" ./. {};                                                                                                                              
in                                                                                                                                                                     
  app.override { inherit (ghc865) hpack; } 
```

I'll add this to miso's overrides.

**Comment by dmjio** [comment]
In fact, you only need this now.

```nix
with (import (builtins.fetchTarball {                                                                                                                                  
  url = "https://github.com/dmjio/miso/archive/8de0a8a432252fe83610bfd310fc856148f524f7.tar.gz";                                                                       
  sha256 = "0pmpwnss4ax2c7hcd32cs4phq3b9995wkx6qw6861q2pvqk96rhz";                                                                                                     
}) {});                                                                                                                                                                
pkgs.haskell.packages.ghcjs.callCabal2nix "app" ./. {}  
```

sorry about the inconvenience !

**Comment by voidus** [comment]
Thank you so much for the quick fix 🥰
