### ISSUE TITLE
Readme instruction about building examples seem to be out of date

### ISSUE THREAD

**Issue by jhrcek** [dmjio/miso#551]
**Describe the bug**
The https://github.com/dmjio/miso#building-examples secion of readme seems out of date.

**To Reproduce**
1. Follow the steps from the building examples section.
2. `tree -d result/bin/` results in
result/bin/
├── simple.jsexe
└── tests.jsexe

**Expected behavior**
All of the examples should be built and appear under the `result/bin` folder

**Desktop (please complete the following information):**
 - OS: Fedora 29
 - Browser google-chrome
 - Version 78

**Comment by dmjio** [comment]
https://github.com/dmjio/miso/commit/1fe0dab487af00c864bbbe3dc0756df5b43b794d

**Comment by jhrcek** [comment]
Thank you for the quick fix :+1:
