### ISSUE TITLE
Websocket Closed Unexpectedly 

### ISSUE THREAD

**Issue by DavidEichmann** [dmjio/miso#555]
**Describe the bug**

I'm working on a project using websockets to communicate between backend and frontend. When navigating around the site, quickly the WS connection is closed and chrome complians `WebSocket connection to 'ws://localhost:8080/' failed: Invalid frame header`. I'm using miso with jsaddle + chrome. Note that there are 2 WS connections: one to connect to my backend and another used by jsaddle to communicate with the browser. It looks to me like both WS connections are terminating.

**To Reproduce**

A minimized version of my project can be found here: https://github.com/DavidEichmann/miso-example-01 (I'm on commit 98d935d390f4dfa27b0650c39b9e27cc7c1a2c10)

* Build with `nix-build`
* Run server with `./result/bin/server`
* Run client with `./result/bin/client`
* Open http://localhost:8080 in chrome
  * open the debug console with Ctl+Shift+I and go to the Consol tab
  * Click Login. Either:
    * JS gets stuck in an infinite loop and the websocket connection gets closed. The console shows an error "jsaddle.js:9 WebSocket connection to 'ws://localhost:8080/' failed: Invalid frame header"
    * OR no error, so reload and try hit Login again.

**Expected behavior**

The WS connection should not close, nor should there be an Invalid frame header error.

**Desktop (please complete the following information):**

 - OS: linux mint 18.3
 - Browser chrome  79.0.3945.88 (Official Build) (64-bit)

**Comment by dmjio** [comment]
I think this issue might be better suited for jsaddle's repo.

**Comment by dmjio** [comment]
Closing as related to jsaddle.
