### ISSUE TITLE
Clarify "production-ready"

### ISSUE THREAD

**Issue by thenomemac** [dmjio/miso#556]
The readme cites miso as being production ready. Can there be some clarity on what that means? Is the API stable, is anyone using it in production, ect?

Context: I'm considering using miso for a new side project, the alternative being hallogen, and I'm wondering how far an app has made it towards production with miso. 

FYI: the README for miso is awesome. The live example URLs are amazing. Thanks for all the work miso contributors.

**Comment by dmjio** [comment]
Miso is used in production by a variety of companies, publicly listed are: https://github.com/dmjio/miso/blob/master/README.md#commercial-users

But many other companies that are not listed, are also using it, be it for internal applications, billabel client projects or open source projects.

"Production-ready" means a project is believed to be ready for production use (commercial clients). This claim is backed-up by its [test-suite and code coverage](http://coverage.haskell-miso.org/diff.js.html), personal adoption in my own place of employment and adoption by others in their respective places of employment. Venture-backed companies are currently using miso (and its most cutting-edge features) to build the core of their [public-facing product](https://www.polimorphic.com) with success. 

The core of miso is its mutable rose tree data structure and corresponding [recursive diffing algorithm](https://github.com/dmjio/miso/blob/master/jsbits/diff.js). This algorithm is simple, highly-documented and well-tested. I've personally used it for building four internal projects at said place of employment (using the Haskell API as well as internal JS API). It is also being used on the iPhone after being cross-compiled to iOS via Nix.

But it has been used for consulting projects for clients, and internal line of business applications as well, and other companies that rely on its correct inner-workings.

Miso's internal architecture is so composable it can be abstracted across any language that allows compilation to JS / Web Assembly and FFI into the DOM with ease (including rust, OCaml / Reason / Idris). I'm currently working on releasing `miso.js` (miso w/o Haskell) to NPM.

**Comment by thenomemac** [comment]
Thanks for the thoughtful reply. I'm curious what is meant by:

> Miso's internal architecture is so composable it can be abstracted across any language that allows compilation to JS / Web Assembly and FFI into the DOM with ease (including rust, OCaml / Reason / Idris). I'm currently working on releasing miso.js (miso w/o Haskell) to NPM.

Are you saying that you can somehow "re-target" the compilation of miso apps to/in other languages or that the framework "concepts" can be more or less ported as a re-write to another language.

**Comment by dmjio** [comment]
The latter, as long as the language allows for calling into js (specifically miso's `diff.js`), and construct js objects, miso can be released as a DSL in any other language with minimal work.

**Comment by thenomemac** [comment]
Very interesting. Two questions.

- Do you want me to take a stab at adding a "production-ready" section to the readme highlights some of what you stated in the issue.
- The idea of miso.js sounds interesting... is the goal just to implement miso in JS because you are familiar with the api and believe it's superior to other JS frameworks. Or does miso.js somehow tie back to the haskell variant in some way I'm not understanding.

**Comment by dmjio** [comment]
> Do you want me to take a stab at adding a "production-ready" section to the readme highlights some of what you stated in the issue.

Wouldn't be opposed to more documentation, ever.

> The idea of miso.js sounds interesting... is the goal just to implement miso in JS because you are familiar with the api and believe it's superior to other JS frameworks. Or does miso.js somehow tie back to the haskell variant in some way I'm not understanding.

https://krausest.github.io/js-framework-benchmark/current.html will show `misojs` and `miso` benchmarks, you can see the overhead Haskell-to-JS interop introduces.

**Comment by thenomemac** [comment]
So will misojs be usable from Haskell via.bjndings or a js only framework?

**Comment by dmjio** [comment]
`miso.js` would be a light wrapper around `diff.js` and friends. The Haskell version of miso just calls into `diff.js` and friends directly.

**Comment by thenomemac** [comment]
Do you envisioning misojs becoming a primary way to use miso or is it going to potentially make Haskell users able to call parts of a miso written JS and vice versa.

**Comment by dmjio** [comment]
It won't replace the Haskell version of miso, but it would allow JS devs to have their own version of miso that behaves just like the Haskell version. Haskell version can already call parts of miso written JS, that's exactly what it does internally.
