### ISSUE TITLE
Custom Index.html?

### ISSUE THREAD

**Issue by itmuckel** [dmjio/miso#569]
The threejs example uses a custom index.html where other js libraries are included. On the other hand when building the miso/sample-app, an index.html is generated together with a few js files. Where does this html file get put together?

The threejs example has an index.html next to the Main.hs and the index.html seems to get used. I couldn't find any flag in the cabal file that seems to do this.

So what is the best way to include external js libraries?

**Comment by dmjio** [comment]
GHCJS generates a default index.html for each build. I don't believe there is a way to change its contents via the cabal file. I've gone ahead and manually updated it. Important to note is that your updates to the `index.html` should be preserved across calls to `cabal build`. So the best way to include external JS is to update the `<head>` section of `index.html` to include a `<script>` tag to the CDN / location of your JS.
