### ISSUE TITLE
The XHR example seems broken

### ISSUE THREAD

**Issue by itmuckel** [dmjio/miso#571]
**Describe the bug**
When using https://xhr.haskell-miso.org and clicking "Fetch JSON...", nothing happens and the browser console shows:
```
Error in $: key "team_url" not present
CallStack (from HasCallStack):
  error, called at xhr/Main.hs:135:15 in main:Main
```

**Expected behavior**
Seeing some data

**Desktop (please complete the following information):**
 - OS: Windows 10 64bit
 - Browser Firefox
 - Version 74

**Comment by dmjio** [comment]
https://github.com/dmjio/miso/commit/456be785bd70115d793cb3e59bd045204f9978ef
