### ISSUE TITLE
Change documentation link of "line_" and "textPath_" in "Miso.Svg.Element"

### ISSUE THREAD

**Issue by jumper149** [dmjio/miso#573]
https://github.com/dmjio/miso/blob/f123e2b55da743117f8802384969d59b8d96d70d/src/Miso/Svg/Element.hs#L137

The documentation of `Miso.Svg.Element.line_` links to the documentation of `image`.

**Comment by jumper149** [comment]
https://github.com/dmjio/miso/blob/f123e2b55da743117f8802384969d59b8d96d70d/src/Miso/Svg/Element.hs#L254

Here is another mistake with `Miso.Svg.Element.textPath_`'s documentation.

**Comment by jumper149** [comment]
... and here are weird underscores breaking the link:

https://github.com/dmjio/miso/blob/f123e2b55da743117f8802384969d59b8d96d70d/src/Miso/Svg/Element.hs#L129

**Comment by dmjio** [comment]
@jumper149 yea, a lot of the documentation additions were ad-hoc. I'd gladly accept a PR with the fix if you're so inclined.

**Comment by dmjio** [comment]
https://github.com/dmjio/miso/commit/68c59190ff14de7d4d90f2f1a37e27ba1e80610a

**Comment by jumper149** [comment]
I was just about to make a pull request myself^^

Thank you for caring about the docs :)

**Comment by dmjio** [comment]
you're welcome :)
