### ISSUE TITLE
br_ breaks miso-isomorphic example

### ISSUE THREAD

**Issue by niteria** [dmjio/miso#585]
Thanks for this framework, I had a lot of fun playing with it.

**Describe the bug**
If I use the `br_` function in the template there's an exception in the browser console and the app doesn't respond to anything.

**To Reproduce**
```
git clone https://github.com/niteria/miso-isomorphic-example && cd miso-isomorphic-example
(cd $(nix-build) && bin/server)
# look at localhost:3003 in the browser, works as intended, no errors in the browser console
# kill the process
git checkout with_br_
(cd $(nix-build) && bin/server)
# look at localhost:3003 in the browser, doesn't work anymore
```
The message from the console:
```
uncaught exception in Haskell main thread: TypeError: g is undefined
window.walk@http://localhost:3003/static/all.js:694:165
window.walk@http://localhost:3003/static/all.js:694:468
window.walk@http://localhost:3003/static/all.js:694:468
window.copyDOMIntoVTree@http://localhost:3003/static/all.js:693:110
h$$aeN@http://localhost:3003/static/all.js:1942:278
h$runThreadSlice@http://localhost:3003/static/all.js:255:243
h$runThreadSliceCatch@http://localhost:3003/static/all.js:254:46
h$mainLoop@http://localhost:3003/static/all.js:253:163
e/<@http://localhost:3003/static/all.js:71:148
f@http://localhost:3003/static/all.js:71:254
e@http://localhost:3003/static/all.js:72:160
uncaught exception: Thread aborted, exit code: 0 all.js:71:271
	f http://localhost:3003/static/all.js:71
	e http://localhost:3003/static/all.js:72
```

If I look in the source I get:
```
<!DOCTYPE HTML><head><title>Miso isomorphic example</title><meta charset="utf-8"><script defer async src="/static/all.js"></script></head><body><div><div><button>-</button>0<br></br><button>+</button></div><button>Go to /flipped</button></div></body>
```

**Expected behavior**
I expect the original app to work with changed appearance because of the `br` tag

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser: Firefox
 - Version: 76.0.1

**Additional context**
This is the change that breaks it: https://github.com/niteria/miso-isomorphic-example/commit/25bfb4f57f3f93795e90dd062060e5c0ca367221

If I were to speculate the server and the client render the same view differently. I've run into issues like that before. You have to be careful to make sure that the HTML from the server is the same that the client renders from the initial model, otherwise the app crashes on startup.

I use my repository because it pins to miso's nixpkgs and it builds quickly because it's able to use cachix.

**Comment by dmjio** [comment]
Thanks, I'll check it out.

**Comment by dmjio** [comment]
`<br></br>` is invalid HTML and rendered as two `<br>` tags in modern browsers. See https://validator.w3.org/ for example. This would break synchrony between client and server. Onus is on the user to get this right.

**Comment by dmjio** [comment]
Whoops, didn't mean to close. @niteria if miso's `ToHtml` instance on `View`, on the `GHC` side is rendering in this way, that is a bug.

**Comment by dmjio** [comment]
```haskell
> renderBS $ toHtml (Miso.br_ [])
"<br></br>"
```

@niteria you found a bug, congrats 🎉

**Comment by niteria** [comment]
As a follow-up, I run into server-rendering-different-than-client bugs quite often, mostly because of bad logic on my part and occasionally because `Network.URI` generated by routes differ between the server and the client.

It'd be nice if the `Miso.miso` function used for isomorphic apps had a version that did some sanity checking and helped narrow down the differences.

Also, correct me if I'm wrong, but the server and the client basically have to use the same `Model`.
Same meaning that the view function generates the same DOM. 

The way I accomplish that currently is kind of clumsy. Before I run the `Miso.miso` function I fetch the model from the sever with XHR. That's inefficient because of an extra request and incorrect because of a potential race condition with the server moving on with the data. Is there a better way?

I'd be happy to open additional issues with the above questions if you'd prefer that.

**Comment by dmjio** [comment]
> As a follow-up, I run into server-rendering-different-than-client bugs quite often, mostly because of bad logic on my part and occasionally because Network.URI generated by routes differ between the server and the client. The difference is that one of them has the host part and the other doesn't.

You should make an issue for this, definitely.

**Comment by dmjio** [comment]
https://github.com/dmjio/miso/pull/586

**Comment by dmjio** [comment]
@niteria can you do me a favor and just double-check this is resolved per your example.

**Comment by niteria** [comment]
Sure, retested it and it works.
For reference https://github.com/niteria/miso-isomorphic-example/tree/with_br_retest is a branch that uses today's master.

**Comment by dmjio** [comment]
awesome :) I'll try to release a new version
