### ISSUE TITLE
Route Network.URIs inconsistent between server and client in isomorphic example

### ISSUE THREAD

**Issue by niteria** [dmjio/miso#587]
**Describe the bug**
This is similar to https://github.com/dmjio/miso/issues/585.
If I modify the view code to use `Show Network.URI` instance the application hangs on start up.
Change for reference: https://github.com/niteria/miso-isomorphic-example/commit/3e9eaa41c9943db01d8d088d8a00391181d80c1d

**To Reproduce**
```
git clone https://github.com/niteria/miso-isomorphic-example && cd miso-isomorphic-example
git checkout network-uri-inconsistent
(cd $(nix-build) && bin/server)
# look at localhost:3003/flipped or localhost:3003/ in the browser, doesn't work anymore. /flipped better illustrates the problem
```

Message from the browser console:
```
Could not copy DOM into virtual DOM, falling back to diff
```

**Expected behavior**
Normal behavior from the example app, with extra text somewhere.

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser: Firefox
 - Version: 76.0.1

**Additional context**
I modified the app to use `Miso.startApp` instead of `Miso.miso` like so: https://github.com/niteria/miso-isomorphic-example/commit/d8a00d97238868dcc74bd7e178535d6b8c9d4cc3.

Running the code you can see that the browser `Show`s the flipped route as `http://localhost:3003/flipped` and the server `Show`s it as `flipped`.

**Comment by dmjio** [comment]
this should be fixed since the node collapse, re-open if not.
