### ISSUE TITLE
Diagnostic info when Miso.miso fails

### ISSUE THREAD

**Issue by niteria** [dmjio/miso#588]
**Is your feature request related to a problem? Please describe.**
This is based on my experience diagnosing #585 and #587.

When a framework user makes an error and the view renders inconsistently between the server and the client in an isomorphic app the only feedback that the user gets is some errors in the console.

From my short experience, it's quite easy to introduce such a bug, so it'd be nice to have more diagnostic info. 

**Describe the solution you'd like**
I think there could be a flag to `Miso.miso` that makes it perform a sanity check on start-up, basically rerendering the view with the model and checking if that's what was shipped from the server. Perhaps the diffing algorithm can be used to print the difference to the console.

**Describe alternatives you've considered**
I only had a brief look at the diffing code, so I might be wrong about this. From what I understand the diffing algorithm assumes that all the DOM nodes rendered with the old model exist. Perhaps it can print some diagnostics when that assumption is broken.

I'm a bit more skeptical of this because it'd an ongoing cost of extra checks instead of a one-time check at startup with the solution proposed in the previous section.

**Comment by dmjio** [comment]
@niteria it should fallback to rendering everything if it determines the view can't render, and `warn` about doing so.

https://github.com/dmjio/miso/blob/master/jsbits/isomorphic.js#L6

Which version of miso are you using?

**Comment by niteria** [comment]
I'm a bit confused then.
The reproducer for #585 used miso `1.5.2` which has an exact same definition for that function.

If I understand correctly the only problem there was that the server sent HTML that was interpreted as two `<br>` tags instead of one. But the console didn't print `"Could not copy DOM into virtual DOM, falling back to diff"` and the app crashed in the `walk` function.

I see that I incorrectly assumed that the `walk` function needs the DOM to agree with the virtual tree created from the Model on the JS side.

If I discard that assumption then going back to the crash in #585 `walk` crashed in:
https://github.com/dmjio/miso/blob/master/jsbits/isomorphic.js#L32, `domChild.nodeType` (sorry the stack trace from #585 had variable names that went through the minimizer).

So at that point in time for the node that `walk` was processing there were fewer DOM nodes than the VDOM nodes.

That makes sense, we were processing this DOM:
```
<body data-gr-c-s-loaded="true"><div><div><button>-</button>0<br><br><button>+</button></div><button>Go to /flipped</button></div></body>
```

And the VDOM was:
```
<body data-gr-c-s-loaded="true"><div><div><button>-</button>0<br><button>+</button></div><button>Go to /flipped</button></div></body>
```

At some point we called `walk` with DOM=`<br>` and VDOM=`<button>+</button>`.
DOM has 0 children while VDOM has 1.
The access at https://github.com/dmjio/miso/blob/master/jsbits/isomorphic.js#L30 gives us `undefined`, hence the crash.

**Comment by niteria** [comment]
I see that we ignore the return value of `walk` here https://github.com/dmjio/miso/blob/master/jsbits/isomorphic.js#L50, is that intended?

**Comment by dmjio** [comment]
https://github.com/dmjio/miso/commit/55ef457655f4ceefecef74ee3c1e381272a85768

**Comment by dmjio** [comment]
Diagnostic info has been added via `logLevel`
