### ISSUE TITLE
Is there a way to insert HTML entities?

### ISSUE THREAD

**Issue by niteria** [dmjio/miso#590]
**Is your feature request related to a problem? Please describe.**

Is there a way to insert HTML entities like `&nbsp;`?
I think for most things I can use Unicode, but for completeness, it'd be nice to be able to use entities.

**Comment by niteria** [comment]
Looks I didn't search the issues hard enough the first time, Unicode is recommended.
https://github.com/dmjio/miso/issues/31

**Comment by coderfromhere** [comment]
Unicode is not enough, there are valid cases that require an API for pre-escaped markup like in [Blaze](https://hackage.haskell.org/package/blaze-markup-0.8.2.8/docs/Text-Blaze.html#v:preEscapedText).

**Comment by niteria** [comment]
@coderfromhere I added `style_` and `script_` tags using `textRaw` internal in https://github.com/dmjio/miso/pull/601

It's not exactly what you want, but maybe it's a push in the right direction.
