### ISSUE TITLE
Error while using (html) file input on Safari (13.1.1)

### ISSUE THREAD

**Issue by kahlil29** [dmjio/miso#599]
**Describe the bug**
Html file input does not work in Safari (throws an error in the console, when inspected) 
The file picker dialog opens up and allows you to pick a file but then after that throws an error : 
```
uncaught exception in Haskell thread: TypeError: Type error
objectToJSON@file:///nix/store/9yv7j8p1jnpl6swc4r5yfzsgj2fdxlmd-app-0.1.0.0/bin/app.jsexe/lib.js:2082:19
h$$U9@file:///nix/store/9yv7j8p1jnpl6swc4r5yfzsgj2fdxlmd-app-0.1.0.0/bin/app.jsexe/out.js:31663:33
h$runThreadSlice@file:///nix/store/9yv7j8p1jnpl6swc4r5yfzsgj2fdxlmd-app-0.1.0.0/bin/app.jsexe/rts.js:8276:12
h$runThreadSliceCatch@file:///nix/store/9yv7j8p1jnpl6swc4r5yfzsgj2fdxlmd-app-0.1.0.0/bin/app.jsexe/rts.js:8239:28
h$mainLoop@file:///nix/store/9yv7j8p1jnpl6swc4r5yfzsgj2fdxlmd-app-0.1.0.0/bin/app.jsexe/rts.js:8232:30
file:///nix/store/9yv7j8p1jnpl6swc4r5yfzsgj2fdxlmd-app-0.1.0.0/bin/app.jsexe/rts.js:2459:30
runIfPresent@file:///nix/store/9yv7j8p1jnpl6swc4r5yfzsgj2fdxlmd-app-0.1.0.0/bin/app.jsexe/rts.js:2478:25
onGlobalMessage@file:///nix/store/9yv7j8p1jnpl6swc4r5yfzsgj2fdxlmd-app-0.1.0.0/bin/app.jsexe/rts.js:2526:29
```
The same code/page works fine on Chrome and Firefox

**To Reproduce**
Use a file input like: 
```
div_ 
            [class_ "custom-file"]
            [
              input_ [ type_ "file"
                      , class_ "custom-file-input"
                      , id_ fileInputId
                      , onChange FileSelected
                      ]
            , label_ [ class_ "custom-file-label"
                     , for_ fileInputId
                     ]
                     ["Choose a Food Image"]
            ]
```

**Expected behavior**
There should not be an error (the program should run fine)

**Screenshots**
![image](https://user-images.githubusercontent.com/8135917/85227262-f8818100-b40e-11ea-9a75-82cc99977403.png)
(In the screenshot, I tried uploading a file twice hence the error has been shown twice)

**Desktop (please complete the following information):**
 - OS: MacOS Catalina
 - Browser Safari 
 - Version 13.1.1

Also happens on safari on iOS 
(Works fine on chrome and firefox)

Could this be related to #453  ?

**Comment by dmjio** [comment]
@kahlil29 yea it should be fixed in `1.5.2.0`, https://github.com/dmjio/miso/commit/f4cc27ec877c0ef53954532e1047ca861dbbc86a. Can you call `ghcjs-pkg list miso` and see which version you're on?

**Comment by kahlil29** [comment]
@dmjio It returns a `command not found`. 
I'm a bit new to nix, but I've installed everything through `nix` based on the instructions in the README. 
Is there any other command I can run to verify the version of miso?

**Comment by kahlil29** [comment]
Okay I managed to do it after getting into `nix-shell` 
It's `1.3.0.0`
I'm guessing I can specify a specific version in the cabal file right? Let me try to do that.

**Comment by dmjio** [comment]
@kahlil29 we'll probably need to update your hash of miso in nix, this will pull in the latest version.

```nix
with (import (builtins.fetchTarball {
  url = "https://github.com/dmjio/miso/archive/afe2536b08c7bea5267b1e7b0121c786209dcd77.tar.gz";
  sha256 = "1rma6j7n53k6m1jqidrpn1g7nx38klgak6waj0r2zw0m3c98b3gc";
}) {});
pkgs.haskell.packages.ghcjs.callCabal2nix "app" ./. {}
```

**Comment by dmjio** [comment]
I'll bump the docs to reflect this.

**Comment by kahlil29** [comment]
Ah yes yes, apologies. I'm quite the `nix` noob. 
It works now, thanks a lot @dmjio 
It's really nice and refreshing when library authors and maintainers are super prompt and helpful 😄 
Also I've wanted to use Miso for almost 2+ years now and finally got into it for a small project at work. 
It's quite good, so far 🎉  Great effort and keep it up! 

Let me know if you need any help with that docs/README change.

**Comment by dmjio** [comment]
@kahlil29 Awesome. Thanks for the kind words :) glad to hear you're using it at work. Would love to have you (and your coworkers) in the commit history. If you wanted to update the `README.md` and sample app nix files to reflect the latest miso hashes and rev I'd gladly merge.

```nix
with (import (builtins.fetchTarball {
  url = "https://github.com/dmjio/miso/archive/afe2536b08c7bea5267b1e7b0121c786209dcd77.tar.gz";
  sha256 = "1rma6j7n53k6m1jqidrpn1g7nx38klgak6waj0r2zw0m3c98b3gc";
}) {});
pkgs.haskell.packages.ghcjs.callCabal2nix "app" ./. {}
```

**Comment by kahlil29** [comment]
@dmjio That would be great. Will make the changes and raise the PR 👍
