### ISSUE TITLE
Update Miso version in provided nix package

### ISSUE THREAD

**Issue by rowanG077** [dmjio/miso#602]
**Describe the bug**
Due to https://github.com/dmjio/miso/pull/591 being merged, there now is a log level paramater in the `App`. The canonical [example](https://github.com/dmjio/miso#sample-application) and the other examples have been updated to include the log level. But the provided nix package doesn't include this change yet. This results in the quick start not compiling if a user follows the steps with nix.
 
**To Reproduce**
1. Follow the Quick start.

**Expected behavior**
A compiling/working sample application.

**Comment by dmjio** [comment]
Thank you, will fix.

**Comment by dmjio** [comment]
https://github.com/dmjio/miso/commit/1c6b8b4515909e98003b2ddb42b4b005cdf5e710
