### ISSUE TITLE
Multiple class_ or classlist_ attributes differ from ELM

### ISSUE THREAD

**Issue by developandplay** [dmjio/miso#606]
**Describe the bug**
I have run into the issue of applying multiple class_ or classlist_ attributes not working like in ELM. In Miso just one class/classlist attribute gets applied.

**To Reproduce**
Simple example:
`button_ [class_ "test1", class_ "test2"] []`
results in `<button class="test2"></button>`

**Expected behavior**
The [standard behavior](https://package.elm-lang.org/packages/elm/html/latest/Html-Attributes#class) in ELM is to apply all class or classlist attributes.
So the example would result in `<button class="test1 test2"></button>`

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser: Chrome

**Additional context**
I'm trying to port material design components from ELM to Miso  **https://github.com/aforemny/material-components-web-elm**. This works reasonably well due to Misos and ELMs similar syntax. I'm now done with porting a first test component (simple button) except for this issue.
As a work around I tried writing a `createClasses :: [Attribute action] -> [Attribute action]` function. This function would take `[Attribute action]` which might contain class attributes and create a `[Attribute action]` that just contains one classlist. However I wasn't able to perform any pattern matching on the Attributes as the constructor is internal.
In case I missed something super obvious I'm sorry. I'm a beginner with Haskell and Elm who just learned about them in a university course.

**Comment by dmjio** [comment]
https://github.com/dmjio/miso/pull/607, this PR should fix that issue.

**Comment by dmjio** [comment]
@developandplay porting material design components to miso would be awesome!
