### ISSUE TITLE
Adding event handler doesn't work for custom events

### ISSUE THREAD

**Issue by developandplay** [dmjio/miso#609]
**Describe the bug**\
[Elms](https://package.elm-lang.org/packages/elm/html/latest/Html-Events#on) `on` function works with custom events while [Misos](https://hackage.haskell.org/package/miso-1.7.1.0/docs/Miso-Html-Event.html#g:1) `on` function only seems to work for some events.

**To Reproduce**
Attach the Attribute `on "myEvent" emptyDecoder$\()->action` to an element. It then doesn't appear under Chromes Event Listeners menu and if it is invoked then `action` does not get executed.

**Expected behavior**
Misos `on` function supports custom events.
https://developer.mozilla.org/en-US/docs/Web/API/CustomEvent/CustomEvent

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser: Chrome

**Additional context**
Creating Material Design Components for Miso. Google's predefined javascript creates custom events e.g. `MDCDialog:closed` to indicate UI changes to the frameworks.

Again if I missed something obvious I'm happy to hear about that.

**Comment by dmjio** [comment]
@developandplay `miso`'s `on` function only listens on the events that are delegated, by default that is what is in `defaultEvents`. If material has its own javascript, you will more than likely need to reimplement it in Haskell. Similar to what bootstrap react has done, reimplementing bootstraps js w/ react components.

**Comment by developandplay** [comment]
I see...
While this re-implementation is definitely possible there would be two major drawbacks:

1. Currently I can currently simply reuse the elm-code (adjusted to Haskell and Miso) and javascript (original) from elm's material components (which includes Google's javascript). If I change the architecture that won't be possible to the same extent.
2. To be recognized as an [official implementation](https://material.io/develop/web/docs/framework-integration) from Google you need to reuse their [architecture](https://github.com/material-components/material-components-web/blob/v6.0.0/docs/code/architecture.md).

**Comment by developandplay** [comment]
As an intermediate solution would it be possible to specify additional events to be delegated?

**Comment by dmjio** [comment]
You can try adding google's events to the default map that miso has yes.

I would look at Elm's implementation and recreate each component like they have done.
https://github.com/aforemny/material-components-web-elm/tree/4.0.0/src/Material

**Comment by developandplay** [comment]
Yes that's what I'm currently doing. So maybe I did a bad job at communicating that.
Here is where I have run into the issue:
https://github.com/developandplay/material-components-web-miso/blob/779bed32c49323226fb79adc7eb473b3f7dbe4dd/sample-app-jsaddle/Material/Dialog.hs#L118
Which corresponds to:
https://github.com/aforemny/material-components-web-elm/blob/c022599fcc3a9dc74e171151351b6d8e8da58d15/src/Material/Dialog.elm#L174

**Comment by dmjio** [comment]
Can you try adding to `defaultEvents` https://github.com/developandplay/material-components-web-miso/blob/master/sample-app-jsaddle/Main.hs#L62

```haskell
  where
      events = M.insert "MDCDialog:close" False defaultEvents
```

**Comment by developandplay** [comment]
Great thank you!
With
```
events = M.insert "MDCDialog:close" True defaultEvents
```
the custom event works perfectly.

**Comment by dmjio** [comment]
nice! @developandplay, looking forward to your project.
