### ISSUE TITLE
Create shorthand for style_ with single element Map

### ISSUE THREAD

**Issue by developandplay** [dmjio/miso#611]
**Is your feature request related to a problem? Please describe.**
The most common use case for `style_` seems to be setting one style property. When setting the style with Miso I always need to include Data.Map and write M.singleton.

**Describe the solution you'd like**
Add a second `style_` function with type `MisoString -> MisoString -> Attribute action` that works as a shorthand for `style_` with single element Maps. Similar to how Elms `style` function works.

**Describe alternatives you've considered**
It's possible to write this function for myself. However I would assume this use case to be very popular as it seems to be the standard implementation in Elm.

**Additional context**
I'm porting Material Design Components from Elm to Miso. Some elements have inline styles attached to them.

**Comment by dmjio** [comment]
If you wanted to add

```haskell
styleInline_ :: MisoString -> Attribute action
styleInline_ = textProp "style"
```

I'd accept.

```haskell
view m = div_ [ styleInline_ "background-color:red;color:blue;" ] [ "foo" ]

**Comment by developandplay** [comment]
Great. I will figure out how to build the Miso project with my changes the next few days.
Currently I'm just using your .tar.gz...

**Comment by dmjio** [comment]
`nix-build` should work.
