### ISSUE TITLE
Declarative Dynamic Subscriptions: Automatically manage subscriptions based on model state.

### ISSUE THREAD

**Issue by dhruvio** [dmjio/miso#622]
In Elm, `subscriptions` are defined as a function that "declares" subscriptions based on the application's current `model` state. 

```elm
subscriptions : model -> Sub msg
```

This enables developers to define subscriptions that are *dynamically* activated and deactivated based on the application's state. For example, I might want to subscribe to messages from a WebSocket server if the user has opened a view to communicate with a support team via a chat feature. However, I don't want to subscribe to the WebSocket server if the user is not using that feature.

I was able to (briefly) review some of the Miso source code, and it seems like it would be possible to use `effectSub` to dynamically initiate a new subscription. However, it is not clear how the developer would "unsubscribe" from it.

In Elm, this is possible because the above `subscriptions` function is called each time application state has been updated, allowing developers to "declare" which subscriptions are still active by including them in the return value.

In the event that I have misunderstood the source code, **does Miso support this kind of behaviour already?** If not, I would like to request this feature as I believe it would create a lot of value for developers.

@dmjio I am happy to discuss this feature in more depth over an audio/video call if this seems like a worthwhile pursuit to you.

**Comment by dmjio** [comment]
Please re-open if `miso` does not current satisfy dynamic subscriptions to your liking.
