### ISSUE TITLE
Expired certificates for example pages

### ISSUE THREAD

**Issue by rycee** [dmjio/miso#623]
**Describe the bug**

The certificates for

- https://todo-mvc.haskell-miso.org/
- https://mario.haskell-miso.org/
- https://flatris.haskell-miso.org/

have expired and thus trigger browser warnings.

**Screenshots**

![expired-cert](https://user-images.githubusercontent.com/798147/92263603-2b4ef780-eedd-11ea-8f56-a0183ea45a48.png)

**Desktop (please complete the following information):**
 - Browser Firefox

**Comment by dmjio** [comment]
@rycee the links on the README now point to the non-HTTPS ones.

**Comment by rycee** [comment]
Sorry, I missed saying that I got the HTTPS links from https://haskell-miso.org/examples.

**Comment by dmjio** [comment]
Ah, yea I need to change that, thanks.
