### ISSUE TITLE
i need help correctly implementing: `pkgs.haskell.packages.ghcjs.callCabal2nix "app" ./. {}` generically in my: (lorri+direnv+emacs-direnv) configuration:

### ISSUE THREAD

**Issue by zeta-00** [dmjio/miso#624]
hello there, the setup that i'm currently using is: (lorri+direnv+emacs-direnv), I got miso working with that setup in the shell.nix file without too much problems, but i'm not sure how to generically place: `pkgs.haskell.packages.ghcjs.callCabal2nix "app" ./. {}`(https://github.com/dmjio/miso#nix) in this shell.nix file ?

if you could take a look at my shell.nix file and help fix my issue, thanks.

note: most of miso's pkgs are broken(in nixos 20.03 nix channel), that's why I have them commented out.

pasted below is the shell.nix file that i'm using:

```nix
{ pkgs ? import <nixpkgs> {} }:

with pkgs;
mkShell
  {
    buildInputs = with pkgs;
      [
        (haskell.packages.ghc865.ghcWithHoogle (hpkgs: with hpkgs;
          [
            ghcid
            # ghcide
            cabal-install

            # web framework:
            miso
            # classy-miso
            # miso-action-logger
            # miso-examples

            # (haskell.packages.ghcjs.callCabal2nix "app" ./. {})

          ]))
        
        # ghcide-nix installation:
        (import (builtins.fetchTarball "https://github.com/cachix/ghcide-nix/tarball/master") {}).ghcide-ghc865
        
        bashInteractive
      ];

        shellHook =
      ''
         export EDITOR=emacs;

         export HIE_HOOGLE_DATABASE="$(cat $(which hoogle) | sed -n -e 's|.*--database \\(.*\\.hoo\\).*|\\1|p')";
         export NIX_GHC="$(which ghc)";
         export NIX_GHCPKG="$(which ghc-pkg)";
         export NIX_GHC_DOCDIR="$NIX_GHC/../../share/doc/ghc/html";
         export NIX_GHC_LIBDIR="$(ghc --print-libdir)";
      '';
  }

**Comment by zeta-00** [comment]
here's the error that the nix-shell command is returning:

[zeta@nixos:/miso]$ nix-shell --show-trace
building '/nix/store/nxbcirqiiy88k1684x6n62fddg9mznnl-cabal2nix-app.drv'...
installing
error: creating directory '/nix/var': Permission denied
error: creating directory '/nix/var': Permission denied
** need a revision for VCS when the hash is given. skipping.
** need a revision for VCS when the hash is given. skipping.
** need a revision for VCS when the hash is given. skipping.
** need a revision for VCS when the hash is given. skipping.
cabal2nix: user error (Failed to fetch source. Does this source exist? Source {sourceUrl = "/nix/store/g95h9rsjgv3qfk19rz0q1iyhnv70vkfy-miso", sourceRevision = "", sourceHash = Guess "", sourceCabalDir = ""})
builder for '/nix/store/nxbcirqiiy88k1684x6n62fddg9mznnl-cabal2nix-app.drv' failed with exit code 1
error: while evaluating the attribute 'buildInputs' of the derivation 'nix-shell' at /nix/store/5bj816i9wzx5a4v6hcv5r9g3iyvrdk7b-nixos-20.03.3021.5659cb448e9/nixos/pkgs/build-support/mkshell/default.nix:28:3:
while evaluating 'getOutput' at /nix/store/5bj816i9wzx5a4v6hcv5r9g3iyvrdk7b-nixos-20.03.3021.5659cb448e9/nixos/lib/attrsets.nix:464:23, called from undefined position:
while evaluating anonymous function at /nix/store/5bj816i9wzx5a4v6hcv5r9g3iyvrdk7b-nixos-20.03.3021.5659cb448e9/nixos/pkgs/stdenv/generic/make-derivation.nix:142:17, called from undefined position:
while evaluating 'ghcWithHoogle' at /nix/store/5bj816i9wzx5a4v6hcv5r9g3iyvrdk7b-nixos-20.03.3021.5659cb448e9/nixos/pkgs/development/haskell-modules/make-package-set.nix:248:21, called from /home/zeta/coding-projects/haskell-web/miso/shell.nix:8:10:
while evaluating 'withPackages' at /nix/store/5bj816i9wzx5a4v6hcv5r9g3iyvrdk7b-nixos-20.03.3021.5659cb448e9/nixos/pkgs/development/haskell-modules/make-package-set.nix:116:18, called from /nix/store/5bj816i9wzx5a4v6hcv5r9g3iyvrdk7b-nixos-20.03.3021.5659cb448e9/nixos/pkgs/development/haskell-modules/make-package-set.nix:254:10:
while evaluating 'callPackageWith' at /nix/store/5bj816i9wzx5a4v6hcv5r9g3iyvrdk7b-nixos-20.03.3021.5659cb448e9/nixos/lib/customisation.nix:117:35, called from /nix/store/5bj816i9wzx5a4v6hcv5r9g3iyvrdk7b-nixos-20.03.3021.5659cb448e9/nixos/pkgs/development/haskell-modules/make-package-set.nix:116:28:
while evaluating 'makeOverridable' at /nix/store/5bj816i9wzx5a4v6hcv5r9g3iyvrdk7b-nixos-20.03.3021.5659cb448e9/nixos/lib/customisation.nix:67:24, called from /nix/store/5bj816i9wzx5a4v6hcv5r9g3iyvrdk7b-nixos-20.03.3021.5659cb448e9/nixos/lib/customisation.nix:121:8:
while evaluating anonymous function at /nix/store/5bj816i9wzx5a4v6hcv5r9g3iyvrdk7b-nixos-20.03.3021.5659cb448e9/nixos/pkgs/development/haskell-modules/with-packages-wrapper.nix:1:1, called from /nix/store/5bj816i9wzx5a4v6hcv5r9g3iyvrdk7b-nixos-20.03.3021.5659cb448e9/nixos/lib/customisation.nix:69:16:
while evaluating 'closePropagation' at /nix/store/5bj816i9wzx5a4v6hcv5r9g3iyvrdk7b-nixos-20.03.3021.5659cb448e9/nixos/lib/deprecated.nix:160:22, called from /nix/store/5bj816i9wzx5a4v6hcv5r9g3iyvrdk7b-nixos-20.03.3021.5659cb448e9/nixos/pkgs/development/haskell-modules/with-packages-wrapper.nix:45:57:
while evaluating 'uniqList' at /nix/store/5bj816i9wzx5a4v6hcv5r9g3iyvrdk7b-nixos-20.03.3021.5659cb448e9/nixos/lib/deprecated.nix:91:14, called from /nix/store/5bj816i9wzx5a4v6hcv5r9g3iyvrdk7b-nixos-20.03.3021.5659cb448e9/nixos/lib/deprecated.nix:160:29:
while evaluating 'go' at /nix/store/5bj816i9wzx5a4v6hcv5r9g3iyvrdk7b-nixos-20.03.3021.5659cb448e9/nixos/lib/deprecated.nix:92:18, called from /nix/store/5bj816i9wzx5a4v6hcv5r9g3iyvrdk7b-nixos-20.03.3021.5659cb448e9/nixos/lib/deprecated.nix:98:8:
while evaluating 'innerClosePropagation' at /nix/store/5bj816i9wzx5a4v6hcv5r9g3iyvrdk7b-nixos-20.03.3021.5659cb448e9/nixos/lib/deprecated.nix:143:32, called from /nix/store/5bj816i9wzx5a4v6hcv5r9g3iyvrdk7b-nixos-20.03.3021.5659cb448e9/nixos/lib/deprecated.nix:160:52:
while evaluating 'innerClosePropagation' at /nix/store/5bj816i9wzx5a4v6hcv5r9g3iyvrdk7b-nixos-20.03.3021.5659cb448e9/nixos/lib/deprecated.nix:143:32, called from /nix/store/5bj816i9wzx5a4v6hcv5r9g3iyvrdk7b-nixos-20.03.3021.5659cb448e9/nixos/lib/deprecated.nix:151:21:
while evaluating 'uniqList' at /nix/store/5bj816i9wzx5a4v6hcv5r9g3iyvrdk7b-nixos-20.03.3021.5659cb448e9/nixos/lib/deprecated.nix:91:14, called from /nix/store/5bj816i9wzx5a4v6hcv5r9g3iyvrdk7b-nixos-20.03.3021.5659cb448e9/nixos/lib/deprecated.nix:153:24:
while evaluating 'go' at /nix/store/5bj816i9wzx5a4v6hcv5r9g3iyvrdk7b-nixos-20.03.3021.5659cb448e9/nixos/lib/deprecated.nix:92:18, called from /nix/store/5bj816i9wzx5a4v6hcv5r9g3iyvrdk7b-nixos-20.03.3021.5659cb448e9/nixos/lib/deprecated.nix:98:8:
while evaluating 'go' at /nix/store/5bj816i9wzx5a4v6hcv5r9g3iyvrdk7b-nixos-20.03.3021.5659cb448e9/nixos/lib/deprecated.nix:92:18, called from /nix/store/5bj816i9wzx5a4v6hcv5r9g3iyvrdk7b-nixos-20.03.3021.5659cb448e9/nixos/lib/deprecated.nix:97:27:
while evaluating 'go' at /nix/store/5bj816i9wzx5a4v6hcv5r9g3iyvrdk7b-nixos-20.03.3021.5659cb448e9/nixos/lib/deprecated.nix:92:18, called from /nix/store/5bj816i9wzx5a4v6hcv5r9g3iyvrdk7b-nixos-20.03.3021.5659cb448e9/nixos/lib/deprecated.nix:97:27:
while evaluating 'go' at /nix/store/5bj816i9wzx5a4v6hcv5r9g3iyvrdk7b-nixos-20.03.3021.5659cb448e9/nixos/lib/deprecated.nix:92:18, called from /nix/store/5bj816i9wzx5a4v6hcv5r9g3iyvrdk7b-nixos-20.03.3021.5659cb448e9/nixos/lib/deprecated.nix:97:27:
while evaluating 'go' at /nix/store/5bj816i9wzx5a4v6hcv5r9g3iyvrdk7b-nixos-20.03.3021.5659cb448e9/nixos/lib/deprecated.nix:92:18, called from /nix/store/5bj816i9wzx5a4v6hcv5r9g3iyvrdk7b-nixos-20.03.3021.5659cb448e9/nixos/lib/deprecated.nix:97:27:
while evaluating 'go' at /nix/store/5bj816i9wzx5a4v6hcv5r9g3iyvrdk7b-nixos-20.03.3021.5659cb448e9/nixos/lib/deprecated.nix:92:18, called from /nix/store/5bj816i9wzx5a4v6hcv5r9g3iyvrdk7b-nixos-20.03.3021.5659cb448e9/nixos/lib/deprecated.nix:97:27:
while evaluating 'go' at /nix/store/5bj816i9wzx5a4v6hcv5r9g3iyvrdk7b-nixos-20.03.3021.5659cb448e9/nixos/lib/deprecated.nix:92:18, called from /nix/store/5bj816i9wzx5a4v6hcv5r9g3iyvrdk7b-nixos-20.03.3021.5659cb448e9/nixos/lib/deprecated.nix:97:27:
while evaluating 'go' at /nix/store/5bj816i9wzx5a4v6hcv5r9g3iyvrdk7b-nixos-20.03.3021.5659cb448e9/nixos/lib/deprecated.nix:92:18, called from /nix/store/5bj816i9wzx5a4v6hcv5r9g3iyvrdk7b-nixos-20.03.3021.5659cb448e9/nixos/lib/deprecated.nix:97:27:
while evaluating 'go' at /nix/store/5bj816i9wzx5a4v6hcv5r9g3iyvrdk7b-nixos-20.03.3021.5659cb448e9/nixos/lib/deprecated.nix:92:18, called from /nix/store/5bj816i9wzx5a4v6hcv5r9g3iyvrdk7b-nixos-20.03.3021.5659cb448e9/nixos/lib/deprecated.nix:97:27:
while evaluating 'go' at /nix/store/5bj816i9wzx5a4v6hcv5r9g3iyvrdk7b-nixos-20.03.3021.5659cb448e9/nixos/lib/deprecated.nix:92:18, called from /nix/store/5bj816i9wzx5a4v6hcv5r9g3iyvrdk7b-nixos-20.03.3021.5659cb448e9/nixos/lib/deprecated.nix:97:27:
while evaluating 'go' at /nix/store/5bj816i9wzx5a4v6hcv5r9g3iyvrdk7b-nixos-20.03.3021.5659cb448e9/nixos/lib/deprecated.nix:92:18, called from /nix/store/5bj816i9wzx5a4v6hcv5r9g3iyvrdk7b-nixos-20.03.3021.5659cb448e9/nixos/lib/deprecated.nix:97:27:
while evaluating 'go' at /nix/store/5bj816i9wzx5a4v6hcv5r9g3iyvrdk7b-nixos-20.03.3021.5659cb448e9/nixos/lib/deprecated.nix:92:18, called from /nix/store/5bj816i9wzx5a4v6hcv5r9g3iyvrdk7b-nixos-20.03.3021.5659cb448e9/nixos/lib/deprecated.nix:97:27:
while evaluating 'go' at /nix/store/5bj816i9wzx5a4v6hcv5r9g3iyvrdk7b-nixos-20.03.3021.5659cb448e9/nixos/lib/deprecated.nix:92:18, called from /nix/store/5bj816i9wzx5a4v6hcv5r9g3iyvrdk7b-nixos-20.03.3021.5659cb448e9/nixos/lib/deprecated.nix:97:27:
while evaluating 'go' at /nix/store/5bj816i9wzx5a4v6hcv5r9g3iyvrdk7b-nixos-20.03.3021.5659cb448e9/nixos/lib/deprecated.nix:92:18, called from /nix/store/5bj816i9wzx5a4v6hcv5r9g3iyvrdk7b-nixos-20.03.3021.5659cb448e9/nixos/lib/deprecated.nix:97:27:
while evaluating 'go' at /nix/store/5bj816i9wzx5a4v6hcv5r9g3iyvrdk7b-nixos-20.03.3021.5659cb448e9/nixos/lib/deprecated.nix:92:18, called from /nix/store/5bj816i9wzx5a4v6hcv5r9g3iyvrdk7b-nixos-20.03.3021.5659cb448e9/nixos/lib/deprecated.nix:97:27:
while evaluating 'go' at /nix/store/5bj816i9wzx5a4v6hcv5r9g3iyvrdk7b-nixos-20.03.3021.5659cb448e9/nixos/lib/deprecated.nix:92:18, called from /nix/store/5bj816i9wzx5a4v6hcv5r9g3iyvrdk7b-nixos-20.03.3021.5659cb448e9/nixos/lib/deprecated.nix:97:27:
while evaluating 'go' at /nix/store/5bj816i9wzx5a4v6hcv5r9g3iyvrdk7b-nixos-20.03.3021.5659cb448e9/nixos/lib/deprecated.nix:92:18, called from /nix/store/5bj816i9wzx5a4v6hcv5r9g3iyvrdk7b-nixos-20.03.3021.5659cb448e9/nixos/lib/deprecated.nix:97:27:
while evaluating 'go' at /nix/store/5bj816i9wzx5a4v6hcv5r9g3iyvrdk7b-nixos-20.03.3021.5659cb448e9/nixos/lib/deprecated.nix:92:18, called from /nix/store/5bj816i9wzx5a4v6hcv5r9g3iyvrdk7b-nixos-20.03.3021.5659cb448e9/nixos/lib/deprecated.nix:97:27:
while evaluating 'go' at /nix/store/5bj816i9wzx5a4v6hcv5r9g3iyvrdk7b-nixos-20.03.3021.5659cb448e9/nixos/lib/deprecated.nix:92:18, called from /nix/store/5bj816i9wzx5a4v6hcv5r9g3iyvrdk7b-nixos-20.03.3021.5659cb448e9/nixos/lib/deprecated.nix:97:27:
while evaluating 'go' at /nix/store/5bj816i9wzx5a4v6hcv5r9g3iyvrdk7b-nixos-20.03.3021.5659cb448e9/nixos/lib/deprecated.nix:92:18, called from /nix/store/5bj816i9wzx5a4v6hcv5r9g3iyvrdk7b-nixos-20.03.3021.5659cb448e9/nixos/lib/deprecated.nix:97:27:
while evaluating 'go' at /nix/store/5bj816i9wzx5a4v6hcv5r9g3iyvrdk7b-nixos-20.03.3021.5659cb448e9/nixos/lib/deprecated.nix:92:18, called from /nix/store/5bj816i9wzx5a4v6hcv5r9g3iyvrdk7b-nixos-20.03.3021.5659cb448e9/nixos/lib/deprecated.nix:97:27:
while evaluating 'go' at /nix/store/5bj816i9wzx5a4v6hcv5r9g3iyvrdk7b-nixos-20.03.3021.5659cb448e9/nixos/lib/deprecated.nix:92:18, called from /nix/store/5bj816i9wzx5a4v6hcv5r9g3iyvrdk7b-nixos-20.03.3021.5659cb448e9/nixos/lib/deprecated.nix:97:27:
while evaluating 'go' at /nix/store/5bj816i9wzx5a4v6hcv5r9g3iyvrdk7b-nixos-20.03.3021.5659cb448e9/nixos/lib/deprecated.nix:92:18, called from /nix/store/5bj816i9wzx5a4v6hcv5r9g3iyvrdk7b-nixos-20.03.3021.5659cb448e9/nixos/lib/deprecated.nix:97:27:
while evaluating 'callCabal2nix' at /nix/store/5bj816i9wzx5a4v6hcv5r9g3iyvrdk7b-nixos-20.03.3021.5659cb448e9/nixos/pkgs/development/haskell-modules/make-package-set.nix:216:32, called from /home/zeta/coding-projects/haskell-web/miso/shell.nix:20:14:
while evaluating 'callCabal2nixWithOptions' at /nix/store/5bj816i9wzx5a4v6hcv5r9g3iyvrdk7b-nixos-20.03.3021.5659cb448e9/nixos/pkgs/development/haskell-modules/make-package-set.nix:201:66, called from /nix/store/5bj816i9wzx5a4v6hcv5r9g3iyvrdk7b-nixos-20.03.3021.5659cb448e9/nixos/pkgs/development/haskell-modules/make-package-set.nix:216:38:
while evaluating 'overrideCabal' at /nix/store/5bj816i9wzx5a4v6hcv5r9g3iyvrdk7b-nixos-20.03.3021.5659cb448e9/nixos/pkgs/development/haskell-modules/lib.nix:37:24, called from /nix/store/5bj816i9wzx5a4v6hcv5r9g3iyvrdk7b-nixos-20.03.3021.5659cb448e9/nixos/pkgs/development/haskell-modules/make-package-set.nix:212:10:
while evaluating 'callPackageKeepDeriver' at /nix/store/5bj816i9wzx5a4v6hcv5r9g3iyvrdk7b-nixos-20.03.3021.5659cb448e9/nixos/pkgs/development/haskell-modules/make-package-set.nix:157:33, called from /nix/store/5bj816i9wzx5a4v6hcv5r9g3iyvrdk7b-nixos-20.03.3021.5659cb448e9/nixos/pkgs/development/haskell-modules/make-package-set.nix:212:25:
while evaluating 'overrideCabal' at /nix/store/5bj816i9wzx5a4v6hcv5r9g3iyvrdk7b-nixos-20.03.3021.5659cb448e9/nixos/pkgs/development/haskell-modules/lib.nix:37:24, called from /nix/store/5bj816i9wzx5a4v6hcv5r9g3iyvrdk7b-nixos-20.03.3021.5659cb448e9/nixos/pkgs/development/haskell-modules/make-package-set.nix:158:5:
while evaluating 'callPackage' at /nix/store/5bj816i9wzx5a4v6hcv5r9g3iyvrdk7b-nixos-20.03.3021.5659cb448e9/nixos/pkgs/development/haskell-modules/make-package-set.nix:114:22, called from /nix/store/5bj816i9wzx5a4v6hcv5r9g3iyvrdk7b-nixos-20.03.3021.5659cb448e9/nixos/pkgs/development/haskell-modules/make-package-set.nix:158:20:
while evaluating 'callPackageWithScope' at /nix/store/5bj816i9wzx5a4v6hcv5r9g3iyvrdk7b-nixos-20.03.3021.5659cb448e9/nixos/pkgs/development/haskell-modules/make-package-set.nix:74:37, called from /nix/store/5bj816i9wzx5a4v6hcv5r9g3iyvrdk7b-nixos-20.03.3021.5659cb448e9/nixos/pkgs/development/haskell-modules/make-package-set.nix:114:28:
while evaluating 'makeOverridable' at /nix/store/5bj816i9wzx5a4v6hcv5r9g3iyvrdk7b-nixos-20.03.3021.5659cb448e9/nixos/lib/customisation.nix:67:24, called from /nix/store/5bj816i9wzx5a4v6hcv5r9g3iyvrdk7b-nixos-20.03.3021.5659cb448e9/nixos/pkgs/development/haskell-modules/make-package-set.nix:97:8:
while evaluating 'drvScope' at /nix/store/5bj816i9wzx5a4v6hcv5r9g3iyvrdk7b-nixos-20.03.3021.5659cb448e9/nixos/pkgs/development/haskell-modules/make-package-set.nix:87:18, called from /nix/store/5bj816i9wzx5a4v6hcv5r9g3iyvrdk7b-nixos-20.03.3021.5659cb448e9/nixos/lib/customisation.nix:69:16:
build of '/nix/store/nxbcirqiiy88k1684x6n62fddg9mznnl-cabal2nix-app.drv' failed

[zeta@nixos:/miso]$

**Comment by sorki** [comment]
Is there `app.cabal` present in the same dir as `shell.nix`?

**Comment by zeta-00** [comment]
@sorki , oh, ya, my directory structure is different than the one in miso's instructions:
[zeta@nixos:/miso]$ tree
.
├── app
│   ├── app.cabal
│   ├── default.nix
│   └── Main.hs
└── shell.nix

1 directory, 4 files

[zeta@nixos:/miso]$ 

making this change to my shell.nix file fixed the error:

`(haskell.packages.ghcjs.callCabal2nix "app" ./app/app.cabal {})`

thanks for the help !

also, after making this change and going into a nix-shell, other errors are being thrown, for some reason things are not being found?

the paste is too lengthy, so here's some of what nix-shell returned:

/nix/store/hrkc2sf2883l16d5yq3zg0y339kfw4xv-binutils-2.31.1/bin/strip
Using tar found on system at:
/nix/store/g7dr83wnkx4gxa5ykcljc5jg04416z60-gnutar-1.32/bin/tar
No uhc found
[1 of 2] Compiling Language.Haskell.TH.Datatype.Internal ( src/Language/Haskell/TH/Datatype/Internal.hs, dist/build/Language/Haskell/TH/Datatype/Internal.js_o )
Preprocessing library for utf8-string-1.0.1.1..
[1 of 3] Compiling Data.Bits.Compat ( src-compat/Data/Bits/Compat.hs, dist/build/Data/Bits/Compat.js_o )
building
Building library for utf8-string-1.0.1.1..
Preprocessing library for doctest-0.16.2..
Building library for doctest-0.16.2..
Preprocessing library for unbounded-delays-0.1.1.0..
Building library for unbounded-delays-0.1.1.0..
[2 of 3] Compiling System.Random.SplitMix ( src/System/Random/SplitMix.hs, dist/build/System/Random/SplitMix.js_o )
[1 of 4] Compiling Control.Monad.Trans.Instances ( src/Control/Monad/Trans/Instances.hs, dist/build/Control/Monad/Trans/Instances.js_o )
[2 of 2] Compiling Language.Haskell.TH.Datatype ( src/Language/Haskell/TH/Datatype.hs, dist/build/Language/Haskell/TH/Datatype.js_o )
[1 of 2] Compiling Control.Concurrent.Thread.Delay ( Control/Concurrent/Thread/Delay.hs, dist/build/Control/Concurrent/Thread/Delay.js_o )
[2 of 6] Compiling Test.HUnit.Lang  ( src/Test/HUnit/Lang.hs, dist/build/Test/HUnit/Lang.js_o )
[1 of 5] Compiling Codec.Binary.UTF8.String ( Codec/Binary/UTF8/String.hs, dist/build/Codec/Binary/UTF8/String.js_o )
[2 of 4] Compiling Data.Functor.Classes.Generic.Internal ( generics/Data/Functor/Classes/Generic/Internal.hs, dist/build/Data/Functor/Classes/Generic/Internal.js_o )
[2 of 2] Compiling Control.Concurrent.Timeout ( Control/Concurrent/Timeout.hs, dist/build/Control/Concurrent/Timeout.js_o )
[ 1 of 16] Compiling GhcUtil          ( src/GhcUtil.hs, dist/build/GhcUtil.js_o )

src/GhcUtil.hs:10:1: error:
    Could not find module ‘GHC’
    Use -v to see a list of the files searched for.
   |
10 | import           GHC
   | ^^^^^^^^^^^^^^^^^^^^

[ 1 of 21] Compiling Data.Vector.Fusion.Util ( Data/Vector/Fusion/Util.hs, dist/build/Data/Vector/Fusion/Util.js_o )
src/GhcUtil.hs:11:1: error:
    Could not find module ‘DynFlags’
    Use -v to see a list of the files searched for.
   |
11 | import           DynFlags (gopt_set)
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

src/GhcUtil.hs:13:1: error:
    Could not find module ‘Panic’
    Use -v to see a list of the files searched for.
   |
13 | import           Panic (throwGhcException)
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

src/GhcUtil.hs:15:1: error:
    Could not find module ‘MonadUtils’
    Use -v to see a list of the files searched for.
   |
15 | import           MonadUtils (liftIO)
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

builder for '/nix/store/i74llxa73070zlr1rnn4r1s0wl803awv-doctest-0.16.2.drv' failed with exit code 1
cannot build derivation '/nix/store/lcg0v8x2v31mb17g85ksydnjp338kiig-http-types-0.12.3.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/j1vwd5izinbi5gci5g9zj7gn7z2dlxwq-servant-0.16.2.drv': 1 dependencies couldn't be built
building '/nix/store/4pzrch0dvxdbbwxd5cc67jcvlajagrp2-tf-random-0.5.drv'...
building '/nix/store/nk8l81136gz9z10i37p68v7bs4vw48cj-wcwidth-0.0.2.drv'...
building '/nix/store/j8higa9idy8hcy76vpjf4vb80ysw9y0d-xml-1.3.14.drv'...
cannot build derivation '/nix/store/pf88f0aw3fv7sm6dbdskfrzivjzb3d1k-miso-1.2.0.0.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/5cpn7n2rwlrw9m09fy165r82h36kq6gv-app-0.1.0.0.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/lbwxsmalkfa0d0rni5vr040m8y3f7pyl-ghc-8.6.5-with-packages.drv': 1 dependencies couldn't be built
error: build of '/nix/store/lbwxsmalkfa0d0rni5vr040m8y3f7pyl-ghc-8.6.5-with-packages.drv' failed

[zeta@nixos:/miso]$

**Comment by zeta-00** [comment]
@sorki , maybe it's because there's some version mismatches ? i'm not sure how to troubleshoot this error.

i'm using nixos 20.03 stable channel, and ghc865.

**Comment by zeta-00** [comment]
here's the current shell.nix channel with the dir/file path change:

{ pkgs ? import <nixpkgs> {} }:

with pkgs;
mkShell
  {
    buildInputs = with pkgs;
      [
        (haskell.packages.ghc865.ghcWithHoogle (hpkgs: with hpkgs;
          [
            ghcid
            # ghcide
            cabal-install

            # web framework
            miso
            # classy-miso
            # miso-action-logger
            # miso-examples

            (haskell.packages.ghcjs.callCabal2nix "app" ./app/app.cabal {})
          ]))
        
        # ghcide-nix installation:
        (import (builtins.fetchTarball "https://github.com/cachix/ghcide-nix/tarball/master") {}).ghcide-ghc865
        
        bashInteractive
      ];

        shellHook =
      ''
         export EDITOR=emacs;

         export HIE_HOOGLE_DATABASE="$(cat $(which hoogle) | sed -n -e 's|.*--database \\(.*\\.hoo\\).*|\\1|p')";
         export NIX_GHC="$(which ghc)";
         export NIX_GHCPKG="$(which ghc-pkg)";
         export NIX_GHC_DOCDIR="$NIX_GHC/../../share/doc/ghc/html";
         export NIX_GHC_LIBDIR="$(ghc --print-libdir)";
      '';
  }

**Comment by zeta-00** [comment]
@sorki , i tried:
with (import (builtins.fetchTarball {
  url = "https://github.com/dmjio/miso/archive/ea25964565074e73d4052b56b60b6e101fa08bc5.tar.gz";
  sha256 = "1yb9yvc0ln4yn1jk2k5kwwa1s32310abawz40yd8cqqkm1z7w6wg";
}) {});
instead of miso from nixpkgs, and the same error is still being returned ?

i can build a miso project fine, but it throws errors when i try to set it up with my (lorri+direnv+emacs-direnv) setup.

**Comment by dmjio** [comment]
I'd ask on #nixos on libera.chat
