### ISSUE TITLE
Miso setup with vscode haskell-language-server

### ISSUE THREAD

**Issue by clojj** [dmjio/miso#628]
Is it possible to provide the following ?

Open vscode in sample-app-jsaddle directory and have haskell-language-server plugin (vscode) working... so having refactorings, type docs, Go To definition etc.

Other nix enabled project with ghcjs have managed to ship with a setup for vscode + hls.
So I wonder, if it is possible with miso too ?
This would be a boost for getting people started with miso apps.

**Comment by smelc** [comment]
This works for me: `nix-shell --run 'code .'`

I'm using `code` provided by `snap` on Ubuntu 20.04 and an instance of `haskell-language-server` downloaded automatically by the corresponding extension.

Note that right now, there are no refactorings available; but _go to definition_ works as well as as-you-type feedback from the compiler.

**Comment by clojj** [comment]
great news.. let me try this on my machine
thx for the update

**Comment by clojj** [comment]
Great, it is working !
if this message is ok ?
![miso-vscode-nix](https://user-images.githubusercontent.com/4367963/96779368-b3854f80-13ec-11eb-8719-d62d018e8f8a.png)

**Comment by smelc** [comment]
Yes this is fine. That's because the `sample-app-jsaddle` doesn't have a `hie.yaml` file describing the code's components. But in this case `haskell-language-server` will infer the correct defaults.

**Comment by clojj** [comment]
I will have to look at jsaddle and see, if I can get a more bare-bones template going...
