### ISSUE TITLE
[Docs] What is (<#) and why does it require a separate action constructor in XHR example?

### ISSUE THREAD

**Issue by avanov** [dmjio/miso#630]
Hi, there's no haddoc section coverig effects at the moment, and the XHR example is scarce on important details about model transitions. Namely, it's not clear what `<#` in the context of `m` and the do block, and it's not clear why the returned payload has to go through `SetGitHub` action instead of being assigned in the same `updateModel FetchGitHub m` case.

https://github.com/dmjio/miso/blob/master/examples/xhr/Main.hs#L49-L53

**Comment by dmjio** [comment]
Hackage doesn't build the GHCJS haddocks, so I host them here: http://haddocks.haskell-miso.org/

`<#` is a smart constructor for building a model transition with an `IO` action that is executed as well. 

When performing IO the model is read-only. All IO is executed asynchronously.

**Comment by avanov** [comment]
thanks for the quick feedback!

I see it now that the official website references your specific haddock domain ionstead of the hackage one. I think it would be good to put a more visible notice somewhere mentioning this GHCJS subtlety when it comes to official hackage-hosted docs. I use duckduckgo with "!h" prefix to search for signatures and packages on hackage, and whilst I was able to find miso, I wasn't able to find anything related to effects and I thought that the sections were not documented. Just a suggestion. I appreciate the dedicated ghcjs host, it makes sense.
