### ISSUE TITLE
Hackage Readme broken in several ways

### ISSUE THREAD

**Issue by turion** [dmjio/miso#635]
While the readme renders ok on https://github.com/dmjio/miso, it is broken on https://hackage.haskell.org/package/miso.

First, there are HTML tags:

![image](https://user-images.githubusercontent.com/303489/99903053-30446b80-2cc2-11eb-8a84-b4b55ff92b1e.png)

Then links are broken:

![image](https://user-images.githubusercontent.com/303489/99903066-4c480d00-2cc2-11eb-921e-4ee969dd8c65.png)

This links to https://hackage.haskell.org/package/miso-1.7.1.0/miso-1.7.1.0/src#todomvc, which doesn't exist.

**Comment by dmjio** [comment]
@turion I think this is a problem with the way hackage renders markdown.

**Comment by dmjio** [comment]
Didn’t mean to close this

**Comment by dmjio** [comment]
hackage links are fixed

- https://hackage.haskell.org/package/miso
- https://haddocks.haskell-miso.org/
