### ISSUE TITLE
todo-mvc: Reproducible build of the CSS file

### ISSUE THREAD

**Issue by MazeChaZer** [dmjio/miso#638]
Right now the CSS file for the TodoMVC example just falls from the sky, as seen in
https://github.com/dmjio/miso/blob/db5400ad7801076a8eac1c071a654b7317b78811/examples/todo-mvc/Main.hs#L182

I assume that it has been built from [tastejs/todomvc-common](https://github.com/tastejs/todomvc-common) and [tastejs/todomvc-app-css](https://github.com/tastejs/todomvc-app-css), as they are part of the official template.

Just linking a CSS file hosted on cloudfront.net makes it impossible to understand where it comes from and how it has been built, if there are bugs like #637 it's impossible to make a pull request to fix it.

It would be nice if the CSS file came directly from this repository or if it would be pulled from [tastejs/todomvc-common](https://github.com/tastejs/todomvc-common) and [tastejs/todomvc-app-css](https://github.com/tastejs/todomvc-app-css) in a build process defined by Nix.

**Comment by dmjio** [comment]
https://github.com/dmjio/miso/commit/658eb44727bfb1dd46f8ea5e30e67a60cecf20a8
