### ISSUE TITLE
callCabal2Nix is returning errors with (direnv+nix-direnv+emacs-direnv) setup?

### ISSUE THREAD

**Issue by zeta-00** [dmjio/miso#641]
Hello There,
Whenever I follow the regular instructions: https://github.com/dmjio/miso#nix , I'm able to get miso and callCabal2Nix working fine, but whenever I try to configure this with my (direnv+nix-direnv+emacs-direnv) setup, I am able to get miso working with this setup in isolated environments, but when I try to get callCabal2Nix working with this setup, errors are returned?

Attached below are the pastebins of the corresponding shell.nix, the tree command which shows the directory structure, and the error thrown, I could't copy all of it because the pastebin was too long, but the entire error message is there.

https://dpaste.org/sTcE#L10

https://dpaste.org/e2Wh#L5

https://dpaste.org/LJNC#L183

I followed the miso instructions for the nix setup very closely and adapted it to my setup, so I don't know if something is incorrect, or if I'm missing something? 

Also here's 3 more links that abathur in irc #nixos, pasted that looks similar to the issue that I'm having here:

https://github.com/NixOS/nixpkgs/issues/47437

https://github.com/ChrisPenner/json-to-haskell-web/blob/f8df5f8e19887b1a5d34f42bee038dbfd1f6ba7d/default.nix#L59-L60

https://github.com/FPtje/miso-component-example/blob/0a931880eb0c9cd660a8e5b077c7dc8ee9467d59/nixpkgs.nix#L39-L51

But I think that I'm close to getting callCabal2Nix working!

Thanks in advance for the help!

**Comment by zeta-00** [comment]
I forgot that these pastebins expire pretty quicky, so I'll paste the stuff here as well!
shell.nix file:
-----------------------------------------------------------------------------------------------------------------------------
{ pkgs ? import <nixpkgs> {}}:

with pkgs;
mkShell
  {
    nativeBuildInputs = with pkgs;
      [
        (haskell.packages.ghc865.ghcWithHoogle (hpkgs: with hpkgs;
          [
            cabal-install
            cabal2nix
            # stack
            haskell-language-server
            implicit-hie
            ghcid

            # web development, miso web-framework:
            miso_1_7_1_0
            # miso-action-logger
            # miso-examples
            miso-from-html

            (pkgs.haskell.packages.ghcjs.callCabal2nix "app" ./. {})
          ]))

        # (pkgs.haskell.packages.ghcjs.callCabal2nix "app" ./. {})
        
      ]; # end of buildInputs

    shellHook =
      ''
         export EDITOR=emacs;
      '';
    
  } # end of mkShell
-----------------------------------------------------------------------------------------------------------------------------

tree command to show the directory structure of the cabal project:
-----------------------------------------------------------------------------------------------------------------------------
[zeta@nixos:/sample-app]$ tree app
app
├── app.cabal
├── Main.hs
└── shell.nix

0 directories, 3 files

[zeta@nixos:/sample-app]$ 
-----------------------------------------------------------------------------------------------------------------------------

the full callCabal2Nix error message:
-----------------------------------------------------------------------------------------------------------------------------
[ 2 of 13] Compiling Network.HTTP.Media.RenderHeader ( src/Network/HTTP/Media/RenderHeader.hs, dist/build/Network/HTTP/Media/RenderHeader.p_o )
[ 3 of 13] Compiling Network.HTTP.Media.Quality ( src/Network/HTTP/Media/Quality.hs, dist/build/Network/HTTP/Media/Quality.p_o )
[12 of 27] Compiling Language.Haskell.LSP.Types.Symbol ( src/Language/Haskell/LSP/Types/Symbol.hs, dist/build/Language/Haskell/LSP/Types/Symbol.o )
configuring
configureFlags: --verbose --prefix=/nix/store/7inb35m785fm5v5cydn56hcyhxq41msn-doctest-0.16.3 --libdir=$prefix/lib/$compiler --libsubdir=$abi/$libname --docdir=/nix/store/d4bz4q3mqv1r0qiq5zg0cscjcd6l6r6c-doctest-0.16.3-doc/share/doc/doctest-0.16.3 --with-gcc=gcc --package-db=/build/package.conf.d --ghc-options=-j8 +RTS -A64M -RTS --disable-split-objs --disable-library-profiling --disable-profiling --enable-shared --disable-coverage --enable-static --disable-executable-dynamic --disable-tests --disable-benchmarks --enable-library-vanilla --disable-library-for-ghci --ghc-option=-split-sections --disable-library-stripping --disable-executable-stripping --ghcjs --extra-lib-dirs=/nix/store/8bb4mkv1r6dvw3a0gmpgdna3m7gdyr8w-ghcjs-8.6.0.1/lib
[3 of 3] Compiling Criterion.Measurement ( src/Criterion/Measurement.hs, dist/build/Criterion/Measurement.o )
[ 4 of 13] Compiling Network.HTTP.Media.Language.Internal ( src/Network/HTTP/Media/Language/Internal.hs, dist/build/Network/HTTP/Media/Language/Internal.p_o )
[ 5 of 13] Compiling Network.HTTP.Media.Language ( src/Network/HTTP/Media/Language.hs, dist/build/Network/HTTP/Media/Language.p_o )
[ 6 of 13] Compiling Network.HTTP.Media.Utils ( src/Network/HTTP/Media/Utils.hs, dist/build/Network/HTTP/Media/Utils.p_o )
[ 7 of 13] Compiling Network.HTTP.Media.MediaType.Internal ( src/Network/HTTP/Media/MediaType/Internal.hs, dist/build/Network/HTTP/Media/MediaType/Internal.p_o )
Using Parsec parser
Configuring doctest-0.16.3...
Dependency base >=4.5 && <5: using base-4.12.0.0
Dependency base-compat >=0.7.0: using base-compat-0.11.1
Dependency code-page >=0.1: using code-page-0.2
Dependency deepseq -any: using deepseq-1.4.4.0
Dependency directory -any: using directory-1.3.3.0
Dependency filepath -any: using filepath-1.4.2.1
Dependency ghc >=7.0 && <8.11: using ghc-8.6.5
Dependency ghc-paths >=0.1.0.9: using ghc-paths-0.1.0.12
Dependency process -any: using process-1.6.5.0
Dependency syb >=0.3: using syb-0.7.1
Dependency transformers -any: using transformers-0.5.6.2
Dependency base >=4.5 && <5: using base-4.12.0.0
Dependency base-compat >=0.7.0: using base-compat-0.11.1
Dependency code-page >=0.1: using code-page-0.2
Dependency deepseq -any: using deepseq-1.4.4.0
Dependency directory -any: using directory-1.3.3.0
Dependency doctest -any: using doctest-0.16.3
Dependency filepath -any: using filepath-1.4.2.1
Dependency ghc >=7.0 && <8.11: using ghc-8.6.5
Dependency ghc-paths >=0.1.0.9: using ghc-paths-0.1.0.12
Dependency process -any: using process-1.6.5.0
Dependency syb >=0.3: using syb-0.7.1
Dependency transformers -any: using transformers-0.5.6.2
Source component graph:
    component lib
    component exe:doctest dependency lib
Configured component graph:
    component doctest-0.16.3-2brPZqUP3rjEpCx0lBL25J
        include base-4.12.0.0-BGkpKxWDclNH5NZN2wRc8Q
        include base-compat-0.11.1-GlimfU6qHwV3VOCKpqzgpL
        include code-page-0.2-AqLQ52mN8NBF6vbkoCggUx
        include deepseq-1.4.4.0-IftsS9ityeGZTtUqULJH7
        include directory-1.3.3.0-5pg72mHzHk4Dhxxy4wYd2z
        include filepath-1.4.2.1-DG92Jon7uT21h5exmtoJCU
        include ghc-8.6.5-5kR8eDcAQgs235a2XOhrTu
        include ghc-paths-0.1.0.12-2KYpm7aF9niFywa7NtYYQP
        include process-1.6.5.0-Wgw4Qh9nsHBTY0LWykUqv
        include syb-0.7.1-8XObCwshap53BK9XAWH8j
        include transformers-0.5.6.2-KaPP0fdMTwBF02jPgfEE5s
    component doctest-0.16.3-FHrjdU0FzLu5yOsXCAkhP1-doctest
        include base-4.12.0.0-BGkpKxWDclNH5NZN2wRc8Q
        include base-compat-0.11.1-GlimfU6qHwV3VOCKpqzgpL
        include code-page-0.2-AqLQ52mN8NBF6vbkoCggUx
        include deepseq-1.4.4.0-IftsS9ityeGZTtUqULJH7
        include directory-1.3.3.0-5pg72mHzHk4Dhxxy4wYd2z
        include doctest-0.16.3-2brPZqUP3rjEpCx0lBL25J
        include filepath-1.4.2.1-DG92Jon7uT21h5exmtoJCU
        include ghc-8.6.5-5kR8eDcAQgs235a2XOhrTu
        include ghc-paths-0.1.0.12-2KYpm7aF9niFywa7NtYYQP
        include process-1.6.5.0-Wgw4Qh9nsHBTY0LWykUqv
        include syb-0.7.1-8XObCwshap53BK9XAWH8j
        include transformers-0.5.6.2-KaPP0fdMTwBF02jPgfEE5s
Linked component graph:
    unit doctest-0.16.3-2brPZqUP3rjEpCx0lBL25J
        include base-4.12.0.0-BGkpKxWDclNH5NZN2wRc8Q
        include base-compat-0.11.1-GlimfU6qHwV3VOCKpqzgpL
        include code-page-0.2-AqLQ52mN8NBF6vbkoCggUx
        include deepseq-1.4.4.0-IftsS9ityeGZTtUqULJH7
        include directory-1.3.3.0-5pg72mHzHk4Dhxxy4wYd2z
        include filepath-1.4.2.1-DG92Jon7uT21h5exmtoJCU
        include ghc-8.6.5-5kR8eDcAQgs235a2XOhrTu
        include ghc-paths-0.1.0.12-2KYpm7aF9niFywa7NtYYQP
        include process-1.6.5.0-Wgw4Qh9nsHBTY0LWykUqv
        include syb-0.7.1-8XObCwshap53BK9XAWH8j
        include transformers-0.5.6.2-KaPP0fdMTwBF02jPgfEE5s
        Test.DocTest=doctest-0.16.3-2brPZqUP3rjEpCx0lBL25J:Test.DocTest
    unit doctest-0.16.3-FHrjdU0FzLu5yOsXCAkhP1-doctest
        include base-4.12.0.0-BGkpKxWDclNH5NZN2wRc8Q
        include base-compat-0.11.1-GlimfU6qHwV3VOCKpqzgpL
        include code-page-0.2-AqLQ52mN8NBF6vbkoCggUx
        include deepseq-1.4.4.0-IftsS9ityeGZTtUqULJH7
        include directory-1.3.3.0-5pg72mHzHk4Dhxxy4wYd2z
        include doctest-0.16.3-2brPZqUP3rjEpCx0lBL25J
        include filepath-1.4.2.1-DG92Jon7uT21h5exmtoJCU
        include ghc-8.6.5-5kR8eDcAQgs235a2XOhrTu
        include ghc-paths-0.1.0.12-2KYpm7aF9niFywa7NtYYQP
        include process-1.6.5.0-Wgw4Qh9nsHBTY0LWykUqv
        include syb-0.7.1-8XObCwshap53BK9XAWH8j
        include transformers-0.5.6.2-KaPP0fdMTwBF02jPgfEE5s
Ready component graph:
    definite doctest-0.16.3-2brPZqUP3rjEpCx0lBL25J
        depends base-4.12.0.0-BGkpKxWDclNH5NZN2wRc8Q
        depends base-compat-0.11.1-GlimfU6qHwV3VOCKpqzgpL
        depends code-page-0.2-AqLQ52mN8NBF6vbkoCggUx
        depends deepseq-1.4.4.0-IftsS9ityeGZTtUqULJH7
        depends directory-1.3.3.0-5pg72mHzHk4Dhxxy4wYd2z
        depends filepath-1.4.2.1-DG92Jon7uT21h5exmtoJCU
        depends ghc-8.6.5-5kR8eDcAQgs235a2XOhrTu
        depends ghc-paths-0.1.0.12-2KYpm7aF9niFywa7NtYYQP
        depends process-1.6.5.0-Wgw4Qh9nsHBTY0LWykUqv
        depends syb-0.7.1-8XObCwshap53BK9XAWH8j
        depends transformers-0.5.6.2-KaPP0fdMTwBF02jPgfEE5s
    definite doctest-0.16.3-FHrjdU0FzLu5yOsXCAkhP1-doctest
        depends base-4.12.0.0-BGkpKxWDclNH5NZN2wRc8Q
        depends base-compat-0.11.1-GlimfU6qHwV3VOCKpqzgpL
        depends code-page-0.2-AqLQ52mN8NBF6vbkoCggUx
        depends deepseq-1.4.4.0-IftsS9ityeGZTtUqULJH7
        depends directory-1.3.3.0-5pg72mHzHk4Dhxxy4wYd2z
        depends doctest-0.16.3-2brPZqUP3rjEpCx0lBL25J
        depends filepath-1.4.2.1-DG92Jon7uT21h5exmtoJCU
        depends ghc-8.6.5-5kR8eDcAQgs235a2XOhrTu
        depends ghc-paths-0.1.0.12-2KYpm7aF9niFywa7NtYYQP
        depends process-1.6.5.0-Wgw4Qh9nsHBTY0LWykUqv
        depends syb-0.7.1-8XObCwshap53BK9XAWH8j
        depends transformers-0.5.6.2-KaPP0fdMTwBF02jPgfEE5s
Using Cabal-2.4.0.1 compiled by ghc-8.6
Using compiler: ghcjs-8.6.0.1
Using install prefix:
/nix/store/7inb35m785fm5v5cydn56hcyhxq41msn-doctest-0.16.3
Executables installed in:
/nix/store/7inb35m785fm5v5cydn56hcyhxq41msn-doctest-0.16.3/bin
Libraries installed in:
/nix/store/7inb35m785fm5v5cydn56hcyhxq41msn-doctest-0.16.3/lib/ghcjs-8.6.0.1/x86_64-linux-ghcjs-8.6.0.1-ghc8_6_5/doctest-0.16.3-2brPZqUP3rjEpCx0lBL25J
Dynamic Libraries installed in:
/nix/store/7inb35m785fm5v5cydn56hcyhxq41msn-doctest-0.16.3/lib/ghcjs-8.6.0.1/x86_64-linux-ghcjs-8.6.0.1-ghc8_6_5
Private executables installed in:
/nix/store/7inb35m785fm5v5cydn56hcyhxq41msn-doctest-0.16.3/libexec/x86_64-linux-ghcjs-8.6.0.1-ghc8_6_5/doctest-0.16.3
Data files installed in:
/nix/store/7inb35m785fm5v5cydn56hcyhxq41msn-doctest-0.16.3/share/x86_64-linux-ghcjs-8.6.0.1-ghc8_6_5/doctest-0.16.3
Documentation installed in:
/nix/store/d4bz4q3mqv1r0qiq5zg0cscjcd6l6r6c-doctest-0.16.3-doc/share/doc/doctest-0.16.3
Configuration files installed in:
/nix/store/7inb35m785fm5v5cydn56hcyhxq41msn-doctest-0.16.3/etc
No alex found
Using ar found on system at:
/nix/store/b10shv9yqbgps47y0n8x7l7bq8fmp1i6-binutils-2.31.1/bin/ar
No c2hs found
No cpphs found
No doctest found
Using gcc version 9.3.0 given by user at:
/nix/store/azayfhqyg9mjyv6rv9bcypi6ws8aqfmy-gcc-wrapper-9.3.0/bin/gcc
Using ghc version 8.6.5 found on system at:
/nix/store/ypw1r9m42rkfjsjzq1a2lyq3zgnykyd9-ghc-8.6.5/bin/ghc
Using ghc-pkg version 8.6.5 found on system at:
/nix/store/ypw1r9m42rkfjsjzq1a2lyq3zgnykyd9-ghc-8.6.5/bin/ghc-pkg
Using ghcjs version 8.6.0.1 found on system at:
/nix/store/8bb4mkv1r6dvw3a0gmpgdna3m7gdyr8w-ghcjs-8.6.0.1/bin/ghcjs
Using ghcjs-pkg version 8.6.5 found on system at:
/nix/store/8bb4mkv1r6dvw3a0gmpgdna3m7gdyr8w-ghcjs-8.6.0.1/bin/ghcjs-pkg
No greencard found
Using haddock version 2.20.0 found on system at:
/nix/store/8bb4mkv1r6dvw3a0gmpgdna3m7gdyr8w-ghcjs-8.6.0.1/bin/haddock-ghcjs
No happy found
Using haskell-suite found on system at: haskell-suite-dummy-location
Using haskell-suite-pkg found on system at: haskell-suite-pkg-dummy-location
No hmake found
Using hpc version 0.67 found on system at:
/nix/store/ypw1r9m42rkfjsjzq1a2lyq3zgnykyd9-ghc-8.6.5/bin/hpc
Using hsc2hs version 0.68.5 found on system at:
/nix/store/8bb4mkv1r6dvw3a0gmpgdna3m7gdyr8w-ghcjs-8.6.0.1/bin/hsc2hs-ghcjs
Using hscolour version 1.24 found on system at:
/nix/store/5xylnbhqs2yfgbqkgnxfp6fxwprq7jwz-hscolour-1.24.4/bin/HsColour
No jhc found
Using ld found on system at:
/nix/store/azayfhqyg9mjyv6rv9bcypi6ws8aqfmy-gcc-wrapper-9.3.0/bin/ld
No pkg-config found
Using runghc version 8.6.5 found on system at:
/nix/store/ypw1r9m42rkfjsjzq1a2lyq3zgnykyd9-ghc-8.6.5/bin/runghc
Using strip version 2.31 found on system at:
/nix/store/b10shv9yqbgps47y0n8x7l7bq8fmp1i6-binutils-2.31.1/bin/strip
Using tar found on system at:
/nix/store/xlfmnfbqryr6s52xgaqfaljmiccrv2rk-gnutar-1.32/bin/tar
No uhc found
building
Preprocessing library for doctest-0.16.3..
Building library for doctest-0.16.3..
[  8 of 228] Compiling GHC.Exts.Heap.Utils ( dist/build/GHC/Exts/Heap/Utils.hs, dist/build/GHC/Exts/Heap/Utils.o )
[  9 of 228] Compiling GHC.Exts.Heap    ( libraries/ghc-heap/GHC/Exts/Heap.hs, dist/build/GHC/Exts/Heap.o )
[ 8 of 13] Compiling Network.HTTP.Media.MediaType ( src/Network/HTTP/Media/MediaType.hs, dist/build/Network/HTTP/Media/MediaType.p_o )
[ 1 of 16] Compiling GhcUtil          ( src/GhcUtil.hs, dist/build/GhcUtil.js_o )

src/GhcUtil.hs:10:1: error:
    Could not find module ‘GHC’
    Use -v to see a list of the files searched for.
   |
10 | import           GHC
   | ^^^^^^^^^^^^^^^^^^^^

src/GhcUtil.hs:11:1: error:
    Could not find module ‘DynFlags’
    Use -v to see a list of the files searched for.
   |
11 | import           DynFlags (gopt_set)
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

src/GhcUtil.hs:13:1: error:
    Could not find module ‘Panic’
    Use -v to see a list of the files searched for.
   |
13 | import           Panic (throwGhcException)
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

src/GhcUtil.hs:15:1: error:
    Could not find module ‘MonadUtils’
    Use -v to see a list of the files searched for.
   |
15 | import           MonadUtils (liftIO)
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: --- Error --- nix-daemon
builder for '/nix/store/gh7fiyzil4jqf91ghd3i3camcjghcjsh-doctest-0.16.3.drv' failed with exit code 1; last 10 log lines:
  13 | import           Panic (throwGhcException)
     | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  
  src/GhcUtil.hs:15:1: error:
      Could not find module ‘MonadUtils’
      Use -v to see a list of the files searched for.
     |
  15 | import           MonadUtils (liftIO)
     | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  
error: --- Error --- nix-daemon
1 dependencies of derivation '/nix/store/2ydrw39xs7m90zcqdyc6x3gxzfxvgmg6-comonad-5.0.6.drv' failed to build
building '/nix/store/gpdf195kxa4a5a6zpmfnkkrbgn92jbb6-hspec-expectations-0.8.2.drv'...
error: --- Error --- nix-daemon
1 dependencies of derivation '/nix/store/wrnasvsy6v7abk2227d0rydppk8f5cw4-http-types-0.12.3.drv' failed to build
building '/nix/store/sad5wrmlg7s4s8b9znvwa0djbxwqddpj-hspec-wai-0.10.1.drv'...
error: --- Error --- nix-daemon
1 dependencies of derivation '/nix/store/5b8znah8hv7kfh49zcadrnyjq02d5pwq-miso-1.6.0.0.drv' failed to build
error: --- Error --- nix-daemon
1 dependencies of derivation '/nix/store/cp8wsm8m78i8h7r6yrj1s1cb69yapyb5-app-0.1.0.0.drv' failed to build
error: --- Error ----------------------------------------- nix-shell
1 dependencies of derivation '/nix/store/6b17g7f67s9q0kqycwc6pdh27v55c0lg-ghc-8.6.5-with-packages.drv' failed to build

[zeta@nixos:/app]$ ls
app.cabal  Main.hs  shell.nix
-----------------------------------------------------------------------------------------------------------------------------

**Comment by dmjio** [comment]
For the best experience, I'd use the default setup. Then progressively try to make things more complex.
