### ISSUE TITLE
Dynamic properties ignored by decoder

### ISSUE THREAD

**Issue by developandplay** [dmjio/miso#646]
**Describe the bug**
When the object that should be decoded has dynamic properties (getters) these will be ignored in the decoder.

**To Reproduce**
Either run [https://github.com/developandplay/material-components-web-miso](https://github.com/developandplay/material-components-web-miso) locally or check out our demo website [matiso.dev](http://www.matiso.dev.s3-website.eu-central-1.amazonaws.com/). Then move the slider and look at the error in the console. (The slider position coordinates might be off when dragging without resizing the screen.)

**Expected behavior**
Dynamic properties should be decoded just like static properties.

**Screenshots**
Unexpected behaviour with expections thrown if dynamic properties are not decoded. As seen in the second screenshot `value` is missing in `newObj` and only the static `value_` is included. In the third screenshot we can see that `value` is an element of `obj` but is a dynamic getter.
![image](https://user-images.githubusercontent.com/34752929/111553685-2ff64180-8785-11eb-9981-a9e5d98d0498.png)
![image](https://user-images.githubusercontent.com/34752929/111553897-8ebbbb00-8785-11eb-9634-51e453cf2451.png)
![image](https://user-images.githubusercontent.com/34752929/111554119-fffb6e00-8785-11eb-9aa9-5474dd25a7d4.png)

Expected behaviour with no exceptions thrown after including dynamic properties in e84d463aaed764810f8d16c033369e9b250a38f8. As seen in the last screenshot `value` is now added to `newObj` when previously only the static `value_` was included.
![image](https://user-images.githubusercontent.com/34752929/111552803-5dda8680-8783-11eb-9412-08043240c9b2.png)
![image](https://user-images.githubusercontent.com/34752929/111554362-81530080-8786-11eb-870f-20cccd484ea7.png)

**Desktop (please complete the following information):**
 - OS: ubuntu
 - Browser: chrome

**Comment by dmjio** [comment]
Can we try doing this w/o the Set.

**Comment by developandplay** [comment]
If you are thinking of replacing the Set with a regular Array then I don't think so.
The Set in this case insures that an attribute/method of an object lower down the protype chain actually [overshadows](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Inheritance_and_the_prototype_chain#inheriting_methods) the ones higher up in the prototype chain.
So if we were to use an array we would still need to check if the attribute already exists.

That being said there might be completly different approaches to this problem that I didn't think of.

One thing I did consider was just checking for the attribute to be decoded in javascript. That could maybe be more efficient but then javascript would need to be aware of the attribute and not just the target. Currently only in Haskell both attribute and target for decoding are exposed.

**Comment by dmjio** [comment]
Merged in https://github.com/dmjio/miso/commit/b32d796ff6ca4434b986fae7844b1df8fe711b54
