### ISSUE TITLE
preventDefault is not working on jsaddle

### ISSUE THREAD

**Issue by cdfa** [dmjio/miso#652]
**Describe the bug**
Using `onWithOptions (Miso.defaultOptions { preventDefault = True })` does not seem to be working when using jsaddle.

**To Reproduce**
1. Create an app that has a `keydown` handler for the "ArrowDown" key with `preventDefault = True`.
2. Open the app and press the "ArrowDown" key

**Expected behavior**
Only the specified action happens.

**Actual behavior**
The page scrolls down a bit.

**Desktop (please complete the following information):**
 - OS: 5.4.105-1-MANJARO GNU/Linux
 - Browser: tested on both Firefox and Chrome
 - Version 1.7.1

**Comment by cdfa** [comment]
Nothing else than the usual. If you're having difficulties reproducing the issue I can modify the sample app a bit, but I'm a bit low on disk space, so I was hoping I wouldn't have to build this repo's nix derivation.

**Comment by dmjio** [comment]
This might be an issue with jsaddle itself.

**Comment by cdfa** [comment]
Sounds plausible. How would I go about figuring that out?

**Comment by dmjio** [comment]
I'd try to make a minimal example of using `preventDefault` with `jsaddle` and with vanilla ghcjs, and check the `jsaddle` source as well.

**Comment by dmjio** [comment]
@cdfa Can you give me a sample application of this exact behavior? I believe `keydown`, unless prevented on `window` will scroll the page. I'd recommend using a subscription for `keydown` in that case.

**Comment by cdfa** [comment]
I think this is related to #668. Will reopen if I find out it's something else.

**Comment by dmjio** [comment]
@cdfa try using `stopPropagation` w/ it.
