### ISSUE TITLE
sample-app isn't working

### ISSUE THREAD

**Issue by arbitrary-dev** [dmjio/miso#655]
**Describe the bug**
`sample-app` isn't working.

**To Reproduce**
1. `cd miso/sample-app`
2. `nix-build`
3. `open ./result/bin/app.jsexe/index.html`
4. ???
5. `command not found: open`

Also this:
```
sample-app $ xdg-open result/bin/app.jsexe/index.html
sample-app $ Gtk-Message: 00:10:31.841: Failed to load module "appmenu-gtk-module"
Gtk-Message: 00:10:31.894: Failed to load module "canberra-gtk-module"
Gtk-Message: 00:10:31.894: Failed to load module "canberra-gtk-module"
[2:25:0523/001031.903827:ERROR:address_tracker_linux.cc(214)] Could not bind NETLINK socket: Address already in use (98)
Opening in existing browser session.
```

...and an empty page is opened.

**Expected behavior**
Working sample app.

**Desktop (please complete the following information):**
 - OS: Pop!_OS 20.10 x86_64
 - Browser: Chrome
 - Version: 90.0.4430.93 (Official Build, ungoogled-chromium) (64-bit)

**Comment by dmjio** [comment]
Can you try `xdg-open ./result/bin/app.jsexe/index.html`

**Comment by arbitrary-dev** [comment]
Ain't it the same as `xdg-open result/bin/app.jsexe/index.html` I tried above?

**Comment by dmjio** [comment]
No, `open` on OSX is in `/usr/bin/open`, it's not available on linux afaik. `xdg-open` should find your preferred browser application. 

https://linux.die.net/man/1/xdg-open

**Comment by arbitrary-dev** [comment]
Yes, I know. What I mean is that I've already tried `xdg-open`, but without `./` prefix for path.

**Comment by dmjio** [comment]
This isn't a problem with miso, but with your local environment.

`Could not bind NETLINK socket: Address already in use (98)`

I'd encourage you to install any missing modules that might exist `Failed to load module "appmenu-gtk-module"`

**Comment by arbitrary-dev** [comment]
What's `NETLINK socket` and where I can configure one?
