### ISSUE TITLE
TouchList not properly parsed, SVG example broken

### ISSUE THREAD

**Issue by nirohank** [dmjio/miso#679]
The SVG example is broken. On touch event:
```
Parse error on touchmove: Error in $[0]: expected [a], encountered Object
CallStack (from HasCallStack):
  error, called at src/Miso/Html/Types.hs:365:20 in miso-1.8.0.0-2TEOtRlVfBi1qwxjiEHDA2:Miso.Html.Types
```

I think it's because `instanceof Array` returns false for the `TouchList` type, even though it looks list-y:
https://github.com/dmjio/miso/blob/master/jsbits/delegate.js#L109

**To Reproduce**
1. https://svg.haskell-miso.org/
2. Open console
3. Enable touch emulation in browser
4. Click (touch) in rectangle
4. See error in console

**Expected behavior**
No error

**Desktop (please complete the following information):**
 - Browser: Chrome & Firefox
 - Version: recent

According to `git blame` this was changed in 2018 from a heuristic that inspects the object like `TouchList` for a `length` property to infer its list-like structure. It seems that:
- the heuristic was the better approach for this case
- this has been broken since 2018

**Comment by dmjio** [comment]
Works fine for me on both firefox and safari, on OSX and Linux. Are you referring to mobile?

**Comment by nirohank** [comment]
addendum: needs click + drag. the error comes on the touchmove event, not the initial click.

**Comment by nirohank** [comment]
![Screenshot from 2021-10-08 14-17-09](https://user-images.githubusercontent.com/78327386/136492960-f1ac3488-f503-41cb-86a4-d227cd947c4e.png)

**Comment by dmjio** [comment]
https://github.com/dmjio/miso/pull/681

**Comment by dmjio** [comment]
Works on mobile now.
