### ISSUE TITLE
Nix-Build Error

### ISSUE THREAD

**Issue by chris-dem** [dmjio/miso#703]
I keep ketting this error `The unauthenticated git protocol on port 9418 is no longer supported.` when running nix-build. Specifically on the link `git://github.com/ghcjs/ghcjs-base (rev 01014ade3f8f5ae677df192d7c2a208bd795b96c) into /nix/store/rw6wianl67igvdka1jrddbsrq3q2kri8-ghcjs-base-01014ad`.
Does anyone have any idea how to resolve this? I have already tried changing my git --config. In addition I did add ssh keys to my github.

**Comment by br4ch1st0chr0n3** [comment]
Hi, @chris-dem. I also got this error. How did you fix it?

**Comment by chris-dem** [comment]
If I remember correctly, I switched to ghc 8.10

**Comment by br4ch1st0chr0n3** [comment]
Thank you, @chris-dem
