### ISSUE TITLE
Nix refuses to build Miso, throwing exit code 137

### ISSUE THREAD

**Issue by aabagdi** [dmjio/miso#717]
**Describe the bug**
So for some reason, although I have not changed anything in my code or my setup, nix refuses to build Miso. It's throwing at me `exit code 137`. Here is the excerpt of the error message:
```
Preprocessing executable 'simple' for miso-1.8.0.0..
Building executable 'simple' for miso-1.8.0.0..
[1 of 1] Compiling Main             ( exe/Main.hs, dist/build/simple/simple-tmp/Main.js_o )
Linking dist/build/simple/simple.jsexe (Main)
/nix/store/7crry947d1xvp1f15c6q089l0gcy5hpc-stdenv-linux/setup: line 1315:  3888 Killed                  ./Setup build
error: builder for '/nix/store/zaw5k6i7lqgxlw7i8aaxvqhknjky3f5x-miso-1.8.0.0.drv' failed with exit code 137
error: 1 dependencies of derivation '/nix/store/gln55w987v3f3jlja355l3kmw6x7rsby-app-0.1.0.0.drv' failed to build
```
I have reinstalled nix and Miso, and restarted my computer to no avail.

**To Reproduce**
1. Go to any miso project and run `nix-build`
2. See error

**Expected behavior**
The program should be building as normal. 

**Desktop (please complete the following information):**
 - Windows 10, using WSL for nix and Miso

**Comment by dmjio** [comment]
It seems like this is the OOM kill issue that occurs during linking if you don’t have enough RAM. I’d try increasing the amount of RAM you’re using in your build machine.

**Comment by aabagdi** [comment]
> It seems like this is the OOM kill issue that occurs during linking if you don’t have enough RAM. I’d try increasing the amount of RAM you’re using in your build machine.

It's weird that it was working fine before, however. I will try changing the amount of memory WSL uses and I'll report back.

**Comment by aabagdi** [comment]
Ah yep! I doubled the memory to 16 GB and it works fine now. Strange that it was working fine before, but oh well. Thanks!
