### ISSUE TITLE
`miso` disappeared from Stackage LTSs

### ISSUE THREAD

**Issue by bingis-khan** [dmjio/miso#727]
Sometime between 2017 (#149) and today, `miso` package disappeared from Stackage LTS. Why did it happen? Would it be possible to re-add it?

**Comment by fizruk** [comment]
You can see here information about the latest snapshots that contain miso: https://www.stackage.org/package/miso

I think this was the reason miso got removed from stackage: https://github.com/commercialhaskell/stackage/issues/6195

**Comment by dmjio** [comment]
This was blocked on jsaddle

https://www.stackage.org/nightly-2024-04-24/package/jsaddle-0.9.9.0
