### ISSUE TITLE
New example application

### ISSUE THREAD

**Issue by functora** [dmjio/miso#737]
Hello! First of all, thanks for the awesome framework! If you wish to do so, you can add link to my currency converter application as an example.

Link:
https://functora.github.io/apps/currency-converter/

Source:
https://github.com/functora/functora.github.io/tree/master/ghcjs/currency-converter

**Comment by dmjio** [comment]
Nice work https://github.com/dmjio/miso/commit/1ed91dec3364464ee4d0221fe0cb32465d0dc849
